/**
 * Chapter 0: Foundations of EKG Waveform Anatomy & Paper Grid
 * Interactive deconstruction of the single cardiac cycle: P, PR, QRS, ST, T, U, and J-point.
 * Strictly zero em-dashes (Unicode U+2014 banned).
 */

import { TutorialStep } from './thalerTypes';
import {
  getCameraForLeads,
  getLeadBounds,
  getMultiLeadBoxes,
  getWaveFeatureGeometry,
} from './thalerGeometry';

// Precomputed feature geometries for Case 0 Foundations (Heart Rate: 72 bpm, PR: 160 ms, QRS: 80 ms)
const calGeom = getWaveFeatureGeometry('CALIBRATION_PULSE', 'CALIBRATION_PULSE', 72, 160, 80);
const pGeom = getWaveFeatureGeometry('II', 'P_WAVE', 72, 160, 80);
const prGeom = getWaveFeatureGeometry('II', 'PR_INTERVAL', 72, 160, 80);
const qrsGeom = getWaveFeatureGeometry('II', 'QRS_COMPLEX', 72, 160, 80);
const stGeom = getWaveFeatureGeometry('II', 'ST_SEGMENT', 72, 160, 80, 0.0);
const tGeom = getWaveFeatureGeometry('II', 'T_WAVE', 72, 160, 80);

export const FOUNDATIONAL_ANATOMY_STEPS: TutorialStep[] = [
  // Step 0.1: Grid Kertas EKG & Pulsa Kalibrasi
  {
    stepIndex: 0,
    stepNumber: 0,
    stepName: 'Fondasi 1: Grid Kertas & Pulsa Kalibrasi',
    stepNameEn: 'Foundation 1: ECG Paper Grid & Calibration Pulse',
    cameraTarget: calGeom.cameraTarget,
    highlightBoxes: [calGeom.boundingBox],
    clinicalFindingTitle: 'Kotak Kecil (1 mm) vs Kotak Besar (5 mm)',
    clinicalFindingTitleEn: 'Small Box (1 mm) vs Large Box (5 mm)',
    triageStatus: 'NORMAL',
    exemplarGroupId: 'INFARCTION_ST_T',
    plainInstructions: [
      'Garis Horisontal (Waktu): Kertas berjalan dengan kecepatan standar 25 mm/detik.',
      '1 Kotak Kecil (1 mm) = tepat 0.04 detik (40 milidetik).',
      '1 Kotak Besar (5 kotak kecil = 5 mm) = tepat 0.20 detik (200 milidetik).',
      '5 Kotak Besar (25 mm) = tepat 1.0 detik. 300 Kotak Besar = 1 menit penuh.',
      'Garis Vertikal (Voltase): Sensitivitas standar adalah 10 mm per 1 milivolt (10 mm/mV).',
      '1 Kotak Kecil = 0.1 milivolt (0.1 mV). 1 Kotak Besar = 0.5 milivolt (0.5 mV).',
      'Pulsa Kalibrasi: Kotak uji di sisi paling kiri wajib setinggi 2 kotak besar (10 mm = 1.0 mV).'
    ],
    plainInstructionsEn: [
      'Horizontal Axis (Time): Standard paper speed runs at 25 mm/second.',
      '1 Small Box (1 mm) = exactly 0.04 seconds (40 milliseconds).',
      '1 Large Box (5 small boxes = 5 mm) = exactly 0.20 seconds (200 milliseconds).',
      '5 Large Boxes (25 mm) = exactly 1.0 second. 300 Large Boxes = 1 full minute.',
      'Vertical Axis (Voltage): Standard calibration sensitivity is 10 mm per 1 millivolt (10 mm/mV).',
      '1 Small Box = 0.1 millivolt (0.1 mV). 1 Large Box = 0.5 millivolt (0.5 mV).',
      'Calibration Pulse: The reference pulse on the far left margin must be 2 large boxes tall (10 mm = 1.0 mV).'
    ],
    thalerRuleQuote: 'Selalu periksa kalibrasi terlebih dahulu. Pulsa standar wajib tepat setinggi dua kotak besar (10 mm). Jika tingginya hanya 5 mm, kalibrasi disetel setengah dan semua voltase harus dikali dua.',
    thalerRuleQuoteEn: 'Always inspect calibration before interpreting the tracing. The standard calibration mark must stand exactly two large boxes (10 mm) tall. If it is only 5 mm, sensitivity is halved and all recorded voltages must be doubled.',
    relevantFormula: '1 mm = 0.04 s | 5 mm = 0.20 s | 10 mm = 1.0 mV',
    relevantFormulaEn: '1 mm = 0.04 s | 5 mm = 0.20 s | 10 mm = 1.0 mV',
    latexFormula: '1\\text{ mm} = 0.04\\text{ s} \\quad | \\quad 5\\text{ mm} = 0.20\\text{ s} \\quad | \\quad 10\\text{ mm} = 1.0\\text{ mV}',
    inSituAnnotation: {
      type: 'CALIBRATION_PULSE',
      targetLead: 'CALIBRATION_PULSE',
      leadRow: 0,
      leadCol: 0,
      label: 'Pulsa Kalibrasi: 10 mm (1.0 mV) x 5 mm (0.20 s)',
      labelEn: 'Calibration Pulse: 10 mm (1.0 mV) x 5 mm (0.20 s)',
      calculationFormula: 'Tinggi = 10 kotak kecil (1.0 mV) | Lebar = 5 kotak kecil (0.20 s)',
      calculationFormulaEn: 'Height = 10 small boxes (1.0 mV) | Width = 5 small boxes (0.20 s)',
      detailExplanation: 'Kotak uji ini membuktikan bahwa mesin EKG mencatat 1 milivolt sebagai defleksi 10 milimeter di atas kertas.',
      detailExplanationEn: 'This reference test pulse confirms that the ECG machine records 1 millivolt as a 10 millimeter vertical deflection.',
      voltageMv: 1.0,
      durationSec: 0.20,
    },
  },

  // Step 0.2: Tiga Kaidah Menghitung Frekuensi Jantung
  {
    stepIndex: 1,
    stepNumber: 0,
    stepName: 'Fondasi 2: Tiga Kaidah Menghitung Frekuensi Jantung',
    stepNameEn: 'Foundation 2: Three Rules for Calculating Heart Rate',
    cameraTarget: getCameraForLeads(['II'], 2.0),
    highlightBoxes: [{
      ...getLeadBounds('II'),
      label: 'Siklus Denyut R-R (Kaidah 300, 1500, dan 6-Detik)',
      labelEn: 'R-R Cardiac Cycle (300, 1500, and 6-Second Rules)',
    }],
    clinicalFindingTitle: 'Kaidah 300, Kaidah 1500, dan Kaidah 6-Detik untuk Irama Ireguler',
    clinicalFindingTitleEn: 'The 300 Rule, 1500 Rule, and 6-Second Method for Irregular Rhythms',
    triageStatus: 'NORMAL',
    exemplarGroupId: 'RATE',
    plainInstructions: [
      'Menghitung frekuensi jantung (Heart Rate) bergantung pada apakah iramanya reguler atau ireguler:',
      '1. Kaidah 300 (Kaidah Kotak Besar untuk Irama Reguler):',
      '   Hitung jumlah kotak besar (5 mm) di antara dua puncak gelombang R yang berurutan. Rumus: HR = 300 / (Jumlah Kotak Besar).',
      '   Rangkaian memori cepat jika puncak R jatuh tepat di garis tebal: 300 -> 150 -> 100 -> 75 -> 60 -> 50 -> 43 -> 37 bpm.',
      '2. Kaidah 1500 (Kaidah Kotak Kecil untuk Presisi Tinggi):',
      '   Jika puncak R berada di antara garis tebal, hitung jumlah kotak kecil (1 mm). Rumus: HR = 1500 / (Jumlah Kotak Kecil). Contoh: 21 kotak kecil = 1500 / 21 = 71 bpm.',
      '3. Kaidah 6-Detik (Untuk Irama Ireguler Total seperti Fibrilasi Atrium):',
      '   Pada irama ireguler, interval R-R selalu berubah sehingga Kaidah 300 atau 1500 TIDAK BISA DIPAKAI! Solusinya: hitung jumlah kompleks QRS dalam 30 kotak besar (30 x 0.2s = 6 detik), lalu kalikan dengan 10. Jika ada 8 QRS dalam 6 detik, maka HR = 8 x 10 = 80 bpm.',
      '4. Kaidah Kertas 10-Detik Penuh: Pada strip ritme 10 detik penuh di bagian bawah (250 mm), hitung seluruh kompleks QRS lalu kalikan 6.'
    ],
    plainInstructionsEn: [
      'Calculating heart rate depends on whether the rhythm is regular or irregular:',
      '1. The 300 Rule (Large Box Method for Regular Rhythms): Count large boxes (5 mm) between two consecutive R wave peaks. Formula: HR = 300 / (Number of Large Boxes). Sequence for R peaks on heavy lines: 300 -> 150 -> 100 -> 75 -> 60 -> 50 -> 43 -> 37 bpm.',
      '2. The 1500 Rule (Small Box Method for High Precision): Count small boxes (1 mm) between R waves. Formula: HR = 1500 / (Number of Small Boxes). Example: 21 small boxes = 1500 / 21 = 71 bpm.',
      '3. The 6-Second Rule (For Irregular Rhythms such as Atrial Fibrillation): On irregular rhythms, R-R intervals vary constantly; the 300 and 1500 rules CANNOT be used! Solution: count QRS complexes within 30 large boxes (30 x 0.2s = 6 seconds) and multiply by 10. For example, 8 QRS in 6 seconds yields HR = 8 x 10 = 80 bpm.',
      '4. The Full 10-Second Paper Strip: On the continuous 10-second rhythm strip along the bottom (250 mm), count all QRS complexes and multiply by 6.'
    ],
    thalerRuleQuote: 'Untuk irama reguler, gunakan kaidah 300 atau 1500. Namun untuk irama ireguler seperti fibrilasi atrium, kaidah 300 mutlak tidak boleh digunakan: hitunglah jumlah denyut dalam interval 6 detik lalu kalikan 10.',
    thalerRuleQuoteEn: 'For regular rhythms, use the 300 or 1500 rule. For irregular rhythms such as atrial fibrillation, the 300 rule must never be used: count the number of complexes in a 6-second interval and multiply by 10.',
    relevantFormula: 'Reguler: 300 / Kotak Besar | Presisi: 1500 / Kotak Kecil | Ireguler: QRS dlm 30 Kotak Besar x 10',
    relevantFormulaEn: 'Regular: 300 / Large Boxes | Precision: 1500 / Small Boxes | Irregular: QRS in 30 Large Boxes x 10',
    latexFormula: '\\text{HR}_{\\text{reguler}} = \\frac{300}{\\text{Kotak Besar}} = \\frac{1500}{\\text{Kotak Kecil}} \\quad | \\quad \\text{HR}_{\\text{ireguler}} = (\\text{QRS dlm 6 s}) \\times 10',
    inSituAnnotation: {
      type: 'RATE_CALIPER',
      targetLead: 'II',
      leadRow: 1,
      leadCol: 0,
      label: 'Kaidah R-R: 4.1 Kotak Besar (21 Kotak Kecil) = 71-73 bpm',
      labelEn: 'R-R Rule: 4.1 Large Boxes (21 Small Boxes) = 71-73 bpm',
      calculationFormula: '300 / 4.17 = 72 bpm | 1500 / 21 = 71.4 bpm (Reguler Normal)',
      calculationFormulaEn: '300 / 4.17 = 72 bpm | 1500 / 21 = 71.4 bpm (Regular Normal)',
      detailExplanation: 'Jarak antara dua puncak R yang stabil menandakan nodus SA melepaskan impuls dengan laju normal 60-100 bpm.',
      detailExplanationEn: 'Stable distance between consecutive R waves confirms the SA node discharges at a normal rate of 60-100 bpm.',
      smallBoxesCount: 21,
      largeBoxesCount: 4.2,
      durationSec: 0.84,
    },
  },

  // Step 0.3: Gelombang P
  {
    stepIndex: 2,
    stepNumber: 0,
    stepName: 'Fondasi 3: Gelombang P (Depolarisasi Atrium)',
    stepNameEn: 'Foundation 3: P Wave (Atrial Depolarization)',
    cameraTarget: pGeom.cameraTarget,
    highlightBoxes: [pGeom.boundingBox],
    clinicalFindingTitle: 'Gelombang P: Cermin Pompa Atrium',
    clinicalFindingTitleEn: 'The P Wave: Window into Atrial Activation',
    triageStatus: 'NORMAL',
    exemplarGroupId: 'RHYTHM',
    plainInstructions: [
      'Fungsi Fisiologis: Mencerminkan penyebaran arus listrik dari Nodus SA ke seluruh atrium kanan dan kiri.',
      'Kriteria Normal (Bagus): Lebar kurang dari 3 kotak kecil (< 0.12 s), tinggi kurang dari 2.5 kotak kecil (< 2.5 mm / 0.25 mV), dan wajib tegak (positif) di Sadapan II serta terbalik (negatif) di aVR.',
      'Kapan Patologis (Jelek)?',
      '1. Terlalu tinggi lancip (> 2.5 mm di Lead II) = P Pulmonale (pembesaran atrium kanan akibat penyakit paru/hipertensi pulmonal).',
      '2. Terlalu lebar berlekuk (>= 0.12 s berbentuk huruf M) = P Mitrale (pembesaran atrium kiri akibat kelainan katup mitral).',
      '3. Hilang total digantikan getaran halus = Fibrilasi Atrium (AFib).'
    ],
    plainInstructionsEn: [
      'Physiological Role: Reflects electrical depolarization spreading from the SA node through the right and left atria.',
      'Normal Criteria: Duration < 3 small boxes (< 0.12 s), amplitude < 2.5 small boxes (< 2.5 mm / 0.25 mV), upright in Lead II, and inverted in Lead aVR.',
      'Pathological Patterns:',
      '1. Tall and peaked (> 2.5 mm in Lead II) = P Pulmonale (right atrial enlargement from pulmonary hypertension or chronic lung disease).',
      '2. Broad and notched (>= 0.12 s, M-shaped) = P Mitrale (left atrial enlargement from mitral valve disease or systemic hypertension).',
      '3. Absent P waves replaced by irregular baseline = Atrial Fibrillation (AFib).'
    ],
    thalerRuleQuote: 'Gelombang P yang normal selalu positif di sadapan II karena depolarisasi atrium mengarah ke bawah dan ke kiri menuju elektroda positif di kaki kiri.',
    thalerRuleQuoteEn: 'Normal P waves are upright in lead II because atrial depolarization spreads downward and to the left toward the positive electrode on the left leg.',
    relevantFormula: 'Durasi P < 0.12 s (3 kotak) | Tinggi P < 2.5 mm (2.5 kotak)',
    relevantFormulaEn: 'P Duration < 0.12 s (3 boxes) | P Amplitude < 2.5 mm (2.5 boxes)',
    latexFormula: '\\text{Durasi P} < 0.12\\text{ s (3 kotak)} \\quad | \\quad \\text{Tinggi P} < 2.5\\text{ mm (0.25 mV)}',
    inSituAnnotation: {
      type: 'INTERVAL_CALIPER',
      targetLead: 'II',
      leadRow: 1,
      leadCol: 0,
      label: 'Gelombang P: Lebar 2 kotak (0.08 s), Tinggi 1.8 mm',
      labelEn: 'P Wave: Width 2 boxes (0.08 s), Height 1.8 mm',
      calculationFormula: '0.08 s < 0.12 s & 1.8 mm < 2.5 mm (Normal)',
      calculationFormulaEn: '0.08 s < 0.12 s & 1.8 mm < 2.5 mm (Normal)',
      detailExplanation: 'Gelombang P mendahului setiap denyut, membuktikan irama berasal dari nodus SA alami.',
      detailExplanationEn: 'P wave precedes every QRS complex, verifying natural SA nodal origin.',
      smallBoxesCount: 2,
      durationSec: 0.08,
      voltageMv: 0.18,
    },
  },

  // Step 0.4: Interval PR
  {
    stepIndex: 3,
    stepNumber: 0,
    stepName: 'Fondasi 4: Interval PR & Jeda Nodus AV',
    stepNameEn: 'Foundation 4: PR Interval & AV Nodal Delay',
    cameraTarget: prGeom.cameraTarget,
    highlightBoxes: [prGeom.boundingBox],
    clinicalFindingTitle: 'Interval PR: Waktu Transit dari Atrium ke Ventrikel',
    clinicalFindingTitleEn: 'PR Interval: Transit Time from Atria to Ventricles',
    triageStatus: 'NORMAL',
    exemplarGroupId: 'CONDUCTION_AV_BLOCK',
    plainInstructions: [
      'Fungsi Fisiologis: Diukur dari awal gelombang P sampai awal kompleks QRS. Mengukur waktu perjalanan listrik dari nodus SA melalui atrium dan nodus AV hingga serabut Purkinje.',
      'Kriteria Normal (Bagus): Berlangsung antara 3 sampai 5 kotak kecil (0.12 hingga 0.20 detik).',
      'Kapan Patologis (Jelek)?',
      '1. Terlalu panjang (> 5 kotak kecil / > 0.20 s) = Blok AV Derajat 1 (konduksi nodus AV melambat).',
      '2. Terlalu pendek (< 3 kotak kecil / < 0.12 s) = Sindrom Wolff-Parkinson-White (impuls melompati nodus AV lewat jalur bypass Kent).',
      '3. Berubah-ubah panjangnya lalu hilang = Blok AV Derajat 2 Mobitz I (Wenckebach).'
    ],
    plainInstructionsEn: [
      'Physiological Role: Measured from P wave onset to initial QRS deflection. Represents electrical conduction time through atria, AV node, and His-Purkinje system.',
      'Normal Criteria: Lasts 3 to 5 small boxes (0.12 to 0.20 seconds).',
      'Pathological Patterns:',
      '1. Prolonged (> 5 small boxes / > 0.20 s) = First-Degree AV Block (delayed AV nodal conduction).',
      '2. Shortened (< 3 small boxes / < 0.12 s) = Wolff-Parkinson-White Syndrome (impulse bypasses AV node via Kent pathway).',
      '3. Progressive lengthening followed by dropped QRS = Second-Degree AV Block Mobitz I (Wenckebach).'
    ],
    thalerRuleQuote: 'Sebagian besar waktu pada interval PR dihabiskan untuk transit lambat di dalam nodus AV. Jeda sepersepuluh detik ini memberi kesempatan bagi atrium untuk mengosongkan darah ke ventrikel.',
    thalerRuleQuoteEn: 'Most of the PR interval is spent in the slow transit through the AV node. This essential delay gives the atria time to empty their blood into the ventricles before ventricular contraction begins.',
    relevantFormula: 'Interval PR Normal = 3 hingga 5 kotak kecil (0.12 s s/d 0.20 s)',
    relevantFormulaEn: 'Normal PR Interval = 3 to 5 small boxes (0.12 s to 0.20 s)',
    latexFormula: '0.12\\text{ s} \\le \\text{Interval PR} \\le 0.20\\text{ s} \\quad (3 - 5\\text{ kotak kecil})',
    inSituAnnotation: {
      type: 'INTERVAL_CALIPER',
      targetLead: 'II',
      leadRow: 1,
      leadCol: 0,
      label: 'Interval PR: 4 Kotak Kecil (0.16 s)',
      labelEn: 'PR Interval: 4 Small Boxes (0.16 s)',
      calculationFormula: '4 kotak x 0.04 s = 0.16 s (Dalam batas 0.12 s s/d 0.20 s)',
      calculationFormulaEn: '4 boxes x 0.04 s = 0.16 s (Within 0.12 s to 0.20 s limit)',
      detailExplanation: 'Jeda konduksi fisiologis nodus AV berjalan sempurna tanpa keterlambatan.',
      detailExplanationEn: 'Normal AV nodal physiological delay occurs without pathological conduction slowing.',
      smallBoxesCount: 4,
      durationSec: 0.16,
    },
  },

  // Step 0.5: Kompleks QRS
  {
    stepIndex: 4,
    stepNumber: 0,
    stepName: 'Fondasi 5: Kompleks QRS (Depolarisasi Ventrikel)',
    stepNameEn: 'Foundation 5: QRS Complex (Ventricular Depolarization)',
    cameraTarget: qrsGeom.cameraTarget,
    highlightBoxes: [qrsGeom.boundingBox],
    clinicalFindingTitle: 'Kompleks QRS: Ledakan Kekuatan Pompa Ventrikel',
    clinicalFindingTitleEn: 'QRS Complex: Ventricular Depolarization and Mechanical Force',
    triageStatus: 'NORMAL',
    exemplarGroupId: 'CONDUCTION_BBB',
    plainInstructions: [
      'Anatomi Gelombang:',
      '• Gelombang Q: Defleksi ke bawah (negatif) pertama sebelum ada gelombang positif.',
      '• Gelombang R: Defleksi ke atas (positif) pertama.',
      '• Gelombang S: Defleksi ke bawah (negatif) pertama setelah gelombang R.',
      'Kriteria Normal (Bagus): Sempit dan tajam, durasi kurang dari 3 kotak kecil (< 0.12 detik, biasanya 0.06 - 0.10 detik).',
      'Kapan Patologis (Jelek)?',
      '1. Melebar (>= 3 kotak kecil / >= 0.12 s) = Blok Cabang Berkas (RBBB/LBBB), pacemaker ventrikel, atau Takikardia Ventrikel (VT).',
      '2. Gelombang Q patologis (lebar >= 1 kotak kecil / >= 0.04 s atau dalamnya > 1/3 tinggi R) = Bekas Infark Miokard (jaringan otot mati/nekrosis).'
    ],
    plainInstructionsEn: [
      'Waveform Anatomy:',
      '• Q Wave: First initial downward (negative) deflection before any upward wave.',
      '• R Wave: First upward (positive) deflection.',
      '• S Wave: First downward (negative) deflection following an R wave.',
      'Normal Criteria: Narrow and sharp, duration < 3 small boxes (< 0.12 seconds, typically 0.06 - 0.10 seconds).',
      'Pathological Patterns:',
      '1. Widened (>= 3 small boxes / >= 0.12 s) = Bundle Branch Block (RBBB/LBBB), ventricular pacemaker, or Ventricular Tachycardia (VT).',
      '2. Pathologic Q wave (width >= 1 small box / >= 0.04 s or depth > 1/3 R wave amplitude) = Prior Myocardial Infarction (necrotic electrically silent tissue).'
    ],
    thalerRuleQuote: 'QRS yang sempit membuktikan bahwa listrik menuruni jalan tol bebas hambatan berkas His dan serabut Purkinje. Jika QRS melebar, listrik terpaksa merayap lambat dari sel otot ke sel otot.',
    thalerRuleQuoteEn: 'A narrow QRS complex proves that depolarization traveled rapidly down the specialized His-Purkinje express system. A widened QRS means conduction was forced to crawl slowly from myocyte to myocyte.',
    relevantFormula: 'Durasi QRS Normal < 0.12 s (< 3 kotak kecil)',
    relevantFormulaEn: 'Normal QRS Duration < 0.12 s (< 3 small boxes)',
    latexFormula: '\\text{Durasi QRS Normal} < 0.12\\text{ s} \\quad (< 3\\text{ kotak kecil})',
    inSituAnnotation: {
      type: 'INTERVAL_CALIPER',
      targetLead: 'II',
      leadRow: 1,
      leadCol: 0,
      label: 'Kompleks QRS: 2 Kotak Kecil (0.08 s)',
      labelEn: 'QRS Complex: 2 Small Boxes (0.08 s)',
      calculationFormula: '2 kotak x 0.04 s = 0.08 s (< 0.12 s: Konduksi Cepat Normal)',
      calculationFormulaEn: '2 boxes x 0.04 s = 0.08 s (< 0.12 s: Normal Rapid Conduction)',
      detailExplanation: 'Depolarisasi ventrikel kanan dan kiri berlangsung serentak melalui jaras Purkinje.',
      detailExplanationEn: 'Simultaneous ventricular depolarization occurs rapidly through intact Purkinje fibers.',
      smallBoxesCount: 2,
      durationSec: 0.08,
    },
  },

  // Step 0.6: Titik J (J-Point) & Segmen ST
  {
    stepIndex: 5,
    stepNumber: 0,
    stepName: 'Fondasi 6: Titik J & Segmen ST (Fase Plateau)',
    stepNameEn: 'Foundation 6: J-Point & ST Segment (Plateau Phase)',
    cameraTarget: stGeom.cameraTarget,
    highlightBoxes: [stGeom.boundingBox],
    clinicalFindingTitle: 'Segmen ST: Tanda Emas Kegawatdaruratan Koroner',
    clinicalFindingTitleEn: 'The ST Segment: The Golden Sign of Coronary Emergencies',
    triageStatus: 'NORMAL',
    exemplarGroupId: 'INFARCTION_ST_T',
    plainInstructions: [
      'Titik J (J-Point): Titik pertemuan persis di mana akhir gelombang S kembali menyentuh garis dasar.',
      'Segmen ST: Garis horisontal antara titik J hingga awal gelombang T. Menggambarkan fase plateau (fase 2 potensial aksi) di mana kedua ventrikel berkontraksi penuh memeras darah.',
      'Kriteria Normal (Bagus): Tepat sejajar garis dasar isoelektrik (tidak naik dan tidak turun).',
      'Kapan Patologis (Jelek)?',
      '1. Melengkung naik cembung (ST Elevation >= 1 mm di 2 sadapan berdekatan) = STEMI (Serangan Jantung Akut Total: segera aktivasi kateterisasi PPCI!).',
      '2. Melorot turun horizontal atau landai (ST Depression >= 1 mm) = Iskemia subendokardial atau regangan hipertensi (LVH strain).'
    ],
    plainInstructionsEn: [
      'J-Point: The exact junction where the end of the S wave returns to the isoelectric baseline.',
      'ST Segment: The horizontal line from the J-point to T wave onset. Represents the action potential plateau (Phase 2) where ventricles are fully contracted.',
      'Normal Criteria: Strictly level with the TP isoelectric baseline (0 mm deviation).',
      'Pathological Patterns:',
      '1. Convex upward elevation (ST elevation >= 1 mm in 2 contiguous leads) = STEMI (Acute Transmural Infarction: activate primary PCI catheterization immediately!).',
      '2. Horizontal or downsloping depression (ST depression >= 1 mm) = Subendocardial ischemia or ventricular strain pattern (LVH).'
    ],
    thalerRuleQuote: 'Elevasi segmen ST yang berbentuk kubah cembung adalah tanda paling berbahaya dalam elektrokardiografi: menunjukkan adanya sumbatan total pembuluh darah koroner yang mengancam nyawa.',
    thalerRuleQuoteEn: 'Convex dome-like ST elevation is the single most urgent finding in clinical electrocardiography: it signals total, acute occlusion of an epicardial coronary artery requiring immediate reperfusion.',
    relevantFormula: 'ST Normal = Isoelektrik (0 mm) | Bahaya jika Elevasi >= 1 mm',
    relevantFormulaEn: 'Normal ST = Isoelectric (0 mm) | Danger if Elevation >= 1 mm',
    latexFormula: '\\text{Segmen ST} = \\text{Isoelektrik (0 mm)} \\quad | \\quad \\text{STEMI jika Elevasi} \\ge 1.0\\text{ mm}',
    inSituAnnotation: {
      type: 'ST_ELEVATION',
      targetLead: 'II',
      leadRow: 1,
      leadCol: 0,
      label: 'Segmen ST: Tepat Isoelektrik (0 mm)',
      labelEn: 'ST Segment: Isoelectric (0 mm)',
      calculationFormula: 'Garis ST sejajar segmen TP (Bebas Cedera Arteri Koroner Akut)',
      calculationFormulaEn: 'ST segment parallel with TP baseline (No Acute Coronary Injury)',
      detailExplanation: 'Tidak ada arus cedera miokardium transmural.',
      detailExplanationEn: 'No active transmural injury currents detected.',
      voltageMv: 0.0,
      smallBoxesCount: 0,
    },
  },

  // Step 0.7: Gelombang T
  {
    stepIndex: 6,
    stepNumber: 0,
    stepName: 'Fondasi 7: Gelombang T (Relaksasi Ventrikel)',
    stepNameEn: 'Foundation 7: T Wave (Ventricular Repolarization)',
    cameraTarget: tGeom.cameraTarget,
    highlightBoxes: [tGeom.boundingBox],
    clinicalFindingTitle: 'Gelombang T: Pemulihan Muatan Listrik Otot',
    clinicalFindingTitleEn: 'The T Wave: Ventricular Electrical Recovery',
    triageStatus: 'NORMAL',
    exemplarGroupId: 'ELECTROLYTES',
    plainInstructions: [
      'Fungsi Fisiologis: Mencerminkan repolarisasi cepat ventrikel (fase 3 potensial aksi) saat otot bersiap menerima denyutan berikutnya.',
      'Kriteria Normal (Bagus): Berbentuk asimetris (naik perlahan, turun lebih curam), tegak searah dengan QRS di sadapan I, II, dan V3-V6.',
      'Kapan Patologis (Jelek)?',
      '1. Terbalik simetris lancip = Iskemia miokard akut.',
      '2. Menjulang tinggi lancip seperti tenda kurva sempit = Hiperkalemia berat (kadar kalium darah tinggi mematikan).',
      '3. Datar atau tertekan = Hipokalemia (kekurangan kalium).'
    ],
    plainInstructionsEn: [
      'Physiological Role: Reflects rapid ventricular repolarization (Phase 3 of action potential) as myocardium resets for the next cardiac cycle.',
      'Normal Criteria: Smoothly asymmetric (gradual upstroke, rapid downstroke), upright concordant with QRS in Leads I, II, and V3-V6.',
      'Pathological Patterns:',
      '1. Inverted and sharply symmetric = Acute myocardial ischemia.',
      '2. Tall, tented, and symmetrically peaked with narrow base = Severe hyperkalemia (life-threatening serum potassium elevation).',
      '3. Flattened or depressed = Hypokalemia (potassium depletion).'
    ],
    thalerRuleQuote: 'Gelombang T yang normal selalu asimetris: lereng naiknya landai sedangkan lereng turunnya curam. Jika gelombang T simetris sempurna, curigailah iskemia atau hiperkalemia.',
    thalerRuleQuoteEn: 'Normal T waves are always asymmetric: the ascending limb is gradual while the descending limb is steep. Symmetrically peaked or inverted T waves should immediately raise suspicion of ischemia or hyperkalemia.',
    relevantFormula: 'Gelombang T Normal: Asimetris, Tegak di I, II, V3-V6',
    relevantFormulaEn: 'Normal T: Asymmetric, Upright in I, II, V3-V6',
    latexFormula: '\\text{T Normal}: \\text{Asimetris, Tegak di } I, II, V_3 - V_6',
    inSituAnnotation: {
      type: 'INTERVAL_CALIPER',
      targetLead: 'II',
      leadRow: 1,
      leadCol: 0,
      label: 'Gelombang T: Asimetris Fisiologis (Tinggi 3.5 mm = 0.35 mV)',
      labelEn: 'T Wave: Physiological Asymmetry (Height 3.5 mm = 0.35 mV)',
      calculationFormula: 'Lereng naik landai, lereng turun curam (Bebas Iskemia Akut)',
      calculationFormulaEn: 'Gradual upstroke, rapid downstroke (Free of Acute Ischemia)',
      detailExplanation: 'Repolarisasi ventrikel berjalan dari epikardium ke endokardium secara harmonis.',
      detailExplanationEn: 'Ventricular repolarization proceeds harmoniously from epicardium to endocardium.',
      voltageMv: 0.35,
      smallBoxesCount: 3.5,
    },
  },

  // Step 0.8: Gelombang U
  {
    stepIndex: 7,
    stepNumber: 0,
    stepName: 'Fondasi 8: Gelombang U (Repolarisasi Lambat)',
    stepNameEn: 'Foundation 8: U Wave (Slow / Purkinje Repolarization)',
    cameraTarget: getCameraForLeads(['V2', 'V3'], 2.6),
    highlightBoxes: [{
      ...getLeadBounds('V2'),
      label: 'Gelombang U (< 1 mm)',
      labelEn: 'U Wave (< 1 mm)',
    }],
    clinicalFindingTitle: 'Gelombang U: Penanda Elektrolit Hipokalemia',
    clinicalFindingTitleEn: 'The U Wave: Marker of Hypokalemia',
    triageStatus: 'NORMAL',
    exemplarGroupId: 'ELECTROLYTES',
    plainInstructions: [
      'Fungsi Fisiologis: Defleksi positif kecil yang kadang muncul tepat setelah gelombang T. Diduga berasal dari repolarisasi lambat serabut Purkinje atau septum interventrikular.',
      'Kriteria Normal (Bagus): Sangat kecil atau seringkali tidak terlihat pada individu normal.',
      'Kapan Patologis (Jelek)?',
      '1. Gelombang U menjadi besar dan menonjol (> 1 mm atau > 25% tinggi T) di sadapan V2-V3 = Hipokalemia (kadar kalium rendah).',
      '2. Gelombang U terbalik = Penyakit arteri koroner berat atau regangan ventrikel kiri berat.'
    ],
    plainInstructionsEn: [
      'Physiological Role: Small positive deflection occasionally appearing immediately following the T wave. Believed to arise from delayed repolarization of Purkinje fibers or mid-myocardial M cells.',
      'Normal Criteria: Very small (< 1 mm) or completely absent in normal healthy individuals.',
      'Pathological Patterns:',
      '1. Prominent giant U waves (> 1 mm or > 25% of T wave height) in V2-V3 = Hypokalemia (low serum potassium).',
      '2. Negative (inverted) U waves = Severe coronary artery disease or severe left ventricular strain.'
    ],
    thalerRuleQuote: 'Munculnya gelombang U yang menonjol bersamaan dengan perataan gelombang T adalah tanda khas hipokalemia. Ini dapat memicu aritmia Torsades de Pointes yang berbahaya.',
    thalerRuleQuoteEn: 'The emergence of prominent U waves alongside T wave flattening is the classic signature of hypokalemia. This prolonged repolarization creates vulnerability to fatal Torsades de Pointes arrhythmias.',
    relevantFormula: 'Gelombang U Normal: Tak tampak atau sangat kecil (< 1 mm)',
    relevantFormulaEn: 'Normal U Wave: Absent or minimal (< 1 mm)',
    latexFormula: '\\text{Gelombang U} < 1\\text{ mm} \\quad (< 25\\% \\text{ Amplitudo T})',
    inSituAnnotation: {
      type: 'INTERVAL_CALIPER',
      targetLead: 'V2',
      leadRow: 1,
      leadCol: 2,
      label: 'Gelombang U: Datar / Minimal Fisiologis',
      labelEn: 'U Wave: Flat / Minimal Physiological',
      calculationFormula: 'Tinggi < 1 mm (Kalium Serum Fisiologis Normal)',
      calculationFormulaEn: 'Height < 1 mm (Normal Physiological Serum Potassium)',
      detailExplanation: 'Tidak ada elongasi repolarisasi yang memicu aritmia ventrikel.',
      detailExplanationEn: 'No repolarization elongation to trigger ventricular arrhythmias.',
      voltageMv: 0.05,
    },
  },

  // Step 0.9: Progresi Sadapan Prekordial V1 s/d V6
  {
    stepIndex: 8,
    stepNumber: 0,
    stepName: 'Fondasi 9: Anatomi Sadapan Dada (V1 s/d V6)',
    stepNameEn: 'Foundation 9: Precordial Lead Anatomy (V1 to V6)',
    cameraTarget: getCameraForLeads(['V1', 'V2', 'V3', 'V4', 'V5', 'V6'], 1.6),
    highlightBoxes: getMultiLeadBoxes(['V1', 'V2', 'V3', 'V4', 'V5', 'V6']),
    clinicalFindingTitle: 'Progresi Gelombang R Normal dari Dada Kanan ke Kiri',
    clinicalFindingTitleEn: 'Normal R-Wave Progression from Right to Left Chest',
    triageStatus: 'NORMAL',
    exemplarGroupId: 'HYPERTROPHY_VENTRICULAR',
    plainInstructions: [
      'Kamera Dada Bergerak dari Kanan ke Kiri:',
      '• V1 & V2 (Septal / Dada Kanan): Menatap ventrikel kanan. QRS didominasi gelombang S yang dalam (pola rS).',
      '• V3 & V4 (Anterior): Zona transisi. Gelombang R dan S memiliki tinggi yang hampir seimbang (pola RS).',
      '• V5 & V6 (Lateral / Dada Kiri): Menatap ventrikel kiri yang tebal. QRS didominasi gelombang R yang tinggi (pola qR).',
      'Kapan Patologis (Jelek)?',
      '1. Poor R-Wave Progression (gelombang R tetap kerdil dari V1 sampai V4) = Bekas Infark Anterior Lama.',
      '2. Gelombang R sangat tinggi di V1 (R > S) = Hipertropi Ventrikel Kanan (RVH) atau Infark Posterior Akut.'
    ],
    plainInstructionsEn: [
      'Chest Leads Camera Sweep from Right to Left:',
      '• V1 & V2 (Septal / Right Chest): Views right ventricle. QRS dominated by deep S waves (rS pattern).',
      '• V3 & V4 (Anterior): Transition zone. R and S waves show near equal amplitude (RS pattern).',
      '• V5 & V6 (Lateral / Left Chest): Views thick left ventricle. QRS dominated by tall R waves (qR pattern).',
      'Pathological Patterns:',
      '1. Poor R-Wave Progression (R wave remains small from V1 through V4) = Prior anterior myocardial infarction.',
      '2. Abnormally tall R wave in V1 (R > S) = Right Ventricular Hypertrophy (RVH) or Acute True Posterior Infarction.'
    ],
    thalerRuleQuote: 'Saat Anda memindai dari sadapan V1 ke V6, gelombang R harus bertumbuh semakin tinggi, sementara gelombang S harus menyusut semakin dangkal. Ini disebut progresi gelombang R normal.',
    thalerRuleQuoteEn: 'As you scan across leads V1 through V6, the R wave should progressively grow taller while the S wave becomes shallower. This orderly transition is normal R-wave progression.',
    relevantFormula: 'V1: rS (R/S < 1) -> V3/V4: RS (Transisi) -> V5/V6: qR (R/S > 1)',
    relevantFormulaEn: 'V1: rS (R/S < 1) -> V3/V4: RS (Transition) -> V5/V6: qR (R/S > 1)',
    latexFormula: 'V_1: rS \\ (R/S < 1) \\longrightarrow V_3/V_4: RS \\longrightarrow V_5/V_6: qR \\ (R/S > 1)',
    inSituAnnotation: {
      type: 'AXIS_VECTOR',
      targetLead: 'V1',
      leadRow: 0,
      leadCol: 2,
      label: 'Progresi R Normal: V1 (r kecil, S dalam) ke V6 (R tinggi)',
      labelEn: 'Normal R Progression: V1 (small r, deep S) to V6 (tall R)',
      calculationFormula: 'Transisi bifasik R=S terjadi di V3 / V4',
      calculationFormulaEn: 'Biphasic R=S transition occurs in V3 / V4',
      detailExplanation: 'Massa otot ventrikel kiri yang tebal mendominasi kelistrikan saat kamera bergerak ke lateral kiri.',
      detailExplanationEn: 'Thick left ventricular myocardium dominates electrical forces as leads move laterally.',
    },
  },

  // Step 0.10: Peta 12 Sadapan & Jebakan Fatal Pemula
  {
    stepIndex: 9,
    stepNumber: 0,
    stepName: 'Fondasi 10: Peta 12 Sadapan & Jebakan Fatal Pemula',
    stepNameEn: 'Foundation 10: 12-Lead Map & Fatal Pitfalls for Beginners',
    cameraTarget: getCameraForLeads(['I', 'II', 'III', 'aVR', 'aVL', 'aVF', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6'], 1.0),
    highlightBoxes: [
      ...getMultiLeadBoxes(['II', 'III', 'aVF']),
      ...getMultiLeadBoxes(['V1', 'V2', 'V3', 'V4']),
      ...getMultiLeadBoxes(['I', 'aVL', 'V5', 'V6']),
      ...getMultiLeadBoxes(['aVR']),
    ],
    clinicalFindingTitle: 'Mengenal Sudut Pandang 12 Sadapan Jantung & Jebakan Penilaian',
    clinicalFindingTitleEn: 'Understanding 12-Lead Perspectives and Diagnostic Pitfalls',
    triageStatus: 'NORMAL',
    exemplarGroupId: 'INFARCTION_ST_T',
    plainInstructions: [
      'Setiap sadapan melihat jantung dari sudut pandang (kamera) yang berbeda:',
      '1. Sadapan Inferior (II, III, aVF): Menatap dinding bawah ventrikel kiri (arteri koroner kanan / RCA). Jebakan: Gelombang Q atau inversi T hanya di lead III seringkali variasi fisiologis normal jika lead II dan aVF positif tegak!',
      '2. Sadapan Septal & Anterior (V1 s/d V4): Menatap septum dan dinding depan (arteri LAD). Jebakan: Di V1, gelombang S dalam dan T terbalik/datar adalah 100% FISIOLOGIS NORMAL!',
      '3. Sadapan Lateral (I, aVL, V5, V6): Menatap dinding samping kiri (arteri sirkumfleksa / LCx). Gelombang T di V5-V6 WAJIB tegak positif. Inversi T di sini selalu patologis!',
      '4. Sadapan aVR (Kavitas Rongga Dalam): Kamera menatap dari bahu kanan ke dalam rongga jantung. Jebakan Fatal: SEMUA gelombang di aVR (P, QRS, T) WAJIB TERBALIK / NEGATIF! Pemula sering panik mengira aVR negatif adalah infark, padahal aVR terbalik adalah normal sempurna.'
    ],
    plainInstructionsEn: [
      'Each lead views the myocardium from a unique anatomical vantage point:',
      '1. Inferior Leads (II, III, aVF): Views inferior left ventricular wall (RCA territory). Pitfall: Isolated Q waves or T inversion in lead III alone is often a normal physiological variant if II and aVF are upright!',
      '2. Septal & Anterior Leads (V1 to V4): Views septum and anterior wall (LAD territory). Pitfall: In V1, deep S waves and flat/inverted T waves are 100% PHYSIOLOGICALLY NORMAL!',
      '3. Lateral Leads (I, aVL, V5, V6): Views lateral left ventricular wall (LCx territory). T waves in V5-V6 MUST be upright. Inverted T waves here are always pathological!',
      '4. Lead aVR (Cavitary View): Views inside the heart from the right shoulder looking into ventricular cavity. Fatal Pitfall: ALL normal deflections in aVR (P, QRS, T) MUST BE INVERTED / NEGATIVE! Beginners frequently mistake negative aVR for infarction; an inverted aVR is perfectly normal.'
    ],
    thalerRuleQuote: 'Jangan pernah mendiagnosis kelainan EKG dari satu sadapan terisolasi. Selalu cari konfirmasi di sadapan anatomis sewilayah (kontigu) dan pahami polaritas fisiologis normal di tiap sadapan, terutama aVR.',
    thalerRuleQuoteEn: 'Never diagnose an abnormality based on a single isolated lead. Always look for confirmation in anatomically contiguous leads and respect normal physiological polarity, especially in lead aVR.',
    relevantFormula: 'Inferior: II, III, aVF | Septal: V1-V2 | Anterior: V3-V4 | Lateral: I, aVL, V5-V6 | Kavitas: aVR',
    relevantFormulaEn: 'Inferior: II, III, aVF | Septal: V1-V2 | Anterior: V3-V4 | Lateral: I, aVL, V5-V6 | Cavitary: aVR',
    latexFormula: '\\text{Inferior: II, III, aVF} \\quad | \\quad \\text{Anteroseptal: } V_1-V_4 \\quad | \\quad \\text{Lateral: I, aVL, } V_5-V_6',
    inSituAnnotation: {
      type: 'AXIS_VECTOR',
      targetLead: 'aVR',
      leadRow: 0,
      leadCol: 1,
      label: 'Sadapan aVR: Polaritas Terbalik Normal (P, QRS, T Negatif)',
      labelEn: 'Lead aVR: Normal Negative Polarity (P, QRS, T Inverted)',
      calculationFormula: 'Kamera bahu kanan memandang menjauh dari arah depolarisasi ventrikel',
      calculationFormulaEn: 'Right shoulder view points away from mean ventricular depolarization',
      detailExplanation: 'Jika gelombang P atau T di aVR positif tegak, periksa kabel elektroda terbalik atau dekstrokardia.',
      detailExplanationEn: 'If P or T waves in aVR are upright, suspect reversed limb electrode leads or dextrocardia.',
    },
  },
];
