/**
 * Visual Exemplar Catalog & Waveform Morphology Database
 * Grounded in Dr. Malcolm S. Thaler's 'The Only EKG Book You'll Ever Need'.
 * Strictly zero em-dashes (Unicode U+2014 banned).
 */

import { VisualExemplarGroup } from './thalerExemplarTypes';

export const THALER_VISUAL_EXEMPLAR_GROUPS: VisualExemplarGroup[] = [
  // 1. ST Segment & J-Point
  {
    id: 'INFARCTION_ST_T',
    groupTitle: 'Segmen ST & Titik J (Iskemia vs Infark vs Varian)',
    groupTitleEn: 'ST Segment & J-Point (Ischemia vs Infarction vs Variants)',
    groupSubtitle: 'Membedakan Oklusi Koroner Akut (STEMI), Iskemia Subendokard, Perikarditis, dan Varian Normal',
    groupSubtitleEn: 'Differentiating Acute Coronary Occlusion (STEMI), Subendocardial Ischemia, Pericarditis, and Normal Variants',
    clinicalEntityKey: 'ST_ELEVATION',
    exemplars: [
      {
        id: 'st_normal_flat',
        category: 'INFARCTION_ST_T',
        triageType: 'NORMAL',
        title: 'Segmen ST Normal (Isoelektrik)',
        titleEn: 'Normal Isoelectric ST Segment',
        medicalTermEn: 'Normal Isoelectric ST Segment',
        badgeLabel: 'Normal',
        badgeLabelEn: 'Normal',
        visualClue: 'Garis ST datar sejajar sempurna dengan garis dasar TP (deviasi 0 mm).',
        visualClueEn: 'Flat ST segment perfectly parallel with the TP baseline (0 mm deviation).',
        clinicalSignificance: 'Perfusi miokardium normal; tidak ada arus cedera aktif.',
        clinicalSignificanceEn: 'Normal myocardial perfusion; no active injury current.',
        diagnosticCriteria: 'Deviasi < 0.5 mm dari garis dasar pada seluruh sadapan.',
        diagnosticCriteriaEn: 'Deviation < 0.5 mm from baseline across all leads.',
        waveformSvgPath: 'M 10,50 L 32,50 C 40,50 42,43 48,43 C 54,43 56,50 64,50 L 78,50 L 82,54 L 88,14 L 96,60 L 102,50 L 124,50 C 134,50 142,32 152,32 C 162,32 168,50 178,50 L 195,50',
        isoelectricY: 50,
        calloutMarker: {
          cx: 112,
          cy: 50,
          label: 'ST Datar (0 mm)',
          labelEn: 'Flat ST (0 mm)',
          type: 'CIRCLE_SPOTLIGHT',
          radius: 8,
        },
      },
      {
        id: 'st_early_repol',
        category: 'INFARCTION_ST_T',
        triageType: 'VARIANT',
        title: 'Repolarisasi Dini Jinak (Early Repol)',
        titleEn: 'Benign Early Repolarization (BER)',
        medicalTermEn: 'Benign Early Repolarization (BER)',
        badgeLabel: 'Varian Jinak',
        badgeLabelEn: 'Benign Variant',
        visualClue: 'Elevasi ST melengkung cekung ke atas (smiling) dengan takik (notch) pada titik J.',
        visualClueEn: 'Upward concave (smiling) ST elevation with prominent J-point notching.',
        clinicalSignificance: 'Varian fisiologis normal pada atlet muda; jangan dikirim kateterisasi darurat.',
        clinicalSignificanceEn: 'Normal physiological variant common in young athletes; avoid unnecessary emergent cath lab transfer.',
        diagnosticCriteria: 'Elevasi ST <= 2 mm di V3-V4, bentuk cekung, takik titik J jelas.',
        diagnosticCriteriaEn: 'ST elevation <= 2 mm in V3-V4, concave morphology, distinct J-point notch.',
        waveformSvgPath: 'M 10,50 L 32,50 C 40,50 42,43 48,43 C 54,43 56,50 64,50 L 78,50 L 82,54 L 88,14 L 96,56 L 99,44 L 102,46 C 112,42 126,38 140,24 C 150,14 160,20 168,50 L 195,50',
        isoelectricY: 50,
        calloutMarker: {
          cx: 101,
          cy: 45,
          label: 'Takik Titik J',
          labelEn: 'J-Point Notch',
          type: 'CIRCLE_SPOTLIGHT',
          radius: 7,
        },
      },
      {
        id: 'stemi_tombstone',
        category: 'INFARCTION_ST_T',
        triageType: 'PATHOLOGY',
        title: 'STEMI Akut (Pola Tombstone)',
        titleEn: 'Acute STEMI (Tombstone Pattern)',
        medicalTermEn: 'Acute STEMI / Transmural Injury',
        badgeLabel: 'Patologi A (Kritis)',
        badgeLabelEn: 'Critical Pathology',
        visualClue: 'Elevasi ST cembung ke atas (frowning) melebur langsung dengan gelombang T tinggi.',
        visualClueEn: 'Convex upward (frowning) ST elevation merging seamlessly into tall T waves.',
        clinicalSignificance: 'Oklusi total arteri koroner; aktivasi cath lab darurat / PCI primer sekarang.',
        clinicalSignificanceEn: 'Total coronary artery occlusion; immediate cath lab activation / primary PCI indicated.',
        diagnosticCriteria: 'Elevasi ST titik J >= 1 mm di sadapan ekstremitas atau >= 2 mm di prekordial.',
        diagnosticCriteriaEn: 'J-point ST elevation >= 1 mm in limb leads or >= 2 mm in precordial leads.',
        waveformSvgPath: 'M 10,50 L 32,50 C 40,50 42,43 48,43 C 54,43 56,50 64,50 L 78,50 L 82,54 L 88,14 L 96,44 L 102,30 C 114,20 134,18 152,22 C 164,26 172,50 185,50 L 195,50',
        isoelectricY: 50,
        calloutMarker: {
          cx: 118,
          cy: 22,
          label: 'Elevasi Cembung (+4 mm)',
          labelEn: 'Convex Elevation (+4 mm)',
          type: 'CIRCLE_SPOTLIGHT',
          radius: 12,
        },
      },
      {
        id: 'st_depression_ischemia',
        category: 'INFARCTION_ST_T',
        triageType: 'PATHOLOGY',
        title: 'Iskemia Subendokard (Depresi ST)',
        titleEn: 'Subendocardial Ischemia (ST Depression)',
        medicalTermEn: 'Subendocardial Ischemia / NSTEMI',
        badgeLabel: 'Patologi B',
        badgeLabelEn: 'Pathology',
        visualClue: 'Depresi segmen ST horizontal atau menurun (downsloping) >= 0.5 mm di bawah garis dasar.',
        visualClueEn: 'Horizontal or downsloping ST depression >= 0.5 mm below baseline.',
        clinicalSignificance: 'Iskemia dinding dalam miokardium (NSTEMI / Angina Pektoris Tidak Stabil).',
        clinicalSignificanceEn: 'Subendocardial myocardial ischemia (NSTEMI / Unstable Angina).',
        diagnosticCriteria: 'Depresi ST horizontal/downsloping >= 0.5 mm diukur 80 ms setelah titik J.',
        diagnosticCriteriaEn: 'Horizontal or downsloping ST depression >= 0.5 mm measured 80 ms after J-point.',
        waveformSvgPath: 'M 10,50 L 32,50 C 40,50 42,43 48,43 C 54,43 56,50 64,50 L 78,50 L 82,54 L 88,14 L 96,64 L 102,64 L 126,64 C 136,64 144,70 152,66 C 160,62 166,50 176,50 L 195,50',
        isoelectricY: 50,
        calloutMarker: {
          cx: 114,
          cy: 64,
          label: 'Depresi Horizontal (-3 mm)',
          labelEn: 'Horizontal Depression (-3 mm)',
          type: 'CIRCLE_SPOTLIGHT',
          radius: 9,
        },
      },
      {
        id: 'pericarditis_pr_dep',
        category: 'INFARCTION_ST_T',
        triageType: 'PATHOLOGY',
        title: 'Perikarditis Akut (Elevasi Cekung Difus)',
        titleEn: 'Acute Pericarditis (Diffuse Concave Elevation)',
        medicalTermEn: 'Acute Pericarditis with PR Depression',
        badgeLabel: 'Patologi C',
        badgeLabelEn: 'Pathology',
        visualClue: 'Elevasi ST cekung difus di hampir semua sadapan disertai depresi segmen PR di Lead II.',
        visualClueEn: 'Diffuse concave ST elevation across nearly all leads with PR depression in Lead II.',
        clinicalSignificance: 'Inflamasi perikardium; trombolisis dikontraindikasikan (memicu tamponade).',
        clinicalSignificanceEn: 'Pericardial inflammation; thrombolysis is contraindicated (risk of tamponade).',
        diagnosticCriteria: 'Elevasi ST cekung difus tanpa resiprokal (kecuali aVR) + depresi PR > 0.8 mm.',
        diagnosticCriteriaEn: 'Diffuse concave ST elevation without reciprocal depression (except aVR) + PR depression > 0.8 mm.',
        waveformSvgPath: 'M 10,50 L 32,50 C 40,50 42,43 48,43 C 54,43 56,54 64,54 L 78,54 L 82,56 L 88,18 L 96,56 L 102,40 C 114,34 130,32 144,28 C 156,26 166,50 178,50 L 195,50',
        isoelectricY: 50,
        calloutMarker: {
          cx: 70,
          cy: 54,
          label: 'Depresi PR',
          labelEn: 'PR Depression',
          type: 'CIRCLE_SPOTLIGHT',
          radius: 7,
        },
      },
      {
        id: 'digoxin_scoop',
        category: 'INFARCTION_ST_T',
        triageType: 'PATHOLOGY',
        title: 'Efek Digoksin (Kumis Salvador Dali)',
        titleEn: 'Digoxin Effect (Salvador Dali Mustache)',
        medicalTermEn: 'Digitalis Effect (Sagging ST)',
        badgeLabel: 'Patologi D',
        badgeLabelEn: 'Pharmacological Effect',
        visualClue: 'Depresi ST melengkung cekung ke bawah seperti kurva centang terbalik atau kumis Salvador Dali.',
        visualClueEn: 'Scooped downsloping ST depression resembling Salvador Dali mustache curve.',
        clinicalSignificance: 'Efek terapeutik obat digitalis pada pompa Na+/K+; bukan berarti toksisitas otomatis.',
        clinicalSignificanceEn: 'Therapeutic effect of digitalis on Na+/K+ pump; does not automatically indicate toxicity.',
        diagnosticCriteria: 'Depresi ST melengkung (sagging) disertai pemendekan interval QTc.',
        diagnosticCriteriaEn: 'Scooped (sagging) ST depression accompanied by shortened QTc interval.',
        waveformSvgPath: 'M 10,50 L 32,50 C 40,50 42,43 48,43 C 54,43 56,50 64,50 L 78,50 L 82,54 L 88,14 L 96,60 L 102,58 C 108,66 120,68 132,64 C 140,60 144,48 154,48 L 195,50',
        isoelectricY: 50,
        calloutMarker: {
          cx: 122,
          cy: 66,
          label: 'ST Cekung Kumis',
          labelEn: 'Scooped ST',
          type: 'CIRCLE_SPOTLIGHT',
          radius: 8,
        },
      },
    ],
  },

  // 2. Frontal Plane QRS Axis
  {
    id: 'AXIS',
    groupTitle: 'Sumbu Jantung Bidang Frontal (Aksis QRS)',
    groupTitleEn: 'Frontal Plane QRS Axis',
    groupSubtitle: 'Metode Kuadran Cepat: Menilai Defleksi Netto Sadapan I dan aVF',
    groupSubtitleEn: 'Fast Quadrant Method: Assessing Net Deflections in Leads I and aVF',
    clinicalEntityKey: 'AXIS',
    exemplars: [
      {
        id: 'axis_normal',
        category: 'AXIS',
        triageType: 'NORMAL',
        title: 'Aksis Normal (0 hingga +90 derajat)',
        titleEn: 'Normal Axis (0 to +90 degrees)',
        medicalTermEn: 'Normal Electrical Axis',
        badgeLabel: 'Normal',
        badgeLabelEn: 'Normal',
        visualClue: 'QRS dominan positif (R tinggi) di Sadapan I DAN Sadapan aVF.',
        visualClueEn: 'Predominantly positive QRS (tall R wave) in Lead I AND Lead aVF.',
        clinicalSignificance: 'Arah aliran listrik ventrikel normal ke arah inferior kiri.',
        clinicalSignificanceEn: 'Normal ventricular electrical depolarization directed inferiorly and to the left.',
        diagnosticCriteria: 'R > S pada Sadapan I dan Sadapan aVF.',
        diagnosticCriteriaEn: 'R > S in both Lead I and Lead aVF.',
        waveformSvgPath: 'M 10,50 L 35,50 L 40,54 L 46,16 L 52,58 L 58,50 L 100,50 L 135,50 L 140,54 L 146,16 L 152,58 L 158,50 L 195,50',
        isoelectricY: 50,
        calloutMarker: {
          cx: 46,
          cy: 16,
          label: 'Lead I (+), aVF (+)',
          labelEn: 'Lead I (+), aVF (+)',
          type: 'CIRCLE_SPOTLIGHT',
          radius: 10,
        },
      },
      {
        id: 'axis_lad',
        category: 'AXIS',
        triageType: 'PATHOLOGY',
        title: 'Deviasi Aksis Kiri / LAD (-30 hingga -90 derajat)',
        titleEn: 'Left Axis Deviation / LAD (-30 to -90 degrees)',
        medicalTermEn: 'Left Axis Deviation (LAD)',
        badgeLabel: 'Patologi A',
        badgeLabelEn: 'Pathology',
        visualClue: 'QRS positif di Sadapan I, tetapi dominan negatif (S dalam) di Sadapan aVF dan Lead II.',
        visualClueEn: 'QRS positive in Lead I, but predominantly negative (deep S wave) in Lead aVF and Lead II.',
        clinicalSignificance: 'Disebabkan Left Anterior Fascicular Block (LAFB), LVH berat, atau infark inferior.',
        clinicalSignificanceEn: 'Etiology includes Left Anterior Fascicular Block (LAFB), severe LVH, or inferior infarction.',
        diagnosticCriteria: 'Lead I (+), aVF (-), Lead II (-).',
        diagnosticCriteriaEn: 'Lead I (+), aVF (-), Lead II (-).',
        waveformSvgPath: 'M 10,50 L 35,50 L 40,54 L 46,14 L 52,56 L 58,50 L 100,50 L 135,50 L 140,46 L 146,40 L 152,82 L 158,50 L 195,50',
        isoelectricY: 50,
        calloutMarker: {
          cx: 152,
          cy: 82,
          label: 'aVF Negatif (S Dalam)',
          labelEn: 'aVF Negative (Deep S)',
          type: 'CIRCLE_SPOTLIGHT',
          radius: 10,
        },
      },
      {
        id: 'axis_rad',
        category: 'AXIS',
        triageType: 'PATHOLOGY',
        title: 'Deviasi Aksis Kanan / RAD (+90 hingga +180 derajat)',
        titleEn: 'Right Axis Deviation / RAD (+90 to +180 degrees)',
        medicalTermEn: 'Right Axis Deviation (RAD)',
        badgeLabel: 'Patologi B',
        badgeLabelEn: 'Pathology',
        visualClue: 'QRS dominan negatif di Sadapan I, tetapi dominan positif di Sadapan aVF.',
        visualClueEn: 'Predominantly negative QRS in Lead I, but predominantly positive in Lead aVF.',
        clinicalSignificance: 'Disebabkan Hipertrofi Ventrikel Kanan (RVH), emboli paru akut, atau LPFB.',
        clinicalSignificanceEn: 'Etiology includes Right Ventricular Hypertrophy (RVH), acute pulmonary embolism, or LPFB.',
        diagnosticCriteria: 'Lead I (-), aVF (+).',
        diagnosticCriteriaEn: 'Lead I (-), aVF (+).',
        waveformSvgPath: 'M 10,50 L 35,50 L 40,46 L 46,42 L 52,82 L 58,50 L 100,50 L 135,50 L 140,54 L 146,14 L 152,56 L 158,50 L 195,50',
        isoelectricY: 50,
        calloutMarker: {
          cx: 52,
          cy: 82,
          label: 'Lead I Negatif',
          labelEn: 'Lead I Negative',
          type: 'CIRCLE_SPOTLIGHT',
          radius: 10,
        },
      },
      {
        id: 'axis_extreme',
        category: 'AXIS',
        triageType: 'PATHOLOGY',
        title: 'Aksis Ekstrem / No Man\'s Land (-90 hingga 180 derajat)',
        titleEn: 'Extreme Right Axis / "No Man\'s Land" (-90 to 180 degrees)',
        medicalTermEn: 'Extreme Right Axis Deviation',
        badgeLabel: 'Patologi C',
        badgeLabelEn: 'Critical Pathology',
        visualClue: 'QRS dominan negatif di KEDUA Sadapan I dan aVF secara bersamaan.',
        visualClueEn: 'Predominantly negative QRS in BOTH Lead I and aVF simultaneously.',
        clinicalSignificance: 'Kecurigaan tinggi Takikardia Ventrikular (VT) atau salah pasang elektroda ekstremitas.',
        clinicalSignificanceEn: 'High suspicion for Ventricular Tachycardia (VT) or reversed limb lead placement.',
        diagnosticCriteria: 'Lead I (-) dan aVF (-).',
        diagnosticCriteriaEn: 'Lead I (-) and aVF (-).',
        waveformSvgPath: 'M 10,50 L 35,50 L 40,46 L 46,40 L 52,82 L 58,50 L 100,50 L 135,50 L 140,46 L 146,40 L 152,82 L 158,50 L 195,50',
        isoelectricY: 50,
        calloutMarker: {
          cx: 100,
          cy: 80,
          label: 'I (-) & aVF (-)',
          labelEn: 'I (-) & aVF (-)',
          type: 'CIRCLE_SPOTLIGHT',
          radius: 12,
        },
      },
    ],
  },

  // 3. Rhythm & P Wave Morphology
  {
    id: 'RHYTHM',
    groupTitle: 'Irama & Morfologi Gelombang P',
    groupTitleEn: 'Rhythm & P Wave Morphology',
    groupSubtitle: 'Menilai Irama Sinus vs Fibrilasi Atrium vs Flutter vs Takikardia',
    groupSubtitleEn: 'Differentiating Sinus Rhythm vs Atrial Fibrillation vs Flutter vs Tachycardia',
    clinicalEntityKey: 'RHYTHM',
    exemplars: [
      {
        id: 'rhythm_nsr',
        category: 'RHYTHM',
        triageType: 'NORMAL',
        title: 'Irama Sinus Normal (NSR)',
        titleEn: 'Normal Sinus Rhythm (NSR)',
        medicalTermEn: 'Normal Sinus Rhythm',
        badgeLabel: 'Normal',
        badgeLabelEn: 'Normal',
        visualClue: 'Gelombang P tegak seragam di Sadapan II mendahului setiap kompleks QRS dengan interval konstan.',
        visualClueEn: 'Uniform upright P waves in Lead II preceding every QRS with a constant PR interval.',
        clinicalSignificance: 'Pacemaker alami nodus SA berfungsi normal pada frekuensi 60-100 bpm.',
        clinicalSignificanceEn: 'Normal SA node pacemaker pacing at 60-100 bpm.',
        diagnosticCriteria: 'Rasio P:QRS 1:1, PR interval 120-200 ms, laju 60-100 bpm.',
        diagnosticCriteriaEn: '1:1 P:QRS ratio, PR interval 120-200 ms, rate 60-100 bpm.',
        waveformSvgPath: 'M 5,50 C 12,50 14,42 19,42 C 24,42 26,50 32,50 L 40,50 L 43,54 L 48,16 L 53,60 L 57,50 L 68,50 C 76,50 82,34 90,34 C 98,34 104,50 112,50 L 118,50 C 125,50 127,42 132,42 C 137,42 139,50 145,50 L 153,50 L 156,54 L 161,16 L 166,60 L 170,50 L 181,50 C 189,50 195,34 200,34',
        isoelectricY: 50,
        calloutMarker: {
          cx: 19,
          cy: 42,
          label: 'P Sinus Seragam',
          labelEn: 'Uniform Sinus P',
          type: 'CIRCLE_SPOTLIGHT',
          radius: 6,
        },
      },
      {
        id: 'rhythm_afib',
        category: 'RHYTHM',
        triageType: 'PATHOLOGY',
        title: 'Fibrilasi Atrium (AFib)',
        titleEn: 'Atrial Fibrillation (AFib)',
        medicalTermEn: 'Atrial Fibrillation (Irregularly Irregular)',
        badgeLabel: 'Patologi A',
        badgeLabelEn: 'Pathology',
        visualClue: 'Tidak ada gelombang P; garis dasar bergelombang acak halus dengan jarak R-R ireguler total.',
        visualClueEn: 'Absence of P waves; fine undulating baseline with completely irregular R-R intervals.',
        clinicalSignificance: 'Hilangnya kontraksi atrium efektif; risiko tinggi stroke tromboemboli.',
        clinicalSignificanceEn: 'Loss of effective atrial contraction; high risk of thromboembolic stroke.',
        diagnosticCriteria: 'Garis fibrilasi (350-600/menit), interval R-R tidak beraturan tanpa pola.',
        diagnosticCriteriaEn: 'Fibrillatory f waves (350-600/min), irregularly irregular R-R intervals.',
        waveformSvgPath: 'M 5,49 Q 10,52 15,48 Q 20,53 25,49 L 32,50 L 35,54 L 40,16 L 45,60 L 49,50 Q 55,47 62,53 Q 70,48 78,52 Q 88,47 96,52 L 102,50 L 105,54 L 110,16 L 115,60 L 119,50 Q 128,47 138,53 Q 148,48 158,52 Q 166,48 174,52 L 180,50 L 183,54 L 188,16 L 193,60 L 197,50',
        isoelectricY: 50,
        calloutMarker: {
          cx: 65,
          cy: 50,
          label: 'Garis Fibrilasi Acak',
          labelEn: 'Random Fibrillatory Baseline',
          type: 'CIRCLE_SPOTLIGHT',
          radius: 12,
        },
      },
      {
        id: 'rhythm_aflutter',
        category: 'RHYTHM',
        triageType: 'PATHOLOGY',
        title: 'Atrial Flutter (Gigi Gergaji)',
        titleEn: 'Atrial Flutter (Sawtooth Pattern)',
        medicalTermEn: 'Atrial Flutter with 2:1 Block',
        badgeLabel: 'Patologi B',
        badgeLabelEn: 'Pathology',
        visualClue: 'Gelombang flutter negatif menyerupai gigi gergaji (sawtooth) teratur pada laju atrium tepat 300 bpm.',
        visualClueEn: 'Negative flutter waves resembling regular sawteeth at an atrial rate of 300 bpm.',
        clinicalSignificance: 'Sirkuit reentri atrium kanan; respons ventrikel 2:1 klasik menghasilkan laju 150 bpm.',
        clinicalSignificanceEn: 'Right atrial macro-reentrant circuit; 2:1 AV block produces classic rate of 150 bpm.',
        diagnosticCriteria: 'Gelombang F gigi gergaji di sadapan inferior pada laju 250-350 bpm.',
        diagnosticCriteriaEn: 'Sawtooth F waves in inferior leads at 250-350 bpm.',
        waveformSvgPath: 'M 5,50 L 15,62 L 25,48 L 35,62 L 45,48 L 48,54 L 52,16 L 56,60 L 60,50 L 70,62 L 80,48 L 90,62 L 100,48 L 103,54 L 107,16 L 111,60 L 115,50 L 125,62 L 135,48 L 145,62 L 155,48 L 158,54 L 162,16 L 166,60 L 170,50 L 180,62 L 190,48 L 200,62',
        isoelectricY: 50,
        calloutMarker: {
          cx: 25,
          cy: 55,
          label: 'Gigi Gergaji (300 bpm)',
          labelEn: 'Sawtooth Waves (300 bpm)',
          type: 'CIRCLE_SPOTLIGHT',
          radius: 10,
        },
      },
      {
        id: 'rhythm_vt',
        category: 'RHYTHM',
        triageType: 'PATHOLOGY',
        title: 'Takikardia Ventrikular (VT Monomorfik)',
        titleEn: 'Monomorphic Ventricular Tachycardia (VT)',
        medicalTermEn: 'Monomorphic Ventricular Tachycardia',
        badgeLabel: 'Patologi C (Fatal)',
        badgeLabelEn: 'Lethal Pathology',
        visualClue: 'Kompleks QRS sangat lebar (> 140 ms), aneh, cepat (140-220 bpm) tanpa gelombang P.',
        visualClueEn: 'Extremely wide (> 140 ms), bizarre, rapid (140-220 bpm) QRS complexes without P waves.',
        clinicalSignificance: 'Aritmia ventrikel mematikan; risiko henti jantung mendadak / syok kardiogenik.',
        clinicalSignificanceEn: 'Malignant ventricular arrhythmia; high risk of sudden cardiac arrest or cardiogenic shock.',
        diagnosticCriteria: 'QRS >= 140 ms, disosiasi AV, capture beat, laju ventrikel cepat konstan.',
        diagnosticCriteriaEn: 'QRS >= 140 ms, AV dissociation, capture/fusion beats, rapid constant rate.',
        waveformSvgPath: 'M 5,72 C 10,72 16,14 24,14 C 32,14 36,78 44,78 C 50,78 56,14 64,14 C 72,14 76,78 84,78 C 90,78 96,14 104,14 C 112,14 116,78 124,78 C 130,78 136,14 144,14 C 152,14 156,78 164,78 C 170,78 176,14 184,14 C 192,14 196,78 200,78',
        isoelectricY: 50,
        calloutMarker: {
          cx: 64,
          cy: 20,
          label: 'QRS Sangat Lebar',
          labelEn: 'Markedly Wide QRS',
          type: 'CIRCLE_SPOTLIGHT',
          radius: 14,
        },
      },
    ],
  },

  // 4. Conduction Blocks (AV Block)
  {
    id: 'CONDUCTION_AV_BLOCK',
    groupTitle: 'Gangguan Konduksi: Blok Atrioventrikular (AV Block)',
    groupTitleEn: 'Conduction Disorders: Atrioventricular (AV) Blocks',
    groupSubtitle: 'Evaluasi Perlambatan Impuls dari Atrium ke Ventrikel',
    groupSubtitleEn: 'Evaluating Electrical Impulse Delay from Atria to Ventricles',
    clinicalEntityKey: 'AV_BLOCK',
    exemplars: [
      {
        id: 'av_block_normal',
        category: 'CONDUCTION_AV_BLOCK',
        triageType: 'NORMAL',
        title: 'Konduksi AV Normal 1:1',
        titleEn: 'Normal 1:1 AV Conduction',
        medicalTermEn: 'Normal AV Conduction',
        badgeLabel: 'Normal',
        badgeLabelEn: 'Normal',
        visualClue: 'Setiap gelombang P diikuti QRS dengan interval PR konstan antara 120 hingga 200 ms.',
        visualClueEn: 'Every P wave followed by QRS with a constant PR interval between 120 and 200 ms.',
        clinicalSignificance: 'Transmisi impuls melalui Nodus AV dan berkas His berlangsung normal.',
        clinicalSignificanceEn: 'Normal impulse transmission through AV node and His bundle.',
        diagnosticCriteria: 'PR interval = 3 hingga 5 kotak kecil (120-200 ms).',
        diagnosticCriteriaEn: 'PR interval = 3 to 5 small boxes (120-200 ms).',
        waveformSvgPath: 'M 5,50 C 12,50 14,42 20,42 C 26,42 28,50 35,50 L 52,50 L 55,54 L 60,16 L 65,60 L 69,50 L 90,50 C 98,50 104,34 112,34 C 120,34 126,50 134,50 L 195,50',
        isoelectricY: 50,
        calloutMarker: {
          cx: 36,
          cy: 50,
          width: 32,
          height: 8,
          label: 'PR 160 ms (Normal)',
          labelEn: 'PR 160 ms (Normal)',
          type: 'BRACKET_INTERVAL',
        },
      },
      {
        id: 'av_block_first_deg',
        category: 'CONDUCTION_AV_BLOCK',
        triageType: 'PATHOLOGY',
        title: 'Blok AV Derajat 1',
        titleEn: 'First-Degree AV Block',
        medicalTermEn: 'First-Degree AV Block',
        badgeLabel: 'Patologi A',
        badgeLabelEn: 'Pathology',
        visualClue: 'Setiap gelombang P tetap diikuti QRS, tetapi interval PR memanjang konstan > 200 ms (> 5 kotak kecil).',
        visualClueEn: 'Every P wave conducts to QRS, but PR interval is constantly prolonged > 200 ms (> 5 small boxes).',
        clinicalSignificance: 'Perlambatan fisiologis di Nodus AV; biasanya jinak namun waspada intoksikasi obat.',
        clinicalSignificanceEn: 'Conduction delay in AV node; usually benign but watch for drug toxicity.',
        diagnosticCriteria: 'PR interval tetap > 200 ms pada semua denyut tanpa ada QRS yang jatuh.',
        diagnosticCriteriaEn: 'Constant PR > 200 ms on all beats without dropped QRS.',
        waveformSvgPath: 'M 5,50 C 12,50 14,42 20,42 C 26,42 28,50 35,50 L 68,50 L 71,54 L 76,16 L 81,60 L 85,50 L 105,50 C 113,50 119,34 127,34 C 135,34 141,50 149,50 L 195,50',
        isoelectricY: 50,
        calloutMarker: {
          cx: 35,
          cy: 50,
          width: 48,
          height: 8,
          label: 'PR Memanjang (> 240 ms)',
          labelEn: 'Prolonged PR (> 240 ms)',
          type: 'BRACKET_INTERVAL',
        },
      },
      {
        id: 'av_block_mobitz_1',
        category: 'CONDUCTION_AV_BLOCK',
        triageType: 'PATHOLOGY',
        title: 'Blok AV Derajat 2 Mobitz I (Wenckebach)',
        titleEn: 'Second-Degree AV Block Mobitz I (Wenckebach)',
        medicalTermEn: 'Second-Degree AV Block Mobitz I',
        badgeLabel: 'Patologi B',
        badgeLabelEn: 'Pathology',
        visualClue: 'Interval PR makin lama makin panjang dari denyut ke denyut sampai 1 gelombang P gagal diteruskan (QRS hilang).',
        visualClueEn: 'Progressive PR lengthening beat-to-beat until a single P wave fails to conduct (dropped QRS).',
        clinicalSignificance: 'Kelelahan bertahap di Nodus AV; biasanya reversibel dan jarang membutuhkan pacu jantung.',
        clinicalSignificanceEn: 'Progressive AV nodal fatigue; usually reversible and rarely requires pacing.',
        diagnosticCriteria: 'Pemanjangan PR progresif diikuti gelombang P tanpa QRS.',
        diagnosticCriteriaEn: 'Progressive PR prolongation followed by non-conducted P wave.',
        waveformSvgPath: 'M 5,50 C 10,50 12,42 16,42 C 20,42 22,50 26,50 L 36,50 L 39,54 L 44,16 L 49,60 L 53,50 L 65,50 C 70,50 72,42 76,42 C 80,42 82,50 86,50 L 104,50 L 107,54 L 112,16 L 117,60 L 121,50 L 135,50 C 140,50 142,42 146,42 C 150,42 152,50 156,50 L 195,50',
        isoelectricY: 50,
        calloutMarker: {
          cx: 156,
          cy: 42,
          label: 'P Gagal Conduct (Dropped)',
          labelEn: 'Dropped QRS Complex',
          type: 'CIRCLE_SPOTLIGHT',
          radius: 10,
        },
      },
      {
        id: 'av_block_third_deg',
        category: 'CONDUCTION_AV_BLOCK',
        triageType: 'PATHOLOGY',
        title: 'Blok AV Derajat 3 (Total AV Block)',
        titleEn: 'Third-Degree (Complete) AV Block',
        medicalTermEn: 'Third-Degree (Complete) AV Block',
        badgeLabel: 'Patologi C (Kritis)',
        badgeLabelEn: 'Critical Pathology',
        visualClue: 'Disosiasi total: Gelombang P berbaris teratur sendiri (~75 bpm) dan QRS berbaris lambat sendiri (~35 bpm).',
        visualClueEn: 'Complete dissociation: Regular P waves march independently (~75 bpm) from slow regular QRS (~35 bpm).',
        clinicalSignificance: 'Pemutusan listrik total antara atrium dan ventrikel; indikasi pacu jantung permanen darurat.',
        clinicalSignificanceEn: 'Complete electrical discontinuity between atria and ventricles; requires emergent pacemaker.',
        diagnosticCriteria: 'Laju atrium lebih cepat dari laju ventrikel, interval PR bervariasi acak.',
        diagnosticCriteriaEn: 'Atrial rate faster than ventricular rate, completely variable PR intervals.',
        waveformSvgPath: 'M 5,50 C 10,50 12,42 16,42 C 20,42 22,50 26,50 L 32,50 L 35,54 L 42,16 L 49,60 L 55,50 L 65,50 C 70,50 72,42 76,42 C 80,42 82,50 86,50 L 120,50 C 125,50 127,42 131,42 C 135,42 137,50 141,50 L 148,50 L 151,54 L 158,16 L 165,60 L 171,50 L 180,50 C 185,50 187,42 191,42',
        isoelectricY: 50,
        calloutMarker: {
          cx: 76,
          cy: 42,
          label: 'P Berjalan Sendiri',
          labelEn: 'Independent P Waves',
          type: 'CIRCLE_SPOTLIGHT',
          radius: 8,
        },
      },
    ],
  },

  // 5. Conduction Blocks (Bundle Branch Block)
  {
    id: 'CONDUCTION_BBB',
    groupTitle: 'Gangguan Konduksi: Blok Cabang Berkas (BBB)',
    groupTitleEn: 'Conduction Disorders: Bundle Branch Blocks (BBB)',
    groupSubtitle: 'Evaluasi Pelebaran Kompleks QRS di Sadapan Prekordial V1 dan Lateral V6',
    groupSubtitleEn: 'Evaluating QRS Widening in Precordial Lead V1 and Lateral Lead V6',
    clinicalEntityKey: 'BUNDLE_BRANCH_BLOCK',
    exemplars: [
      {
        id: 'bbb_normal',
        category: 'CONDUCTION_BBB',
        triageType: 'NORMAL',
        title: 'Kompleks QRS Ramping Normal (< 120 ms)',
        titleEn: 'Normal Narrow QRS Duration (< 120 ms)',
        medicalTermEn: 'Normal Narrow QRS Duration',
        badgeLabel: 'Normal',
        badgeLabelEn: 'Normal',
        visualClue: 'Kompleks QRS sempit tajam berdurasi di bawah 3 kotak kecil (< 120 ms).',
        visualClueEn: 'Narrow sharp QRS complex lasting less than 3 small boxes (< 120 ms).',
        clinicalSignificance: 'Aktivasi kedua ventrikel serentak melalui serabut Purkinje yang utuh.',
        clinicalSignificanceEn: 'Simultaneous ventricular activation through intact Purkinje fibers.',
        diagnosticCriteria: 'Durasi QRS < 0.10 hingga 0.12 detik.',
        diagnosticCriteriaEn: 'QRS duration < 0.10 to 0.12 seconds.',
        waveformSvgPath: 'M 10,50 L 45,50 L 49,54 L 54,16 L 59,60 L 63,50 L 195,50',
        isoelectricY: 50,
        calloutMarker: {
          cx: 54,
          cy: 50,
          width: 18,
          height: 8,
          label: 'QRS Sempit (80 ms)',
          labelEn: 'Narrow QRS (80 ms)',
          type: 'BRACKET_INTERVAL',
        },
      },
      {
        id: 'bbb_rbbb',
        category: 'CONDUCTION_BBB',
        triageType: 'PATHOLOGY',
        title: 'Right Bundle Branch Block (RBBB)',
        titleEn: 'Right Bundle Branch Block (RBBB)',
        medicalTermEn: "Complete RBBB (rsR' in V1)",
        badgeLabel: 'Patologi A',
        badgeLabelEn: 'Pathology',
        visualClue: "QRS lebar (>= 120 ms) dengan bentuk telinga kelinci (rsR') di V1 dan S lebar tumpul di V6.",
        visualClueEn: "Wide QRS (>= 120 ms) with rabbit-ear morphology (rsR') in V1 and slurred S in V6.",
        clinicalSignificance: 'Keterlambatan aktivasi ventrikel kanan; bisa idiopatik atau tanda regangan paru/PE.',
        clinicalSignificanceEn: 'Delayed right ventricular activation; can be idiopathic or indicate pulmonary strain/PE.',
        diagnosticCriteria: "QRS >= 120 ms, gelombang R kedua (R') lebih tinggi dari r awal di V1.",
        diagnosticCriteriaEn: "QRS >= 120 ms, secondary R wave (R') taller than initial r in V1.",
        waveformSvgPath: 'M 10,50 L 35,50 L 40,54 L 46,34 L 52,58 L 58,14 L 66,50 L 80,50 C 88,50 96,62 108,62 C 118,62 124,50 134,50 L 195,50',
        isoelectricY: 50,
        calloutMarker: {
          cx: 58,
          cy: 14,
          label: "Telinga Kelinci (R')",
          labelEn: "Rabbit Ears (R')",
          type: 'CIRCLE_SPOTLIGHT',
          radius: 12,
        },
      },
      {
        id: 'bbb_lbbb',
        category: 'CONDUCTION_BBB',
        triageType: 'PATHOLOGY',
        title: 'Left Bundle Branch Block (LBBB)',
        titleEn: 'Left Bundle Branch Block (LBBB)',
        medicalTermEn: 'Complete LBBB (Notched R in V5-V6)',
        badgeLabel: 'Patologi B',
        badgeLabelEn: 'Pathology',
        visualClue: 'QRS lebar (>= 120 ms) dengan gelombang R terpancung bertakik (M-shape) di lateral dan QS dalam di V1.',
        visualClueEn: 'Wide QRS (>= 120 ms) with broad notched R wave in lateral leads and deep QS in V1.',
        clinicalSignificance: 'Keterlambatan aktivasi ventrikel kiri; mengaburkan evaluasi STEMI dan menandakan penyakit jantung struktural.',
        clinicalSignificanceEn: 'Delayed left ventricular activation; obscures STEMI and indicates structural heart disease.',
        diagnosticCriteria: 'QRS >= 120 ms, tidak ada gelombang q di lateral, gelombang R lebar bertakik di V5-V6.',
        diagnosticCriteriaEn: 'QRS >= 120 ms, absence of Q waves in lateral leads, broad notched R in V5-V6.',
        waveformSvgPath: 'M 10,50 L 35,50 L 40,50 L 46,20 L 52,28 L 58,16 L 68,62 L 74,50 C 84,50 94,62 106,62 C 116,62 122,50 132,50 L 195,50',
        isoelectricY: 50,
        calloutMarker: {
          cx: 52,
          cy: 20,
          label: 'R Bertakik (M-Shape)',
          labelEn: 'Notched R (M-Shape)',
          type: 'CIRCLE_SPOTLIGHT',
          radius: 12,
        },
      },
    ],
  },

  // 6. Hypertrophy & Chamber Enlargement
  {
    id: 'HYPERTROPHY_VENTRICULAR',
    groupTitle: 'Hipertrofi & Pembesaran Ruang Jantung',
    groupTitleEn: 'Ventricular Hypertrophy & Chamber Enlargement',
    groupSubtitle: 'Kriteria Voltase Sokolow-Lyon & Pola Regangan Repolarisasi (Strain Pattern)',
    groupSubtitleEn: 'Sokolow-Lyon Voltage Criteria & Repolarization Strain Pattern',
    clinicalEntityKey: 'HYPERTROPHY',
    exemplars: [
      {
        id: 'hyp_normal',
        category: 'HYPERTROPHY_VENTRICULAR',
        triageType: 'NORMAL',
        title: 'Voltase & Dinding Ventrikel Normal',
        titleEn: 'Normal Ventricular Voltages',
        medicalTermEn: 'Normal Precordial Voltages',
        badgeLabel: 'Normal',
        badgeLabelEn: 'Normal',
        visualClue: 'Kedalaman S di V1 ditambah tinggi R di V5 kurang dari 35 mm (3.5 mV).',
        visualClueEn: 'S depth in V1 plus R height in V5 is less than 35 mm (3.5 mV).',
        clinicalSignificance: 'Massa otot ventrikel dalam batas fisiologis normal.',
        clinicalSignificanceEn: 'Ventricular myocardial mass within normal physiological limits.',
        diagnosticCriteria: 'Sokolow-Lyon < 35 mm, Cornell kriteria negatif.',
        diagnosticCriteriaEn: 'Sokolow-Lyon < 35 mm, negative Cornell criteria.',
        waveformSvgPath: 'M 10,50 L 45,50 L 49,54 L 54,26 L 59,58 L 63,50 L 80,50 C 90,50 96,36 106,36 C 116,36 122,50 132,50 L 195,50',
        isoelectricY: 50,
        calloutMarker: {
          cx: 54,
          cy: 26,
          label: 'Voltase Normal (< 35 mm)',
          labelEn: 'Normal Voltage (< 35 mm)',
          type: 'CIRCLE_SPOTLIGHT',
          radius: 8,
        },
      },
      {
        id: 'hyp_lvh_strain',
        category: 'HYPERTROPHY_VENTRICULAR',
        triageType: 'PATHOLOGY',
        title: 'Hipertrofi Ventrikel Kiri (LVH dengan Strain)',
        titleEn: 'Left Ventricular Hypertrophy (LVH with Strain)',
        medicalTermEn: 'LVH with Repolarization Strain Pattern',
        badgeLabel: 'Patologi A',
        badgeLabelEn: 'Pathology',
        visualClue: 'Gelombang R menjulang sangat tinggi di V5 (Sokolow >= 35 mm) disertai depresi ST asimetris dan T inversi.',
        visualClueEn: 'Towering R waves in V5 (Sokolow >= 35 mm) with asymmetric ST depression and T inversion.',
        clinicalSignificance: 'Beban tekanan kronis (hipertensi menahun, stenosis aorta); risiko tinggi gagal jantung.',
        clinicalSignificanceEn: 'Chronic pressure overload (hypertension, aortic stenosis); elevated risk of heart failure.',
        diagnosticCriteria: 'S_V1 + R_V5 >= 35 mm atau R di aVL >= 11 mm disertai Strain Pattern di lateral.',
        diagnosticCriteriaEn: 'S_V1 + R_V5 >= 35 mm or R in aVL >= 11 mm with lateral strain pattern.',
        waveformSvgPath: 'M 10,50 L 35,50 L 39,54 L 48,6 L 56,66 L 62,62 L 80,62 C 92,62 100,74 112,74 C 122,74 130,50 142,50 L 195,50',
        isoelectricY: 50,
        calloutMarker: {
          cx: 48,
          cy: 6,
          label: 'R Menjulang Tinggi (LVH)',
          labelEn: 'Towering R (LVH)',
          type: 'CIRCLE_SPOTLIGHT',
          radius: 12,
        },
      },
    ],
  },

  // 7. Electrolytes & Metabolic
  {
    id: 'ELECTROLYTES',
    groupTitle: 'Gangguan Elektrolit & Efek Metabolik',
    groupTitleEn: 'Electrolyte Disorders & Metabolic Effects',
    groupSubtitle: 'Refleksi Disfungsi Kanal Ion Membran Seluler pada EKG Permukaan',
    groupSubtitleEn: 'Cellular Membrane Ion Channel Dysfunction Reflected on Surface ECG',
    clinicalEntityKey: 'ELECTROLYTES',
    exemplars: [
      {
        id: 'electrolyte_normal',
        category: 'ELECTROLYTES',
        triageType: 'NORMAL',
        title: 'Repolarisasi & Elektrolit Normal',
        titleEn: 'Normal T-Wave Repolarization & Electrolytes',
        medicalTermEn: 'Normal T-Wave Repolarization',
        badgeLabel: 'Normal',
        badgeLabelEn: 'Normal',
        visualClue: 'Gelombang T asimetris halus (naik perlahan, turun lebih cepat) dengan tinggi < 5 mm di limb leads.',
        visualClueEn: 'Smooth asymmetric T wave (slow rise, faster descent) with amplitude < 5 mm in limb leads.',
        clinicalSignificance: 'Keseimbangan ion kalium, kalsium, dan magnesium serum normal.',
        clinicalSignificanceEn: 'Normal serum potassium, calcium, and magnesium balance.',
        diagnosticCriteria: 'Tinggi T < 5 mm (ekstremitas) atau < 10 mm (prekordial), QTc 380-440 ms.',
        diagnosticCriteriaEn: 'T height < 5 mm in limb leads or < 10 mm in precordial leads; QTc 380-440 ms.',
        waveformSvgPath: 'M 10,50 L 45,50 L 49,54 L 54,20 L 59,58 L 63,50 L 80,50 C 92,50 102,34 112,34 C 120,34 126,50 134,50 L 195,50',
        isoelectricY: 50,
        calloutMarker: {
          cx: 112,
          cy: 34,
          label: 'T Asimetris Halus',
          labelEn: 'Smooth Asymmetric T',
          type: 'CIRCLE_SPOTLIGHT',
          radius: 8,
        },
      },
      {
        id: 'electrolyte_hyperkalemia',
        category: 'ELECTROLYTES',
        triageType: 'PATHOLOGY',
        title: 'Hiperkalemia Berat (K+ > 6.5 mEq/L)',
        titleEn: 'Severe Hyperkalemia (K+ > 6.5 mEq/L)',
        medicalTermEn: 'Tall Peaked Tented T Waves',
        badgeLabel: 'Patologi A (Kritis)',
        badgeLabelEn: 'Critical Pathology',
        visualClue: 'Gelombang T sangat tinggi, lancip simetris berdasar sempit seperti tenda (Tented T Wave).',
        visualClueEn: 'Tall, narrow, symmetrically peaked tented T waves with narrow base.',
        clinicalSignificance: 'Risiko asistol atau fibrilasi ventrikel; berikan Kalsium Glukonat intravena segera!',
        clinicalSignificanceEn: 'Imminent risk of asystole or ventricular fibrillation; give IV calcium gluconate immediately.',
        diagnosticCriteria: 'Gelombang T simetris tinggi runcing, dasar sempit (< 120 ms), hilangnya gelombang P.',
        diagnosticCriteriaEn: 'Symmetric tall peaked T waves, narrow base (< 120 ms), loss of P waves.',
        waveformSvgPath: 'M 10,50 L 45,50 L 49,54 L 54,20 L 59,58 L 63,50 L 78,50 L 88,50 L 98,8 L 108,50 L 120,50 L 195,50',
        isoelectricY: 50,
        calloutMarker: {
          cx: 98,
          cy: 8,
          label: 'T Lancip Tenda (Tented)',
          labelEn: 'Peaked Tented T',
          type: 'CIRCLE_SPOTLIGHT',
          radius: 12,
        },
      },
    ],
  },
];

/**
 * Returns the matching exemplar group for a clinical entity key.
 */
export function getExemplarGroupByEntity(entityKey: string): VisualExemplarGroup | undefined {
  return THALER_VISUAL_EXEMPLAR_GROUPS.find(
    (g) => g.clinicalEntityKey === entityKey || g.id === entityKey
  );
}
