/**
 * Comprehensive InSitu Caliper Annotation Map for All 15 Thaler Clinical Cases
 * Grounded in Dr. Malcolm S. Thaler's 'The Only EKG Book You'll Ever Need' (9th/10th Ed.)
 * Strictly zero em-dashes (Unicode U+2014 banned).
 */

import { InSituCaliperAnnotation } from './thalerTypes';

export interface CaseCaliperSet {
  caseId: string;
  caseCode: string;
  title: string;
  step1_calibration: InSituCaliperAnnotation;
  step2_heart_rate: InSituCaliperAnnotation;
  step3_intervals: InSituCaliperAnnotation;
  step4_axis: InSituCaliperAnnotation;
  step8_or_9_core_pathology: InSituCaliperAnnotation;
}

export const THALER_IN_SITU_CALIPER_MAP: Record<string, CaseCaliperSet> = {
  "case_normal_sinus": {
    "caseId": "case_normal_sinus",
    "caseCode": "THALER-01-NSR",
    "title": "Normal Resting Sinus Rhythm",
    "step1_calibration": {
      "type": "CALIBRATION_PULSE",
      "targetLead": "CALIBRATION_PULSE",
      "leadRow": 0,
      "leadCol": 0,
      "label": "Pulsa Kalibrasi: 10 mm (1.0 mV) x 5 mm (0.20 s)",
      "labelEn": "Calibration Pulse: 10 mm (1.0 mV) x 5 mm (0.20 s)",
      "calculationFormula": "10 mm = 1.0 mV | 25 mm/s (1 mm = 0.04 s)",
      "calculationFormulaEn": "10 mm = 1.0 mV | 25 mm/s (1 mm = 0.04 s)",
      "detailExplanation": "Standar kalibrasi normal: defleksi vertikal tepat 10 kotak kecil (10 mm = 1.0 mV) dan durasi horizontal 5 kotak kecil (0.20 s). Menandakan pembacaan voltase dan interval 1:1 tanpa faktor koreksi.",
      "detailExplanationEn": "Standard normal calibration: vertical deflection exactly 10 small boxes (10 mm = 1.0 mV) and horizontal width 5 small boxes (0.20 s). Confirms 1:1 voltage and interval scaling without correction factor.",
      "voltageMv": 1.0,
      "durationSec": 0.2,
      "smallBoxesCount": 10,
      "largeBoxesCount": 2
    },
    "step2_heart_rate": {
      "type": "RATE_CALIPER",
      "targetLead": "RHYTHM_II",
      "leadRow": 3,
      "leadCol": 0,
      "label": "Laju Jantung Normal: 72 bpm",
      "labelEn": "Normal Heart Rate: 72 bpm",
      "calculationFormula": "300 / 4.16 kotak besar = 72 bpm (1500 / 20.8 kotak kecil)",
      "calculationFormulaEn": "300 / 4.16 large boxes = 72 bpm (1500 / 20.8 small boxes)",
      "detailExplanation": "Jarak antar puncak R pada strip ritme Sadapan II konstan 4.16 kotak besar (~21 kotak kecil). Menggunakan rumus 300 / N menghasilkan laju sinus normal 72 bpm.",
      "detailExplanationEn": "R-R peak interval on Lead II rhythm strip remains constant at 4.16 large boxes (~21 small boxes). Using the 300 / N formula yields a normal resting sinus rate of 72 bpm.",
      "smallBoxesCount": 20.8,
      "largeBoxesCount": 4.16
    },
    "step3_intervals": {
      "type": "INTERVAL_CALIPER",
      "targetLead": "II",
      "leadRow": 1,
      "leadCol": 0,
      "label": "Interval Konduksi Normal: PR 160 ms, QRS 80 ms, QTc 405 ms",
      "labelEn": "Normal Conduction Intervals: PR 160 ms, QRS 80 ms, QTc 405 ms",
      "calculationFormula": "PR = 4 kotak kecil (0.16 s) | QRS = 2 kotak kecil (0.08 s) | QTc Bazett = 405 ms",
      "calculationFormulaEn": "PR = 4 small boxes (0.16 s) | QRS = 2 small boxes (0.08 s) | Bazett QTc = 405 ms",
      "detailExplanation": "Interval PR 160 ms berada dalam rentang normal 120 - 200 ms. Kompleks QRS sempit fisiologis 80 ms (< 120 ms). Repolarisasi ventrikel QTc normal.",
      "detailExplanationEn": "PR interval of 160 ms falls well within the normal 120 - 200 ms range. QRS complex is physiologically narrow at 80 ms (< 120 ms). Ventricular repolarization QTc is normal.",
      "smallBoxesCount": 4,
      "durationSec": 0.16
    },
    "step4_axis": {
      "type": "AXIS_VECTOR",
      "targetLead": "I",
      "leadRow": 0,
      "leadCol": 0,
      "label": "Aksis Frontal Normal (+58\u00b0): Lead I (+) & aVF (+)",
      "labelEn": "Normal Frontal Axis: +60 degrees",
      "calculationFormula": "Lead I (+9.0 mm) & aVF (+9.5 mm) -> Kuadran Bawah-Kiri 0\u00b0 s/d +90\u00b0 (~+58\u00b0)",
      "calculationFormulaEn": "Lead I (+1.0 mV) > 0 and Lead aVF (+0.8 mV) > 0 -> Quadrant 0 to +90 degrees",
      "detailExplanation": "Defleksi QRS dominan positif di kedua sadapan ortogonal Lead I (0\u00b0) dan aVF (+90\u00b0), memastikan vektor listrik jantung berada dalam batas normal.",
      "detailExplanationEn": "Equally positive net deflections in both Lead I and Lead aVF establish an electrical vector pointing downwards and to the patient's left (+60 degrees), indicative of normal ventricular depolarization.",
      "voltageMv": 0.9
    },
    "step8_or_9_core_pathology": {
      "type": "VOLTAGE_CALIPER",
      "targetLead": "V5",
      "leadRow": 1,
      "leadCol": 3,
      "label": "Segmen ST Isoelektrik & Kriteria Hipertrofi Negatif (Sokolow-Lyon 24 mm)",
      "labelEn": "Normal Baseline: Isoelectric ST Segment and Concordant T Wave",
      "calculationFormula": "S(V1) [10 mm] + R(V5) [14 mm] = 24 mm (< 35 mm) | ST elevasi = 0.0 mm",
      "calculationFormulaEn": "ST deviation = 0.0 mV (0 mm relative to TP baseline) | Normal T polarity",
      "detailExplanation": "Segmen ST berada tepat di garis isoelektrik (0 mm deviasi). Penjumlahan voltase prekordial jauh di bawah kriteria Sokolow-Lyon 35 mm.",
      "detailExplanationEn": "The ST segment in Lead II is strictly isoelectric with 0.00 mm deviation. T wave displays normal physiological asymmetry with gradual upslope and rapid downslope, confirming absent acute ischemia.",
      "voltageMv": 1.4,
      "smallBoxesCount": 24
    }
  },
  "case_inferior_stemi": {
    "caseId": "case_inferior_stemi",
    "caseCode": "THALER-02-INF-STEMI",
    "title": "Acute Inferior STEMI (RCA Occlusion) with Reciprocal Depression",
    "step1_calibration": {
      "type": "CALIBRATION_PULSE",
      "targetLead": "CALIBRATION_PULSE",
      "leadRow": 0,
      "leadCol": 0,
      "label": "Pulsa Kalibrasi: 10 mm (1.0 mV) x 5 mm (0.20 s)",
      "labelEn": "Calibration Pulse: 10 mm (1.0 mV) x 5 mm (0.20 s)",
      "calculationFormula": "10 mm = 1.0 mV | 25 mm/s",
      "calculationFormulaEn": "10 mm = 1.0 mV | 25 mm/s (1 mm = 0.04 s)",
      "detailExplanation": "Kalibrasi standar normal 10 mm/mV terverifikasi. Memastikan elevasi ST yang diukur mencerminkan voltase patologis absolut.",
      "detailExplanationEn": "Standard calibration pulse verified at 10 mm height and 5 mm width, confirming true 1:1 millivolt scaling for ST elevation measurement.",
      "voltageMv": 1.0,
      "durationSec": 0.2,
      "smallBoxesCount": 10,
      "largeBoxesCount": 2
    },
    "step2_heart_rate": {
      "type": "RATE_CALIPER",
      "targetLead": "RHYTHM_II",
      "leadRow": 3,
      "leadCol": 0,
      "label": "Sinus Bradikardia: 52 bpm",
      "labelEn": "Sinus Tachycardia: 105 bpm",
      "calculationFormula": "300 / 5.77 kotak besar = 52 bpm (1500 / 28.8 kotak kecil)",
      "calculationFormulaEn": "300 / 2.85 large boxes = 105 bpm (1500 / 14.3 small boxes)",
      "detailExplanation": "Bradikardia akibat iskemia nodus SA/AV yang diperdarahi oleh cabang Right Coronary Artery (RCA) yang mengalami oklusi akut.",
      "detailExplanationEn": "Sympathetic activation secondary to acute myocardial ischemia and chest pain increases sinus rate to 105 bpm (R-R distance ~14.3 small boxes).",
      "smallBoxesCount": 28.8,
      "largeBoxesCount": 5.77
    },
    "step3_intervals": {
      "type": "INTERVAL_CALIPER",
      "targetLead": "II",
      "leadRow": 1,
      "leadCol": 0,
      "label": "Interval PR Mendekati Batas Atas: 180 ms (4.5 Kotak Kecil)",
      "labelEn": "Conduction Intervals: PR 150 ms, QRS 85 ms, QTc 440 ms",
      "calculationFormula": "PR = 4.5 kotak (180 ms) | QRS = 85 ms | QTc = 440 ms",
      "calculationFormulaEn": "PR = 3.75 small boxes (0.15 s) | QRS = 2.1 small boxes (0.085 s) | QTc = 440 ms",
      "detailExplanation": "Interval PR 180 ms mencerminkan keterlambatan konduksi nodus AV subklinis akibat penurunan perfusi mikrovaskular nodus AV.",
      "detailExplanationEn": "Intact AV nodal conduction without acute AV block; narrow physiological QRS complex indicates preserved intraventricular conduction.",
      "smallBoxesCount": 4.5,
      "durationSec": 0.18
    },
    "step4_axis": {
      "type": "AXIS_VECTOR",
      "targetLead": "aVF",
      "leadRow": 2,
      "leadCol": 1,
      "label": "Aksis Frontal Vertikal (+80\u00b0): Lead I (+) Kecil & aVF (+) Sangat Kuat",
      "labelEn": "Normal to Rightward Trend Axis: +75 degrees",
      "calculationFormula": "Lead I (+2.0 mm) & aVF (+11.0 mm) -> Aksis dominan inferior (+80\u00b0)",
      "calculationFormulaEn": "Lead I net positive (+0.4 mV), Lead aVF strongly positive (+1.4 mV) -> +75 degrees",
      "detailExplanation": "Vektor depolarisasi mengarah ke inferior karena voltase positif dominan di aVF dibandingkan Lead I.",
      "detailExplanationEn": "Electrical vector points directly inferior towards the diaphragm and inferior left ventricular wall, aligning with territorial injury.",
      "voltageMv": 1.1
    },
    "step8_or_9_core_pathology": {
      "type": "ST_ELEVATION",
      "targetLead": "III",
      "leadRow": 2,
      "leadCol": 0,
      "label": "Elevasi Segmen ST Akut Inferior (+4.0 mm di III, +3.5 mm di aVF, +2.5 mm di II)",
      "labelEn": "Diagnostic ST Elevation: Inferior Leads (+3.5 mm in Lead III)",
      "calculationFormula": "ST elevasi > 1.0 mm pada >= 2 sadapan anatomis inferior (II, III, aVF) = STEMI Inferior",
      "calculationFormulaEn": "ST Elevation Lead III = +3.5 mm (+0.35 mV) at J-point + 60 ms | Reciprocal ST Depression in aVL (-2.0 mm)",
      "detailExplanation": "Elevasi ST konveks (cembung) masif di dinding inferior akibat oklusi total RCA, disertai depresi ST resiprokal spesifik di Lead I dan aVL.",
      "detailExplanationEn": "Convex 'tombstone' ST elevation >= 1 mm across contiguous inferior leads (II, III, aVF) paired with reciprocal ST depression in Lead aVL confirms acute thrombotic occlusion of the Right Coronary Artery (RCA).",
      "voltageMv": 0.4,
      "smallBoxesCount": 4.0
    }
  },
  "case_anterior_stemi": {
    "caseId": "case_anterior_stemi",
    "caseCode": "THALER-03-ANT-STEMI",
    "title": "Acute Extensive Anterior STEMI (Proximal LAD Occlusion)",
    "step1_calibration": {
      "type": "CALIBRATION_PULSE",
      "targetLead": "CALIBRATION_PULSE",
      "leadRow": 0,
      "leadCol": 0,
      "label": "Pulsa Kalibrasi: 10 mm (1.0 mV) x 5 mm (0.20 s)",
      "labelEn": "Calibration Pulse: 10 mm (1.0 mV) x 5 mm (0.20 s)",
      "calculationFormula": "10 mm = 1.0 mV | 25 mm/s",
      "calculationFormulaEn": "10 mm = 1.0 mV | 25 mm/s (1 mm = 0.04 s)",
      "detailExplanation": "Standar kalibrasi valid 10 mm/mV mengonfirmasi keaslian elevasi ST ekstrem dinding anterior.",
      "detailExplanationEn": "Standard calibration pulse confirmed at 10 mm, validating the extreme amplitude of anterior precordial ST segment displacement.",
      "voltageMv": 1.0,
      "durationSec": 0.2,
      "smallBoxesCount": 10,
      "largeBoxesCount": 2
    },
    "step2_heart_rate": {
      "type": "RATE_CALIPER",
      "targetLead": "RHYTHM_II",
      "leadRow": 3,
      "leadCol": 0,
      "label": "Sinus Takikardia: 104 bpm",
      "labelEn": "Sinus Rhythm with Borderline Rate: 98 bpm",
      "calculationFormula": "300 / 2.88 kotak besar = 104 bpm (1500 / 14.4 kotak kecil)",
      "calculationFormulaEn": "300 / 3.06 large boxes = 98 bpm (1500 / 15.3 small boxes)",
      "detailExplanation": "Takikardia sinus kompensatori akibat aktivasi adrenergik masif dan ancaman kegagalan pompa ventrikel kiri.",
      "detailExplanationEn": "Resting sinus rate at 98 bpm driven by intense adrenergic surge due to acute anterior wall injury.",
      "smallBoxesCount": 14.4,
      "largeBoxesCount": 2.88
    },
    "step3_intervals": {
      "type": "INTERVAL_CALIPER",
      "targetLead": "II",
      "leadRow": 1,
      "leadCol": 0,
      "label": "Interval Konduksi: PR 150 ms, QRS 90 ms, QTc 465 ms (Memanjang)",
      "labelEn": "Conduction Intervals: PR 165 ms, QRS 90 ms, QTc 465 ms (Prolonged)",
      "calculationFormula": "PR = 3.75 kotak (150 ms) | QRS = 90 ms | QTc = 465 ms (> 450 ms)",
      "calculationFormulaEn": "PR = 4.1 small boxes (0.165 s) | QRS = 2.25 small boxes (0.09 s) | QTc = 465 ms",
      "detailExplanation": "Interval PR normal namun repolarisasi QTc memanjang akibat disfungsi repolarisasi miokard iskemik luas.",
      "detailExplanationEn": "Delayed repolarization from extensive anterior ischemia prolongs QTc to 465 ms, increasing vulnerability to ventricular arrhythmias.",
      "smallBoxesCount": 3.75,
      "durationSec": 0.15
    },
    "step4_axis": {
      "type": "AXIS_VECTOR",
      "targetLead": "I",
      "leadRow": 0,
      "leadCol": 0,
      "label": "Aksis Frontal Normal (+45\u00b0): Lead I (+) & aVF (+)",
      "labelEn": "Normal Axis: +45 degrees",
      "calculationFormula": "Lead I (+8.0 mm) & aVF (+8.0 mm) -> Aksis simetris +45\u00b0",
      "calculationFormulaEn": "Lead I (+1.1 mV) > 0 and Lead aVF (+1.1 mV) > 0 -> Quadrant 0 to +90 degrees",
      "detailExplanation": "Aksis frontal tetap normal karena infark berpusat pada bidang horizontal prekordial (sadapan anterior V1-V5).",
      "detailExplanationEn": "Depolarization vector remains within normal quadrant; dominant pathology resides in horizontal precordial plane (V1 - V4).",
      "voltageMv": 0.8
    },
    "step8_or_9_core_pathology": {
      "type": "ST_ELEVATION",
      "targetLead": "V2",
      "leadRow": 1,
      "leadCol": 2,
      "label": "Elevasi Segmen ST Tombstone Masif (+6.0 mm di V2, +5.5 mm di V3, +4.5 mm di V4)",
      "labelEn": "Extensive Precordial ST Elevation: +5.0 mm in Lead V2",
      "calculationFormula": "ST elevasi V2-V3 >= 2.0 mm = Kriteria STEMI Anterior Ekstensif (Oklusi LAD Proksimal)",
      "calculationFormulaEn": "ST Elevation Lead V2 = +5.0 mm (+0.50 mV) at J-point | Loss of anterior R wave progression",
      "detailExplanation": "Oklusi total Left Anterior Descending (LAD) proksimal menghasilkan cedera transmural masif dengan morfologi batu nisan (tombstone) yang menyatu langsung dengan puncak gelombang T.",
      "detailExplanationEn": "Massive convex ST elevation >= 2 mm across precordial leads V1 - V4 signifies proximal Left Anterior Descending (LAD) coronary artery occlusion (widowmaker lesion), demanding emergent reperfusion.",
      "voltageMv": 0.6,
      "smallBoxesCount": 6.0
    }
  },
  "case_lvh_strain": {
    "caseId": "case_lvh_strain",
    "caseCode": "THALER-04-LVH-STRAIN",
    "title": "Left Ventricular Hypertrophy with Repolarization Strain Pattern",
    "step1_calibration": {
      "type": "CALIBRATION_PULSE",
      "targetLead": "CALIBRATION_PULSE",
      "leadRow": 0,
      "leadCol": 0,
      "label": "Pulsa Kalibrasi: 10 mm (1.0 mV) x 5 mm (0.20 s)",
      "labelEn": "Calibration Pulse: 10 mm (1.0 mV) x 5 mm (0.20 s)",
      "calculationFormula": "10 mm = 1.0 mV | 25 mm/s",
      "calculationFormulaEn": "10 mm = 1.0 mV | 25 mm/s (1 mm = 0.04 s)",
      "detailExplanation": "Kalibrasi standar penuh 10 mm/mV. Menjamin voltase ekstrem pada kriteria Sokolow-Lyon adalah nilai fisik riil.",
      "detailExplanationEn": "Standard 10 mm calibration confirmed. Essential to verify standard voltage before applying Sokolow-Lyon criteria.",
      "voltageMv": 1.0,
      "durationSec": 0.2,
      "smallBoxesCount": 10,
      "largeBoxesCount": 2
    },
    "step2_heart_rate": {
      "type": "RATE_CALIPER",
      "targetLead": "RHYTHM_II",
      "leadRow": 3,
      "leadCol": 0,
      "label": "Laju Jantung Normal: 75 bpm",
      "labelEn": "Sinus Rhythm: 68 bpm",
      "calculationFormula": "300 / 4.0 kotak besar = 75 bpm (1500 / 20.0 kotak kecil)",
      "calculationFormulaEn": "300 / 4.41 large boxes = 68 bpm (1500 / 22.0 small boxes)",
      "detailExplanation": "Irama sinus reguler dengan jarak R-R tepat 4 kotak besar, menghasilkan laju 75 bpm.",
      "detailExplanationEn": "Normal regular resting sinus rhythm at 68 bpm in a patient with chronic hypertensive heart disease.",
      "smallBoxesCount": 20.0,
      "largeBoxesCount": 4.0
    },
    "step3_intervals": {
      "type": "INTERVAL_CALIPER",
      "targetLead": "II",
      "leadRow": 1,
      "leadCol": 0,
      "label": "Interval Konduksi: PR 165 ms, QRS 95 ms, QTc 448 ms",
      "labelEn": "Conduction Intervals: PR 180 ms, QRS 105 ms (Borderline Widening), QTc 435 ms",
      "calculationFormula": "PR = 4.1 kotak (165 ms) | QRS = 95 ms (< 120 ms) | QTc = 448 ms",
      "calculationFormulaEn": "PR = 4.5 small boxes (0.18 s) | QRS = 2.6 small boxes (0.105 s) | QTc = 435 ms",
      "detailExplanation": "Penebalan dinding ventrikel kiri memperpanjang waktu defleksi intrinsikoid sehingga QRS sedikit melebar (95 ms) namun tetap di bawah 120 ms.",
      "detailExplanationEn": "QRS duration reaches 105 ms due to thickened myocardial wall requiring longer depolarization time, without complete bundle branch block.",
      "smallBoxesCount": 4.1,
      "durationSec": 0.165
    },
    "step4_axis": {
      "type": "AXIS_VECTOR",
      "targetLead": "aVF",
      "leadRow": 2,
      "leadCol": 1,
      "label": "Deviasi Aksis Kiri Patologis (LAD = -35\u00b0): Lead I (+), aVF (-), II (-)",
      "labelEn": "Left Axis Deviation (LAD): -25 degrees",
      "calculationFormula": "Lead I (+14 mm), aVF (-9 mm), II (-3 mm) -> Deviasi Aksis Kiri Sejati (-35\u00b0)",
      "calculationFormulaEn": "Lead I positive (+1.4 mV), Lead aVF negative (-0.7 mV), Lead II negative (-0.2 mV)",
      "detailExplanation": "Massa miokard ventrikel kiri yang membesar mendistorsi vektor listrik frontal ke arah superior-kiri, menghasilkan defleksi negatif di aVF dan II.",
      "detailExplanationEn": "Massive left ventricular hypertrophy rotates the net electrical vector superiorly and leftward, establishing true left axis deviation.",
      "voltageMv": -0.9
    },
    "step8_or_9_core_pathology": {
      "type": "VOLTAGE_CALIPER",
      "targetLead": "V5",
      "leadRow": 1,
      "leadCol": 3,
      "label": "Kriteria Sokolow-Lyon Masif: S(V1) [24 mm] + R(V5) [27 mm] = 51 mm",
      "labelEn": "Sokolow-Lyon Voltage Criterion: S in V1 (22 mm) + R in V5 (26 mm) = 48 mm",
      "calculationFormula": "S di V1 (24 mm) + R di V5 (27 mm) = 51 mm (Ambang Batas Patologis >= 35 mm)",
      "calculationFormulaEn": "S_V1 (2.2 mV) + R_V5 (2.6 mV) = 4.8 mV (48 mm) >= 35 mm (Diagnostic LVH)",
      "detailExplanation": "Voltase gabungan 51 mm jauh melampaui batas diagnostik Sokolow-Lyon 35 mm. Disertai pola strain ventrikel kiri (depresi ST asimetris dan inversi gelombang T di I, aVL, V5, V6).",
      "detailExplanationEn": "Sokolow-Lyon voltage sum of 48 mm comfortably surpasses the 35 mm threshold. Combined with asymmetrical downsloping ST depression and inverted T waves (Strain Pattern) in I, aVL, V5, V6.",
      "voltageMv": 5.1,
      "smallBoxesCount": 51.0
    }
  },
  "case_atrial_fibrillation": {
    "caseId": "case_atrial_fibrillation",
    "caseCode": "THALER-05-AFIB-RVR",
    "title": "Atrial Fibrillation with Rapid Ventricular Response (RVR)",
    "step1_calibration": {
      "type": "CALIBRATION_PULSE",
      "targetLead": "CALIBRATION_PULSE",
      "leadRow": 0,
      "leadCol": 0,
      "label": "Pulsa Kalibrasi: 10 mm (1.0 mV) x 5 mm (0.20 s)",
      "labelEn": "Calibration Pulse: 10 mm (1.0 mV) x 5 mm (0.20 s)",
      "calculationFormula": "10 mm = 1.0 mV | 25 mm/s",
      "calculationFormulaEn": "10 mm = 1.0 mV | 25 mm/s (1 mm = 0.04 s)",
      "detailExplanation": "Standar kalibrasi valid 10 mm/mV memastikan keaslian gelombang fibrilasi halus di sadapan dada.",
      "detailExplanationEn": "Standard calibration confirmed. Critical for observing fine fibrillatory baseline fluctuations.",
      "voltageMv": 1.0,
      "durationSec": 0.2,
      "smallBoxesCount": 10,
      "largeBoxesCount": 2
    },
    "step2_heart_rate": {
      "type": "RATE_CALIPER",
      "targetLead": "RHYTHM_II",
      "leadRow": 3,
      "leadCol": 0,
      "label": "Respon Ventrikel Cepat (RVR): ~130 bpm (Metode Strip 6 Detik)",
      "labelEn": "Irregularly Irregular Rate (Rapid Ventricular Response): 128 bpm",
      "calculationFormula": "13 kompleks QRS dalam 30 kotak besar (6.0 detik) x 10 = 130 bpm",
      "calculationFormulaEn": "6-Second Method: 13 QRS complexes in 30 large boxes x 10 = 130 bpm (Mean ~128 bpm)",
      "detailExplanation": "Karena irama irregularly irregular tanpa jarak R-R konstan, rumus 300/N tidak berlaku. Menghitung jumlah kompleks dalam 30 kotak besar (6 detik) dikali 10 menghasilkan 130 bpm.",
      "detailExplanationEn": "R-R intervals are completely irregular without recurring pattern. Large-box rule is invalid; 6-second method confirms tachycardia with rapid ventricular response.",
      "smallBoxesCount": 150.0,
      "largeBoxesCount": 30.0
    },
    "step3_intervals": {
      "type": "INTERVAL_CALIPER",
      "targetLead": "II",
      "leadRow": 1,
      "leadCol": 0,
      "label": "Gelombang P Absen (PR Tidak Terukur), QRS Sempit 80 ms",
      "labelEn": "Conduction: Absent P Wave (No PR Interval), QRS 85 ms, Variable QT",
      "calculationFormula": "PR = Absen (0 ms) | QRS = 2 kotak kecil (80 ms) | QTc = 420 ms",
      "calculationFormulaEn": "PR = N/A (Fibrillatory f-waves replace organized P waves) | Narrow QRS = 85 ms",
      "detailExplanation": "Tidak ada depolarisasi atrium tersinkronisasi sehingga interval PR tidak dapat diukur. QRS sempit membuktikan konduksi melalui cabang berkas normal.",
      "detailExplanationEn": "Total absence of discrete P waves. Baseline consists of continuous chaotic f-waves (350 - 600 cycles/min). AV node filters erratic impulses into narrow QRS complexes.",
      "durationSec": 0.08,
      "smallBoxesCount": 2
    },
    "step4_axis": {
      "type": "AXIS_VECTOR",
      "targetLead": "I",
      "leadRow": 0,
      "leadCol": 0,
      "label": "Aksis Frontal Normal (+50\u00b0): Lead I (+) & aVF (+)",
      "labelEn": "Normal Frontal Axis: +40 degrees",
      "calculationFormula": "Lead I (+6.0 mm) & aVF (+7.0 mm) -> Aksis normal +50\u00b0",
      "calculationFormulaEn": "Lead I (+0.8 mV) > 0 and Lead aVF (+0.6 mV) > 0 -> Quadrant 0 to +90 degrees",
      "detailExplanation": "Depolarisasi ventrikel tetap mengikuti aksis frontal normal meskipun irama pacu di atrium mengalami kekacauan listrik total.",
      "detailExplanationEn": "Ventricular activation maintains normal frontal axis despite chaotic atrial pacemaker activity.",
      "voltageMv": 0.6
    },
    "step8_or_9_core_pathology": {
      "type": "INTERVAL_CALIPER",
      "targetLead": "V1",
      "leadRow": 0,
      "leadCol": 2,
      "label": "Gelombang Fibrilasi Kasar (f-waves) & Irama Irregularly Irregular",
      "labelEn": "Chaotic Atrial Fibrillatory Baseline (f-waves) and Irregular R-R Intervals",
      "calculationFormula": "Frekuensi gelombang fibrilasi atrium > 350 - 600 siklus/menit tanpa gelombang P sejati",
      "calculationFormulaEn": "Fibrillatory frequency = 400 - 600/min | Delta R-R continuously fluctuates between 320 ms and 640 ms",
      "detailExplanation": "Sadapan V1 memperlihatkan garis dasar fibrilatorik ireguler dengan fluktuasi amplitudo halus hingga kasar (f-waves) dan hilangnya gelombang P teratur.",
      "detailExplanationEn": "Pathognomonic hallmarks of Atrial Fibrillation: absent P waves, undulating fibrillatory baseline, and irregularly irregular R-R intervals posing systemic thromboembolism risk.",
      "voltageMv": 0.12,
      "smallBoxesCount": 0
    }
  },
  "case_atrial_flutter": {
    "caseId": "case_atrial_flutter",
    "caseCode": "THALER-06-AFLUTTER",
    "title": "Atrial Flutter with 2:1 AV Block (Classic 150 bpm Tachycardia)",
    "step1_calibration": {
      "type": "CALIBRATION_PULSE",
      "targetLead": "CALIBRATION_PULSE",
      "leadRow": 0,
      "leadCol": 0,
      "label": "Pulsa Kalibrasi: 10 mm (1.0 mV) x 5 mm (0.20 s)",
      "labelEn": "Calibration Pulse: 10 mm (1.0 mV) x 5 mm (0.20 s)",
      "calculationFormula": "10 mm = 1.0 mV | 25 mm/s",
      "calculationFormulaEn": "10 mm = 1.0 mV | 25 mm/s (1 mm = 0.04 s)",
      "detailExplanation": "Kalibrasi standar normal 10 mm/mV terverifikasi.",
      "detailExplanationEn": "Standard calibration pulse verified at 10 mm height and 5 mm width.",
      "voltageMv": 1.0,
      "durationSec": 0.2,
      "smallBoxesCount": 10,
      "largeBoxesCount": 2
    },
    "step2_heart_rate": {
      "type": "RATE_CALIPER",
      "targetLead": "RHYTHM_II",
      "leadRow": 3,
      "leadCol": 0,
      "label": "Laju Ventrikel Klasik: 150 bpm (Aturan 2 Kotak Besar)",
      "labelEn": "Ventricular Rate Exactly 150 bpm (2:1 AV Conduction)",
      "calculationFormula": "300 / 2.0 kotak besar = tepat 150 bpm (Konduksi AV 2:1 dari laju flutter 300 bpm)",
      "calculationFormulaEn": "Atrial Rate: 300 bpm (1 large box) | Ventricular Rate: 300 / 2 = 150 bpm (2 large boxes)",
      "detailExplanation": "Sirkuit makro-reentry atrium kanan berputar dengan kecepatan 300 bpm. Nodus AV memblokir setiap impuls kedua (2:1 block), menghasilkan laju ventrikel tepat 150 bpm.",
      "detailExplanationEn": "Atrial flutter circuit cycles at 300 bpm. The physiological AV node refractory period passes every second flutter wave, producing a regular ventricular rate of exactly 150 bpm.",
      "smallBoxesCount": 10.0,
      "largeBoxesCount": 2.0
    },
    "step3_intervals": {
      "type": "INTERVAL_CALIPER",
      "targetLead": "II",
      "leadRow": 1,
      "leadCol": 0,
      "label": "Gelombang Flutter Gigi Gergaji (Saw-Tooth F-Waves): Siklus 300 bpm",
      "labelEn": "Conduction: Flutter Wave Interval 200 ms, Narrow QRS 80 ms",
      "calculationFormula": "Interval F-F = 5 kotak kecil (0.20 s) -> Laju Flutter Atrium = 300 bpm",
      "calculationFormulaEn": "F-F interval = 5 small boxes (0.20 s = 300/min) | QRS = 2 small boxes (0.08 s)",
      "detailExplanation": "Defleksi undulasi teratur berbentuk gigi gergaji tanpa garis isoelektrik datar di sadapan inferior (II, III, aVF) khas untuk flutter atrium klasik.",
      "detailExplanationEn": "Discrete sinus P waves are absent; continuous flutter waves cycle with 200 ms period. Ventricular depolarization proceeds normally through the His-Purkinje system.",
      "smallBoxesCount": 5.0,
      "largeBoxesCount": 1.0,
      "durationSec": 0.2,
      "voltageMv": -0.25
    },
    "step4_axis": {
      "type": "AXIS_VECTOR",
      "targetLead": "I",
      "leadRow": 0,
      "leadCol": 0,
      "label": "Aksis Frontal Normal (+60\u00b0): Lead I (+) & aVF (+)",
      "labelEn": "Normal Frontal Axis: +60 degrees",
      "calculationFormula": "Lead I (+6.5 mm) & aVF (+11.0 mm) -> Aksis +60\u00b0",
      "calculationFormulaEn": "Lead I (+0.9 mV) > 0 and Lead aVF (+0.8 mV) > 0 -> Quadrant 0 to +90 degrees",
      "detailExplanation": "Aksis depolarisasi ventrikel normal, konduksi intraventrikular utuh.",
      "detailExplanationEn": "Ventricular depolarization follows normal anatomical pathways (+60 degrees).",
      "voltageMv": 0.65
    },
    "step8_or_9_core_pathology": {
      "type": "RATE_CALIPER",
      "targetLead": "III",
      "leadRow": 2,
      "leadCol": 0,
      "label": "Blok AV Fisiologis 2:1: 2 Gelombang Flutter per 1 Kompleks QRS",
      "labelEn": "Sawtooth Flutter Waves (F-Waves) across Inferior Leads II, III, aVF",
      "calculationFormula": "Rasio F:QRS = 2:1 (Atrium 300 bpm : Ventrikel 150 bpm)",
      "calculationFormulaEn": "Sawtooth amplitude = 2.0 mm (0.2 mV) | F-F interval = 200 ms | 2:1 AV conduction ratio",
      "detailExplanation": "Sifat refrakter alami nodus AV melindungi ventrikel dari takiaritmia fatal dengan menyaring separuh gelombang flutter atrium.",
      "detailExplanationEn": "Continuous negative sawtooth baseline in leads II, III, aVF without isoelectric pause diagnostic of counterclockwise cavotricuspid isthmus (CTI)-dependent atrial flutter.",
      "largeBoxesCount": 2.0,
      "durationSec": 0.4
    }
  },
  "case_wpw_syndrome": {
    "caseId": "case_wpw_syndrome",
    "caseCode": "THALER-07-WPW",
    "title": "Wolff-Parkinson-White (WPW) Syndrome with Classic Delta Wave",
    "step1_calibration": {
      "type": "CALIBRATION_PULSE",
      "targetLead": "CALIBRATION_PULSE",
      "leadRow": 0,
      "leadCol": 0,
      "label": "Pulsa Kalibrasi: 10 mm (1.0 mV) x 5 mm (0.20 s)",
      "labelEn": "Calibration Pulse: 10 mm (1.0 mV) x 5 mm (0.20 s)",
      "calculationFormula": "10 mm = 1.0 mV | 25 mm/s",
      "calculationFormulaEn": "10 mm = 1.0 mV | 25 mm/s (1 mm = 0.04 s)",
      "detailExplanation": "Standar kalibrasi normal 10 mm/mV terverifikasi.",
      "detailExplanationEn": "Standard calibration pulse verified at 10 mm height and 5 mm width.",
      "voltageMv": 1.0,
      "durationSec": 0.2,
      "smallBoxesCount": 10,
      "largeBoxesCount": 2
    },
    "step2_heart_rate": {
      "type": "RATE_CALIPER",
      "targetLead": "RHYTHM_II",
      "leadRow": 3,
      "leadCol": 0,
      "label": "Laju Jantung Istirahat: 78 bpm",
      "labelEn": "Normal Resting Sinus Rate: 78 bpm",
      "calculationFormula": "300 / 3.85 kotak besar = 78 bpm (1500 / 19.2 kotak kecil)",
      "calculationFormulaEn": "300 / 3.85 large boxes = 78 bpm (1500 / 19.2 small boxes)",
      "detailExplanation": "Irama sinus reguler dengan kecepatan denyut normal 78 bpm saat istirahat.",
      "detailExplanationEn": "Resting sinus rhythm at 78 bpm; accessory pathway conducts passively during baseline state.",
      "smallBoxesCount": 19.2,
      "largeBoxesCount": 3.85
    },
    "step3_intervals": {
      "type": "INTERVAL_CALIPER",
      "targetLead": "II",
      "leadRow": 1,
      "leadCol": 0,
      "label": "Trias WPW: PR Memendek (90 ms) & QRS Melebar (130 ms)",
      "labelEn": "Short PR Interval (95 ms) with Widened QRS (135 ms)",
      "calculationFormula": "PR = 2.25 kotak (< 0.12 s) | QRS = 3.25 kotak (> 0.12 s)",
      "calculationFormulaEn": "PR = 2.4 small boxes (0.095 s < 0.12 s) | QRS = 3.4 small boxes (0.135 s > 0.12 s)",
      "detailExplanation": "Impuls melewati jalur bypass nodus AV (berkas Kent) sehingga depolarisasi ventrikel dimulai prematur (PR < 120 ms) dan meluas lambat dari miosit ke miosit (QRS > 120 ms).",
      "detailExplanationEn": "Accessory pathway (Bundle of Kent) bypasses normal AV nodal delay, pre-exciting ventricular myocardium prematurely and producing a short PR interval.",
      "smallBoxesCount": 2.25,
      "durationSec": 0.09
    },
    "step4_axis": {
      "type": "AXIS_VECTOR",
      "targetLead": "I",
      "leadRow": 0,
      "leadCol": 0,
      "label": "Aksis Frontal (+65\u00b0) & Waspada Pola Pseudo-Infark",
      "labelEn": "Left Axis Trend: +15 degrees",
      "calculationFormula": "Lead I (+) & aVF (+) -> Aksis frontal normal",
      "calculationFormulaEn": "Lead I (+1.3 mV) > 0 and Lead aVF (+0.3 mV) > 0 -> Quadrant 0 to +90 degrees",
      "detailExplanation": "Arah gelombang delta bergantung pada lokasi anatomis jalur aksesori, dapat membelokkan sumbu rata-rata QRS.",
      "detailExplanationEn": "Frontal axis influenced by anomalous ventricular pre-excitation wave vector.",
      "voltageMv": 0.7
    },
    "step8_or_9_core_pathology": {
      "type": "INTERVAL_CALIPER",
      "targetLead": "V4",
      "leadRow": 0,
      "leadCol": 3,
      "label": "Gelombang Delta (Delta Wave): Slurring Kenaikan Awal Kompleks QRS",
      "labelEn": "Diagnostic Delta Wave: Slurred Initial Upstroke of QRS Complex",
      "calculationFormula": "Landaian Pra-eksitasi (Delta Wave) = 50 ms + QRS Intrinsik = 80 ms -> QRS Total = 130 ms",
      "calculationFormulaEn": "PR < 120 ms (95 ms) + Delta wave duration 40 ms + QRS > 120 ms (135 ms) = Triad of WPW",
      "detailExplanation": "Slurring landai pada awal gelombang R merupakan tanda patognomonik depolarisasi pra-eksitasi ventrikel melalui jalur aksesori abnormal.",
      "detailExplanationEn": "Classic Wolff-Parkinson-White triad: short PR (< 120 ms), initial slurring of QRS upstroke (delta wave), and widened QRS complex. Represents anatomical pre-excitation through the Bundle of Kent.",
      "smallBoxesCount": 1.25,
      "durationSec": 0.05,
      "voltageMv": 0.35
    }
  },
  "case_complete_heart_block": {
    "caseId": "case_complete_heart_block",
    "caseCode": "THALER-08-3RD-AVB",
    "title": "Third-Degree (Complete) AV Block with Idioventricular Escape",
    "step1_calibration": {
      "type": "CALIBRATION_PULSE",
      "targetLead": "CALIBRATION_PULSE",
      "leadRow": 0,
      "leadCol": 0,
      "label": "Pulsa Kalibrasi: 10 mm (1.0 mV) x 5 mm (0.20 s)",
      "labelEn": "Calibration Pulse: 10 mm (1.0 mV) x 5 mm (0.20 s)",
      "calculationFormula": "10 mm = 1.0 mV | 25 mm/s",
      "calculationFormulaEn": "10 mm = 1.0 mV | 25 mm/s (1 mm = 0.04 s)",
      "detailExplanation": "Standar kalibrasi normal 10 mm/mV terverifikasi.",
      "detailExplanationEn": "Standard calibration verified at 10 mm height and 5 mm width.",
      "voltageMv": 1.0,
      "durationSec": 0.2,
      "smallBoxesCount": 10,
      "largeBoxesCount": 2
    },
    "step2_heart_rate": {
      "type": "RATE_CALIPER",
      "targetLead": "RHYTHM_II",
      "leadRow": 3,
      "leadCol": 0,
      "label": "Bradikardia Ekstrem Escape Ventrikel: 34 bpm",
      "labelEn": "Profound Ventricular Bradycardia: 36 bpm (Idioventricular Escape)",
      "calculationFormula": "300 / 8.8 kotak besar = 34 bpm (1500 / 44 kotak kecil)",
      "calculationFormulaEn": "Atrial Rate: 300 / 3.75 = 80 bpm | Ventricular Rate: 300 / 8.33 = 36 bpm",
      "detailExplanation": "Jarak antar kompleks QRS berjarak masif 8.8 kotak besar (1.76 detik), membuktikan laju pemacu escape ventrikel yang sangat lambat.",
      "detailExplanationEn": "Atria fire at normal sinus rate (80 bpm) while ventricles are driven independently by an intrinsic idioventricular escape pacemaker at 36 bpm.",
      "smallBoxesCount": 44.0,
      "largeBoxesCount": 8.8
    },
    "step3_intervals": {
      "type": "RATE_CALIPER",
      "targetLead": "RHYTHM_II",
      "leadRow": 3,
      "leadCol": 0,
      "label": "Disosiasi AV Total: P Sinus Reguler 75 bpm vs QRS Escape 34 bpm",
      "labelEn": "Complete AV Dissociation: Variable, Independent PR Intervals",
      "calculationFormula": "Interval P-P = 4.0 kotak besar (75 bpm) independen dari Interval R-R = 8.8 kotak besar (34 bpm)",
      "calculationFormulaEn": "P-P interval constant at 750 ms (80 bpm) | R-R interval constant at 1660 ms (36 bpm) | No PR correlation",
      "detailExplanation": "Gelombang P berbaris teratur tanpa pernah menghantarkan impuls ke ventrikel. Beberapa gelombang P bertumpukan di puncak gelombang T atau kompleks QRS.",
      "detailExplanationEn": "Total failure of AV nodal and infranodal conduction. P waves march across the rhythm strip with complete disregard for wide QRS complexes.",
      "largeBoxesCount": 4.0,
      "durationSec": 0.8
    },
    "step4_axis": {
      "type": "AXIS_VECTOR",
      "targetLead": "aVF",
      "leadRow": 2,
      "leadCol": 1,
      "label": "Aksis Escape Menyimang ke Kanan (RAD ~ +95\u00b0)",
      "labelEn": "Rightward Escape Axis: +95 degrees (RAD)",
      "calculationFormula": "Lead I (-1.0 mm) & aVF (+8.5 mm) -> Deviasi aksis kanan",
      "calculationFormulaEn": "Lead I negative (-0.1 mV), Lead aVF positive (+0.85 mV) -> Right Axis Deviation (+95 degrees)",
      "detailExplanation": "Aksis frontal ditentukan sepenuhnya oleh lokasi anatomis pemacu escape ektopik ventrikel.",
      "detailExplanationEn": "Electrical axis dictated by the anatomical origin of the ventricular escape focus in the peripheral Purkinje network.",
      "voltageMv": 0.85
    },
    "step8_or_9_core_pathology": {
      "type": "INTERVAL_CALIPER",
      "targetLead": "V1",
      "leadRow": 0,
      "leadCol": 2,
      "label": "Morfologi QRS Escape Idioventrikular Melebar: 150 ms",
      "labelEn": "Third-Degree (Complete) AV Block with Ventricular Escape Rhythm",
      "calculationFormula": "Durasi QRS = 3.75 kotak kecil (150 ms > 0.12 s) menandakan asal fokus infra-His",
      "calculationFormulaEn": "Complete AV Dissociation: Atrial rate 80 bpm > Ventricular rate 36 bpm | P-P regular, R-R regular",
      "detailExplanation": "QRS yang sangat lebar dan aneh membuktikan fokus penyelamat denyut jantung berasal dari serabut Purkinje ventrikel, bukan nodus AV junctional.",
      "detailExplanationEn": "Complete absence of conduction between atria and ventricles. Independent regular P waves and slow wide escape QRS complexes constitute a hemodynamic emergency requiring immediate pacing.",
      "smallBoxesCount": 3.75,
      "durationSec": 0.15,
      "voltageMv": -1.2
    }
  },
  "case_rbbb": {
    "caseId": "case_rbbb",
    "caseCode": "THALER-09-RBBB",
    "title": "Complete Right Bundle Branch Block (Classic Rabbit Ears in V1)",
    "step1_calibration": {
      "type": "CALIBRATION_PULSE",
      "targetLead": "CALIBRATION_PULSE",
      "leadRow": 0,
      "leadCol": 0,
      "label": "Pulsa Kalibrasi: 10 mm (1.0 mV) x 5 mm (0.20 s)",
      "labelEn": "Calibration Pulse: 10 mm (1.0 mV) x 5 mm (0.20 s)",
      "calculationFormula": "10 mm = 1.0 mV | 25 mm/s",
      "calculationFormulaEn": "10 mm = 1.0 mV | 25 mm/s (1 mm = 0.04 s)",
      "detailExplanation": "Standar kalibrasi normal 10 mm/mV terverifikasi.",
      "detailExplanationEn": "Standard calibration confirmed at 10 mm, ensuring accurate measurement of QRS duration.",
      "voltageMv": 1.0,
      "durationSec": 0.2,
      "smallBoxesCount": 10,
      "largeBoxesCount": 2
    },
    "step2_heart_rate": {
      "type": "RATE_CALIPER",
      "targetLead": "RHYTHM_II",
      "leadRow": 3,
      "leadCol": 0,
      "label": "Laju Jantung Normal: 70 bpm",
      "labelEn": "Normal Sinus Rhythm: 74 bpm",
      "calculationFormula": "300 / 4.3 kotak besar = 70 bpm (1500 / 21.4 kotak kecil)",
      "calculationFormulaEn": "300 / 4.05 large boxes = 74 bpm (1500 / 20.3 small boxes)",
      "detailExplanation": "Irama sinus reguler dengan konduksi nodus SA normal pada laju 70 bpm.",
      "detailExplanationEn": "Stable normal sinus rhythm at 74 bpm.",
      "smallBoxesCount": 21.4,
      "largeBoxesCount": 4.3
    },
    "step3_intervals": {
      "type": "INTERVAL_CALIPER",
      "targetLead": "II",
      "leadRow": 1,
      "leadCol": 0,
      "label": "Durasi QRS Melebar Patologis: 140 ms (3.5 Kotak Kecil)",
      "labelEn": "Conduction Delay: Normal PR 160 ms, Wide QRS 140 ms (>= 120 ms)",
      "calculationFormula": "QRS = 3.5 kotak kecil (140 ms >= 120 ms) = Blok Cabang Berkas Lengkap",
      "calculationFormulaEn": "PR = 4.0 small boxes (0.16 s) | QRS = 3.5 small boxes (0.14 s >= 0.12 s)",
      "detailExplanation": "Kriteria mutlak pertama bundle branch block: durasi QRS melebihi 120 ms akibat disinkroni aktivasi kedua ventrikel.",
      "detailExplanationEn": "Interrupted right bundle branch forces right ventricular depolarization to proceed slowly through transseptal cell-to-cell spread, prolonging QRS beyond 120 ms.",
      "smallBoxesCount": 3.5,
      "durationSec": 0.14
    },
    "step4_axis": {
      "type": "AXIS_VECTOR",
      "targetLead": "I",
      "leadRow": 0,
      "leadCol": 0,
      "label": "Aksis Frontal Normal (+60\u00b0): Lead I (+) & aVF (+)",
      "labelEn": "Normal Frontal Axis: +65 degrees",
      "calculationFormula": "Lead I (+8.0 mm) & aVF (+10.0 mm) -> Aksis +60\u00b0",
      "calculationFormulaEn": "Lead I positive (+0.6 mV), Lead aVF positive (+0.9 mV) -> Normal Axis Quadrant",
      "detailExplanation": "Aksis bidang frontal normal membuktikan tidak adanya hemiblok fasikuler penyerta.",
      "detailExplanationEn": "Initial left ventricular activation preserves normal frontal axis.",
      "voltageMv": 0.8
    },
    "step8_or_9_core_pathology": {
      "type": "INTERVAL_CALIPER",
      "targetLead": "V1",
      "leadRow": 0,
      "leadCol": 2,
      "label": "Telinga Kelinci V1 (Morfologi Trifasik rsR'): R' Tinggi 10 mm",
      "labelEn": "Classic rsR' ('Rabbit Ears') in Lead V1 and Slurred Wide S Wave in Lead I and V6",
      "calculationFormula": "r kecil (septal) -> S dangkal (LV) -> R' tinggi lebar (RV delayed activation)",
      "calculationFormulaEn": "QRS >= 120 ms (140 ms) + rsR' in V1 + Slurred S in I & V6 (> 40 ms) = Complete RBBB",
      "detailExplanation": "Depolarisasi ventrikel kanan yang lambat dan tertunda mengarah langsung ke elektroda V1, menciptakan gelombang R kedua (R') yang tinggi dan lebar khas telinga kelinci (rabbit ears). Disertai gelombang S lebar slurred di sadapan lateral I dan V6.",
      "detailExplanationEn": "Pathognomonic RBBB pattern: secondary R' wave in V1 reflects delayed anterior and rightward depolarization of the unshielded right ventricle.",
      "smallBoxesCount": 3.5,
      "durationSec": 0.14,
      "voltageMv": 1.0
    }
  },
  "case_lbbb": {
    "caseId": "case_lbbb",
    "caseCode": "THALER-10-LBBB",
    "title": "Complete Left Bundle Branch Block (Broad Notched R in I, V5, V6)",
    "step1_calibration": {
      "type": "CALIBRATION_PULSE",
      "targetLead": "CALIBRATION_PULSE",
      "leadRow": 0,
      "leadCol": 0,
      "label": "Pulsa Kalibrasi: 10 mm (1.0 mV) x 5 mm (0.20 s)",
      "labelEn": "Calibration Pulse: 10 mm (1.0 mV) x 5 mm (0.20 s)",
      "calculationFormula": "10 mm = 1.0 mV | 25 mm/s",
      "calculationFormulaEn": "10 mm = 1.0 mV | 25 mm/s (1 mm = 0.04 s)",
      "detailExplanation": "Standar kalibrasi normal 10 mm/mV terverifikasi.",
      "detailExplanationEn": "Standard calibration confirmed at 10 mm.",
      "voltageMv": 1.0,
      "durationSec": 0.2,
      "smallBoxesCount": 10,
      "largeBoxesCount": 2
    },
    "step2_heart_rate": {
      "type": "RATE_CALIPER",
      "targetLead": "RHYTHM_II",
      "leadRow": 3,
      "leadCol": 0,
      "label": "Laju Jantung Normal: 74 bpm",
      "labelEn": "Normal Sinus Rhythm: 70 bpm",
      "calculationFormula": "300 / 4.05 kotak besar = 74 bpm (1500 / 20.3 kotak kecil)",
      "calculationFormulaEn": "300 / 4.28 large boxes = 70 bpm (1500 / 21.4 small boxes)",
      "detailExplanation": "Irama sinus reguler dengan kecepatan denyut 74 bpm.",
      "detailExplanationEn": "Stable normal sinus rhythm at 70 bpm.",
      "smallBoxesCount": 20.3,
      "largeBoxesCount": 4.05
    },
    "step3_intervals": {
      "type": "INTERVAL_CALIPER",
      "targetLead": "II",
      "leadRow": 1,
      "leadCol": 0,
      "label": "Pelebaran QRS Masif: 150 ms (3.75 Kotak Kecil)",
      "labelEn": "Severe Conduction Delay: Wide QRS 155 ms (>= 120 ms)",
      "calculationFormula": "QRS = 3.75 kotak (150 ms > 120 ms) = Blok Cabang Berkas Lengkap",
      "calculationFormulaEn": "PR = 4.2 small boxes (0.17 s) | QRS = 3.9 small boxes (0.155 s >> 0.12 s)",
      "detailExplanation": "Konduksi melalui cabang berkas kiri terputus total; impuls menyebar lambat melalui serabut otot septal dari kanan ke kiri.",
      "detailExplanationEn": "Complete interruption of the main left bundle branch forces entire left ventricular depolarization to proceed via slow transseptal cell-to-cell propagation.",
      "smallBoxesCount": 3.75,
      "durationSec": 0.15
    },
    "step4_axis": {
      "type": "AXIS_VECTOR",
      "targetLead": "I",
      "leadRow": 0,
      "leadCol": 0,
      "label": "Aksis Frontal Cenderung Kiri (-15\u00b0): Lead I (+) & aVF (-)",
      "labelEn": "Leftward Axis Trend (-15 degrees): Lead I (+) & aVF (-)",
      "calculationFormula": "Lead I (+11.0 mm) & aVF (-3.0 mm) -> Aksis -15\u00b0",
      "calculationFormulaEn": "Lead I positive (+1.1 mV), Lead aVF slightly negative (-0.3 mV) -> Axis -15 degrees",
      "detailExplanation": "Aksis bidang frontal condong ke kiri karena arah aktivasi ventrikel kiri yang tertunda.",
      "detailExplanationEn": "Delayed leftward forces dominate and rotate axis toward left anterior hemithorax.",
      "voltageMv": 1.1
    },
    "step8_or_9_core_pathology": {
      "type": "INTERVAL_CALIPER",
      "targetLead": "V6",
      "leadRow": 2,
      "leadCol": 3,
      "label": "Gelombang R Monofasik Lebar Berlekuk (Broad Notched R) di Sadapan Lateral",
      "labelEn": "Broad, Notched Monomorphic R Wave in Lateral Leads (I, aVL, V6) and QS in V1",
      "calculationFormula": "QRS > 120 ms + Gelombang R berlekuk di I, aVL, V5, V6 + Hilangnya gelombang Q septal",
      "calculationFormulaEn": "QRS >= 120 ms (155 ms) + Broad monomorphic R without Q in I, aVL, V6 + QS in V1 + Secondary ST-T changes",
      "detailExplanation": "Depolarisasi septum bergerak abnormal dari kanan ke kiri (menghilangkan gelombang Q normal di sadapan lateral), diikuti aktivasi ventrikel kiri yang tertunda dan menghasilkan gelombang R bertakik lebar (notched R). Menunjukkan diskordansi repolarisasi sekunder.",
      "detailExplanationEn": "Definitive LBBB criteria: absent septal Q waves in lateral leads, broad monomorphic notched R wave, deep QS complex in V1, and discordant ST-T depressions. Masks standard STEMI criteria.",
      "smallBoxesCount": 3.75,
      "durationSec": 0.15,
      "voltageMv": 1.2
    }
  },
  "case_hyperkalemia": {
    "caseId": "case_hyperkalemia",
    "caseCode": "THALER-11-HYPERKALEMIA",
    "title": "Severe Hyperkalemia (Serum K+ 7.8 mEq/L) with Tented T Waves",
    "step1_calibration": {
      "type": "CALIBRATION_PULSE",
      "targetLead": "CALIBRATION_PULSE",
      "leadRow": 0,
      "leadCol": 0,
      "label": "Pulsa Kalibrasi: 10 mm (1.0 mV) x 5 mm (0.20 s)",
      "labelEn": "Calibration Pulse: 10 mm (1.0 mV) x 5 mm (0.20 s)",
      "calculationFormula": "10 mm = 1.0 mV | 25 mm/s",
      "calculationFormulaEn": "10 mm = 1.0 mV | 25 mm/s (1 mm = 0.04 s)",
      "detailExplanation": "Standar kalibrasi normal 10 mm/mV terverifikasi.",
      "detailExplanationEn": "Standard 10 mm calibration verified. Critical for assessing extreme amplitude of tented T waves.",
      "voltageMv": 1.0,
      "durationSec": 0.2,
      "smallBoxesCount": 10,
      "largeBoxesCount": 2
    },
    "step2_heart_rate": {
      "type": "RATE_CALIPER",
      "targetLead": "RHYTHM_II",
      "leadRow": 3,
      "leadCol": 0,
      "label": "Sinus Bradikardia Toksik: 58 bpm",
      "labelEn": "Sinus Bradycardia: 56 bpm",
      "calculationFormula": "300 / 5.17 kotak besar = 58 bpm (1500 / 25.8 kotak kecil)",
      "calculationFormulaEn": "300 / 5.35 large boxes = 56 bpm (1500 / 26.8 small boxes)",
      "detailExplanation": "Toksisitas ion kalium tinggi menekan otomatisitas nodus sinoatrial, menyebabkan bradikardia progresif.",
      "detailExplanationEn": "Elevated extracellular potassium partially depolarizes pacemaker resting potential, suppressing SA nodal firing rate.",
      "smallBoxesCount": 25.8,
      "largeBoxesCount": 5.17
    },
    "step3_intervals": {
      "type": "INTERVAL_CALIPER",
      "targetLead": "II",
      "leadRow": 1,
      "leadCol": 0,
      "label": "Perpanjangan PR (220 ms) & Pelebaran QRS Difus (130 ms)",
      "labelEn": "Conduction Delay: Flattened P Wave, PR 220 ms, Wide QRS 130 ms",
      "calculationFormula": "PR = 5.5 kotak kecil (> 200 ms) | QRS = 3.25 kotak kecil (> 120 ms)",
      "calculationFormulaEn": "PR = 5.5 small boxes (0.22 s > 0.20 s) | QRS = 3.25 small boxes (0.13 s > 0.12 s)",
      "detailExplanation": "Kadar kalium 7.8 mEq/L mendepolarisasi resting membrane potential parsial, memperlambat kecepatan konduksi intraseluler di atrium dan ventrikel.",
      "detailExplanationEn": "Severe hyperkalemia inactivates voltage-gated sodium channels, markedly slowing interatrial and intraventricular conduction.",
      "smallBoxesCount": 5.5,
      "durationSec": 0.22
    },
    "step4_axis": {
      "type": "AXIS_VECTOR",
      "targetLead": "I",
      "leadRow": 0,
      "leadCol": 0,
      "label": "Aksis Frontal Normal (+40\u00b0): Lead I (+) & aVF (+)",
      "labelEn": "Normal Frontal Axis: +50 degrees",
      "calculationFormula": "Lead I (+7.5 mm) & aVF (+6.5 mm) -> Aksis +40\u00b0",
      "calculationFormulaEn": "Lead I positive (+0.7 mV), Lead aVF positive (+0.8 mV)",
      "detailExplanation": "Aksis frontal masih dalam batas normal meskipun pelebaran QRS bersifat difus di seluruh sadapan.",
      "detailExplanationEn": "Frontal axis remains centered as hyperkalemic conduction delay affects both ventricles symmetrically.",
      "voltageMv": 0.75
    },
    "step8_or_9_core_pathology": {
      "type": "VOLTAGE_CALIPER",
      "targetLead": "V3",
      "leadRow": 2,
      "leadCol": 2,
      "label": "Gelombang T Runcing Menjulang (Tented T Waves): Tinggi 11.0 mm",
      "labelEn": "Tall, Symmetrical, Peaked ('Tented') T Waves across Precordial Leads (K+ > 7.0 mEq/L)",
      "calculationFormula": "Tinggi gelombang T > 10 mm dengan pangkalan sempit dan simetris runcing",
      "calculationFormulaEn": "T wave height in V3 = 11.5 mm (1.15 mV) with narrow base and sharp peak",
      "detailExplanation": "Peningkatan permeabilitas membran miosit terhadap ion K+ mempercepat repolarisasi fase 3 ventrikel, membentuk gelombang T yang menjulang tinggi, lancip, dan berpangkalan sempit khas menyerupai tenda kemah.",
      "detailExplanationEn": "Pathognomonic hallmark of severe hyperkalemia: symmetrical, tented T waves with narrow base and sharp apex, caused by accelerated phase 3 repolarization via enhanced outward potassium current.",
      "voltageMv": 1.1,
      "smallBoxesCount": 11.0
    }
  },
  "case_early_repol": {
    "caseId": "case_early_repol",
    "caseCode": "THALER-12-EARLY-REPOL",
    "title": "Benign Early Repolarization (Common Normal Athletic Variant)",
    "step1_calibration": {
      "type": "CALIBRATION_PULSE",
      "targetLead": "CALIBRATION_PULSE",
      "leadRow": 0,
      "leadCol": 0,
      "label": "Pulsa Kalibrasi: 10 mm (1.0 mV) x 5 mm (0.20 s)",
      "labelEn": "Calibration Pulse: 10 mm (1.0 mV) x 5 mm (0.20 s)",
      "calculationFormula": "10 mm = 1.0 mV | 25 mm/s",
      "calculationFormulaEn": "10 mm = 1.0 mV | 25 mm/s (1 mm = 0.04 s)",
      "detailExplanation": "Standar kalibrasi normal 10 mm/mV terverifikasi.",
      "detailExplanationEn": "Standard calibration pulse verified at 10 mm height and 5 mm width.",
      "voltageMv": 1.0,
      "durationSec": 0.2,
      "smallBoxesCount": 10,
      "largeBoxesCount": 2
    },
    "step2_heart_rate": {
      "type": "RATE_CALIPER",
      "targetLead": "RHYTHM_II",
      "leadRow": 3,
      "leadCol": 0,
      "label": "Laju Jantung Atlet Normal: 62 bpm",
      "labelEn": "Athletic Sinus Bradycardia: 54 bpm",
      "calculationFormula": "300 / 4.84 kotak besar = 62 bpm (1500 / 24.2 kotak kecil)",
      "calculationFormulaEn": "300 / 5.55 large boxes = 54 bpm (1500 / 27.8 small boxes)",
      "detailExplanation": "Irama sinus fisiologis dengan nada vagal tinggi pada individu muda sehat.",
      "detailExplanationEn": "High resting vagal tone in a healthy young athlete produces resting sinus bradycardia at 54 bpm.",
      "smallBoxesCount": 24.2,
      "largeBoxesCount": 4.84
    },
    "step3_intervals": {
      "type": "INTERVAL_CALIPER",
      "targetLead": "II",
      "leadRow": 1,
      "leadCol": 0,
      "label": "Interval Konduksi Normal: PR 155 ms, QRS 82 ms, QTc 395 ms",
      "labelEn": "Conduction Intervals: PR 150 ms, Narrow QRS 85 ms, QTc 390 ms",
      "calculationFormula": "PR = 3.9 kotak (155 ms) | QRS = 2.05 kotak (82 ms) | QTc = 395 ms",
      "calculationFormulaEn": "PR = 3.75 small boxes (0.15 s) | QRS = 2.1 small boxes (0.085 s) | QTc = 390 ms",
      "detailExplanation": "Seluruh interval konduksi berada dalam batas normal sempurna tanpa hambatan konduksi.",
      "detailExplanationEn": "Normal physiological intervals confirming absence of organic conduction system pathology.",
      "smallBoxesCount": 3.9,
      "durationSec": 0.155
    },
    "step4_axis": {
      "type": "AXIS_VECTOR",
      "targetLead": "I",
      "leadRow": 0,
      "leadCol": 0,
      "label": "Aksis Frontal Normal (+55\u00b0): Lead I (+) & aVF (+)",
      "labelEn": "Normal Frontal Axis: +60 degrees",
      "calculationFormula": "Lead I (+7.5 mm) & aVF (+8.5 mm) -> Aksis +55\u00b0",
      "calculationFormulaEn": "Lead I positive (+1.0 mV), Lead aVF positive (+0.9 mV) -> Quadrant 0 to +90 degrees",
      "detailExplanation": "Vektor frontal berada di kuadran normal fisiologis.",
      "detailExplanationEn": "Normal electrical axis pointing toward the apex.",
      "voltageMv": 0.75
    },
    "step8_or_9_core_pathology": {
      "type": "ST_ELEVATION",
      "targetLead": "V3",
      "leadRow": 2,
      "leadCol": 2,
      "label": "Takik J-Point Mata Pancing (Fishhook Notch) & Elevasi ST Cekung Jinak (+2.5 mm)",
      "labelEn": "Benign J-Point Elevation with Concave ST and Prominent Notching ('Fishhook')",
      "calculationFormula": "Elevasi ST Cekung + Takik J-Point (Fishhook) + Rasio ST/T < 0.25 di V6 = Varian Normal Jinak",
      "calculationFormulaEn": "J-point elevation = 1.5 mm | Concave ST slope | Symmetrical tall upright T waves | Absent reciprocal depression",
      "detailExplanation": "Perbedaan gradien voltase transmural epikardial pada atlet muda menghasilkan takik lekukan seperti mata pancing (fishhook) pada titik J dengan elevasi segmen ST yang cekung ke atas dan gelombang T asimetris.",
      "detailExplanationEn": "Benign Early Repolarization (BER) in healthy young adults: concave upward ST elevation with characteristic J-point slurring/notching in leads V2 - V5, absence of reciprocal ST depression, and normal cardiac biomarkers.",
      "voltageMv": 0.25,
      "smallBoxesCount": 2.5
    }
  },
  "case_lahb": {
    "caseId": "case_lahb",
    "caseCode": "THALER-13-LAHB",
    "title": "Left Anterior Hemiblock (Marked Left Axis Deviation -60\u00b0)",
    "step1_calibration": {
      "type": "CALIBRATION_PULSE",
      "targetLead": "CALIBRATION_PULSE",
      "leadRow": 0,
      "leadCol": 0,
      "label": "Pulsa Kalibrasi: 10 mm (1.0 mV) x 5 mm (0.20 s)",
      "labelEn": "Calibration Pulse: 10 mm (1.0 mV) x 5 mm (0.20 s)",
      "calculationFormula": "10 mm = 1.0 mV | 25 mm/s",
      "calculationFormulaEn": "10 mm = 1.0 mV | 25 mm/s (1 mm = 0.04 s)",
      "detailExplanation": "Standar kalibrasi normal 10 mm/mV terverifikasi.",
      "detailExplanationEn": "Standard calibration pulse verified at 10 mm height and 5 mm width.",
      "voltageMv": 1.0,
      "durationSec": 0.2,
      "smallBoxesCount": 10,
      "largeBoxesCount": 2
    },
    "step2_heart_rate": {
      "type": "RATE_CALIPER",
      "targetLead": "RHYTHM_II",
      "leadRow": 3,
      "leadCol": 0,
      "label": "Laju Jantung Normal: 72 bpm",
      "labelEn": "Normal Sinus Rhythm: 75 bpm",
      "calculationFormula": "300 / 4.16 kotak besar = 72 bpm (1500 / 20.8 kotak kecil)",
      "calculationFormulaEn": "300 / 4.0 large boxes = 75 bpm (1500 / 20.0 small boxes)",
      "detailExplanation": "Irama sinus reguler dengan laju denyut 72 bpm.",
      "detailExplanationEn": "Normal regular resting sinus rhythm at 75 bpm.",
      "smallBoxesCount": 20.8,
      "largeBoxesCount": 4.16
    },
    "step3_intervals": {
      "type": "INTERVAL_CALIPER",
      "targetLead": "II",
      "leadRow": 1,
      "leadCol": 0,
      "label": "Durasi QRS Tetap Sempit: 88 ms (< 120 ms)",
      "labelEn": "Conduction Intervals: PR 160 ms, Narrow QRS 95 ms (< 120 ms)",
      "calculationFormula": "QRS = 2.2 kotak (< 0.12 s) = Ciri Khas Hemiblok Murni",
      "calculationFormulaEn": "PR = 4.0 small boxes (0.16 s) | QRS = 2.4 small boxes (0.095 s < 0.12 s)",
      "detailExplanation": "Hemiblok (fasikuler blok) tidak memperlebar QRS secara signifikan melebihi 120 ms karena konduksi masih berlangsung cepat melalui fasikel posterior yang utuh.",
      "detailExplanationEn": "Fascicular hemiblock alone does not prolong QRS duration beyond 120 ms because posterior fascicle remains functional.",
      "smallBoxesCount": 2.2,
      "durationSec": 0.088
    },
    "step4_axis": {
      "type": "AXIS_VECTOR",
      "targetLead": "aVF",
      "leadRow": 2,
      "leadCol": 1,
      "label": "Deviasi Aksis Kiri Ekstrem (Marked LAD = -60\u00b0): qR di I/aVL & rS di II/III/aVF",
      "labelEn": "Marked Left Axis Deviation (LAD): -55 degrees",
      "calculationFormula": "Lead I (+8.0 mm) positif & Lead aVF (-10.0 mm), Lead II (-8.5 mm) negatif dalam -> Aksis = -60\u00b0",
      "calculationFormulaEn": "Lead I positive (+1.1 mV), Lead II negative (-0.8 mV), Lead aVF negative (-1.2 mV) -> Axis -55 degrees",
      "detailExplanation": "Blok pada fasikel anterior kiri mengalihkan gelombang depolarisasi melalui fasikel posterior terlebih dahulu, menyapu ventrikel dari inferior ke superior-kiri sehingga menghasilkan deviasi aksis kiri yang sangat tajam dengan pola rS inferior.",
      "detailExplanationEn": "Interrupted left anterior fascicle forces initial depolarization inferiorly (small r in II, III, aVF) followed by dominant delayed superior-leftward forces (tall R in I, aVL; deep S in II, III, aVF).",
      "voltageMv": -1.0,
      "smallBoxesCount": 10.0
    },
    "step8_or_9_core_pathology": {
      "type": "AXIS_VECTOR",
      "targetLead": "I",
      "leadRow": 0,
      "leadCol": 0,
      "label": "Kriteria Definitif LAHB: Morfologi qR di Sadapan Lateral Tinggi (I & aVL)",
      "labelEn": "Isolated Left Anterior Hemiblock (LAHB / LAFB): Axis <= -45 degrees with qR in I/aVL and rS in II/III/aVF",
      "calculationFormula": "LAD <= -45\u00b0 + qR di I & aVL + rS di II, III, aVF + QRS < 120 ms = LAHB Murni",
      "calculationFormulaEn": "Frontal Axis <= -45 degrees (-55 degrees) + qR pattern in aVL + rS pattern in II, III, aVF + QRS < 120 ms",
      "detailExplanation": "Kriteria definitif Left Anterior Hemiblock menurut Thaler: aksis kiri tajam (-60\u00b0) tanpa pemanjangan durasi QRS patologis dan tanpa adanya infark inferior lama yang meniru LAD.",
      "detailExplanationEn": "Diagnostic criteria for Left Anterior Hemiblock: marked left axis deviation (-45 to -90 degrees), qR pattern in high lateral leads (I, aVL), rS pattern in inferior leads (II, III, aVF), and normal QRS duration.",
      "voltageMv": 0.8,
      "smallBoxesCount": 8.0
    }
  },
  "case_acute_pericarditis": {
    "caseId": "case_acute_pericarditis",
    "caseCode": "THALER-14-PERICARDITIS",
    "title": "Acute Viral Pericarditis (Diffuse Concave ST Elevation with PR Depression)",
    "step1_calibration": {
      "type": "CALIBRATION_PULSE",
      "targetLead": "CALIBRATION_PULSE",
      "leadRow": 0,
      "leadCol": 0,
      "label": "Pulsa Kalibrasi: 10 mm (1.0 mV) x 5 mm (0.20 s)",
      "labelEn": "Calibration Pulse: 10 mm (1.0 mV) x 5 mm (0.20 s)",
      "calculationFormula": "10 mm = 1.0 mV | 25 mm/s",
      "calculationFormulaEn": "10 mm = 1.0 mV | 25 mm/s (1 mm = 0.04 s)",
      "detailExplanation": "Standar kalibrasi normal 10 mm/mV terverifikasi.",
      "detailExplanationEn": "Standard calibration pulse verified at 10 mm height and 5 mm width.",
      "voltageMv": 1.0,
      "durationSec": 0.2,
      "smallBoxesCount": 10,
      "largeBoxesCount": 2
    },
    "step2_heart_rate": {
      "type": "RATE_CALIPER",
      "targetLead": "RHYTHM_II",
      "leadRow": 3,
      "leadCol": 0,
      "label": "Sinus Takikardia Ringan: 88 bpm",
      "labelEn": "Sinus Tachycardia: 102 bpm",
      "calculationFormula": "300 / 3.41 kotak besar = 88 bpm (1500 / 17.0 kotak kecil)",
      "calculationFormulaEn": "300 / 2.94 large boxes = 102 bpm (1500 / 14.7 small boxes)",
      "detailExplanation": "Peningkatan laju denyut akibat respons inflamasi perikardium dan nyeri dada pleuritik.",
      "detailExplanationEn": "Sinus tachycardia driven by pleuritic chest pain and systemic inflammatory response.",
      "smallBoxesCount": 17.0,
      "largeBoxesCount": 3.41
    },
    "step3_intervals": {
      "type": "INTERVAL_CALIPER",
      "targetLead": "II",
      "leadRow": 1,
      "leadCol": 0,
      "label": "Tanda Spodick: Depresi Segmen PR (-1.2 mm di Lead II) & Elevasi PR di aVR",
      "labelEn": "Conduction: Normal PR 150 ms, Narrow QRS 85 ms, QTc 415 ms",
      "calculationFormula": "Depresi PR > 0.8 mm di sadapan inferolateral + Elevasi PR di aVR = Arus Cedera Epikardium Atrium",
      "calculationFormulaEn": "PR = 3.75 small boxes (0.15 s) | QRS = 2.1 small boxes (0.085 s) | QTc = 415 ms",
      "detailExplanation": "Peradangan perikardium subepikardial menyebabkan arus cedera pada atrium, mendepresi segmen PR di Sadapan II dan menaikkannya di aVR, tanda paling dini dan spesifik perikarditis akut.",
      "detailExplanationEn": "Normal ventricular conduction; pathology is confined to epicardial and pericardial inflammation.",
      "voltageMv": -0.12,
      "smallBoxesCount": 1.2
    },
    "step4_axis": {
      "type": "AXIS_VECTOR",
      "targetLead": "I",
      "leadRow": 0,
      "leadCol": 0,
      "label": "Aksis Frontal Normal (+55\u00b0): Lead I (+) & aVF (+)",
      "labelEn": "Normal Frontal Axis: +55 degrees",
      "calculationFormula": "Lead I (+7.0 mm) & aVF (+8.0 mm) -> Aksis normal +55\u00b0",
      "calculationFormulaEn": "Lead I positive (+0.9 mV), Lead aVF positive (+0.8 mV) -> Normal Axis Quadrant",
      "detailExplanation": "Aksis listrik frontal normal tanpa deviasi.",
      "detailExplanationEn": "Normal depolarization vector.",
      "voltageMv": 0.7
    },
    "step8_or_9_core_pathology": {
      "type": "ST_ELEVATION",
      "targetLead": "V4",
      "leadRow": 0,
      "leadCol": 3,
      "label": "Elevasi Segmen ST Cekung Difus (+2.5 mm di V4, +2.0 mm di II, III, aVF, V2-V6)",
      "labelEn": "Diffuse Concave ST Elevation with Pathognomonic PR Segment Depression across Multiple Territories",
      "calculationFormula": "ST elevasi cekung melintasi wilayah RCA, LAD, dan LCx sekaligus tanpa depresi resiprokal (kecuali aVR & V1)",
      "calculationFormulaEn": "Concave ST elevation across I, II, aVF, V2 - V6 + PR depression >= 0.8 mm in Lead II + Reciprocal PR elevation in aVR",
      "detailExplanation": "Karena peradangan membungkus seluruh lapisan perikardium jantung secara global, elevasi segmen ST bersifat cekung ke atas (seperti mangkuk) dan melintasi sadapan ekstremitas serta prekordial tanpa membatasi diri pada teritori satu arteri koroner.",
      "detailExplanationEn": "Stage 1 Acute Pericarditis: diffuse upwardly concave ST elevation sparing no specific coronary territory, paired with PR segment depression (subepicardial atrial injury) and reciprocal PR elevation in lead aVR.",
      "voltageMv": 0.25,
      "smallBoxesCount": 2.5
    }
  },
  "case_digoxin_effect": {
    "caseId": "case_digoxin_effect",
    "caseCode": "THALER-15-DIGOXIN",
    "title": "Therapeutic Digoxin Effect (Salvador Dali Mustache ST Depression)",
    "step1_calibration": {
      "type": "CALIBRATION_PULSE",
      "targetLead": "CALIBRATION_PULSE",
      "leadRow": 0,
      "leadCol": 0,
      "label": "Pulsa Kalibrasi: 10 mm (1.0 mV) x 5 mm (0.20 s)",
      "labelEn": "Calibration Pulse: 10 mm (1.0 mV) x 5 mm (0.20 s)",
      "calculationFormula": "10 mm = 1.0 mV | 25 mm/s",
      "calculationFormulaEn": "10 mm = 1.0 mV | 25 mm/s (1 mm = 0.04 s)",
      "detailExplanation": "Standar kalibrasi normal 10 mm/mV terverifikasi.",
      "detailExplanationEn": "Standard calibration pulse verified at 10 mm height and 5 mm width.",
      "voltageMv": 1.0,
      "durationSec": 0.2,
      "smallBoxesCount": 10,
      "largeBoxesCount": 2
    },
    "step2_heart_rate": {
      "type": "RATE_CALIPER",
      "targetLead": "RHYTHM_II",
      "leadRow": 3,
      "leadCol": 0,
      "label": "Laju Jantung Terkendali Baik: 68 bpm",
      "labelEn": "Controlled Sinus Bradycardia: 58 bpm",
      "calculationFormula": "300 / 4.41 kotak besar = 68 bpm (1500 / 22.0 kotak kecil)",
      "calculationFormulaEn": "300 / 5.17 large boxes = 58 bpm (1500 / 25.8 small boxes)",
      "detailExplanation": "Efek inotropik positif dan kronotropik negatif digoksin menstabilkan laju denyut jantung pada 68 bpm.",
      "detailExplanationEn": "Digitalis vagomimetic central action slows sinus node rate and prolongs AV conduction.",
      "smallBoxesCount": 22.0,
      "largeBoxesCount": 4.41
    },
    "step3_intervals": {
      "type": "INTERVAL_CALIPER",
      "targetLead": "II",
      "leadRow": 1,
      "leadCol": 0,
      "label": "Interval QTc Memendek Terapetik: 380 ms (PR 180 ms, QRS 82 ms)",
      "labelEn": "Conduction: Borderline PR 205 ms, Narrow QRS 85 ms, Short QTc 360 ms",
      "calculationFormula": "QTc = 380 ms (< 390 ms akibat pemendekan fase plateau potensial aksi ventrikel)",
      "calculationFormulaEn": "PR = 5.1 small boxes (0.205 s) | QRS = 2.1 small boxes (0.085 s) | QTc = 360 ms (Shortened)",
      "detailExplanation": "Digoksin mempercepat repolarisasi fase 2 ventrikel melalui inhibisi Na+/K+ ATPase, menghasilkan pemendekan interval QTc yang khas.",
      "detailExplanationEn": "Shortened QTc is a characteristic digitalis feature reflecting accelerated ventricular repolarization.",
      "smallBoxesCount": 4.5,
      "durationSec": 0.18
    },
    "step4_axis": {
      "type": "AXIS_VECTOR",
      "targetLead": "I",
      "leadRow": 0,
      "leadCol": 0,
      "label": "Aksis Frontal Normal (+50\u00b0): Lead I (+) & aVF (+)",
      "labelEn": "Normal Frontal Axis: +50 degrees",
      "calculationFormula": "Lead I (+8.0 mm) & aVF (+7.0 mm) -> Aksis +50\u00b0",
      "calculationFormulaEn": "Lead I positive (+0.8 mV), Lead aVF positive (+0.7 mV) -> Normal Axis Quadrant",
      "detailExplanation": "Aksis frontal berada dalam kuadran normal.",
      "detailExplanationEn": "Normal electrical axis.",
      "voltageMv": 0.8
    },
    "step8_or_9_core_pathology": {
      "type": "ST_ELEVATION",
      "targetLead": "V5",
      "leadRow": 1,
      "leadCol": 3,
      "label": "Depresi Segmen ST Berbentuk Sekop (Salvador Dali Mustache Scoop: -2.0 mm)",
      "labelEn": "Characteristic Scooped ('Salvador Dali Sag') ST Depression in Leads with Tall R Waves",
      "calculationFormula": "Depresi ST Melengkung Cekung ke Bawah (Scooped ST) di Sadapan dengan Gelombang R Dominan",
      "calculationFormulaEn": "Downsloping scooped ST depression = -1.5 mm | Flattened/inverted T wave | Short QTc interval",
      "detailExplanation": "Penghambatan pompa Na+/K+ ATPase oleh digoksin memperpendek durasi potensial aksi ventrikel dan menghasilkan depresi segmen ST cekung melengkung asimetris khas menyerupai kumis pelukis surealis Salvador Dali.",
      "detailExplanationEn": "Classic Digoxin Effect: scooped, concave-upward sagging ST segment resembling Salvador Dali's mustache, primarily in leads with tall R waves (V4 - V6, I, aVL). Indicates digitalis presence, not necessarily toxicity.",
      "voltageMv": -0.2,
      "smallBoxesCount": 2.0
    }
  },
  "case_monomorphic_vt": {
    "caseId": "case_monomorphic_vt",
    "caseCode": "THALER-16-MONO-VT",
    "title": "Monomorphic Ventricular Tachycardia (Wide Complex Tachycardia)",
    "step1_calibration": {
      "type": "CALIBRATION_PULSE",
      "targetLead": "CALIBRATION_PULSE",
      "leadRow": 0,
      "leadCol": 0,
      "label": "Pulsa Kalibrasi: 10 mm (1.0 mV) x 5 mm (0.20 s)",
      "labelEn": "Calibration Pulse: 10 mm (1.0 mV) x 5 mm (0.20 s)",
      "calculationFormula": "10 mm = 1.0 mV | Kecepatan 25 mm/s",
      "calculationFormulaEn": "10 mm = 1.0 mV | 25 mm/s (1 mm = 0.04 s)",
      "detailExplanation": "Standar kalibrasi normal terverifikasi 10 mm/mV.",
      "detailExplanationEn": "Standard calibration pulse verified at 10 mm height and 5 mm width.",
      "voltageMv": 1.0,
      "durationSec": 0.2,
      "smallBoxesCount": 10,
      "largeBoxesCount": 2
    },
    "step2_heart_rate": {
      "type": "RATE_CALIPER",
      "targetLead": "RHYTHM_II",
      "leadRow": 3,
      "leadCol": 0,
      "label": "Takikardia Ventrikel Cepat Mengancam Jiwa: 165 bpm",
      "labelEn": "Extreme Ventricular Tachycardia: 175 bpm",
      "calculationFormula": "300 / 1.81 kotak besar = 165 bpm (Irama Reguler Cepat)",
      "calculationFormulaEn": "300 / 1.71 large boxes = 175 bpm (1500 / 8.6 small boxes)",
      "detailExplanation": "Laju ventrikel 165 denyut per menit dengan kompleks QRS monomorfik yang seragam.",
      "detailExplanationEn": "Rapid regular wide-complex tachycardia originating from an ectopic ventricular myocardial focus.",
      "smallBoxesCount": 9.1,
      "largeBoxesCount": 1.81
    },
    "step3_intervals": {
      "type": "INTERVAL_CALIPER",
      "targetLead": "II",
      "leadRow": 1,
      "leadCol": 0,
      "label": "Kompleks QRS Melebar Bizarre: 165 ms (> 140 ms Patognomonik VT)",
      "labelEn": "Extreme QRS Widening: QRS 170 ms (>> 120 ms), AV Dissociation",
      "calculationFormula": "QRS = 4.1 kotak kecil (165 ms) | PR: Tidak Terukur (Disosiasi AV)",
      "calculationFormulaEn": "QRS = 4.25 small boxes (0.17 s >> 0.12 s) | AV dissociation present with independent P waves",
      "detailExplanation": "Durasi QRS jauh melampaui batas 120 ms. Impuls berasal langsung dari miokardium ventrikel di luar sistem konduksi His-Purkinje.",
      "detailExplanationEn": "Severe QRS widening >= 140 ms with uniform morphology confirms ectopic ventricular origin over SVT with aberrancy.",
      "smallBoxesCount": 4.1,
      "durationSec": 0.165
    },
    "step4_axis": {
      "type": "AXIS_VECTOR",
      "targetLead": "I",
      "leadRow": 0,
      "leadCol": 0,
      "label": "Aksis Ekstrim Northwest (-130\u00b0): Tidak Bertuan (No Mans Land)",
      "labelEn": "Extreme Right Axis Deviation ('Northwest Axis'): -135 degrees",
      "calculationFormula": "Lead I (-) dan aVF (-) -> Deviasi Aksis Ekstrim Khas VT",
      "calculationFormulaEn": "Lead I negative (-1.2 mV), Lead aVF negative (-1.0 mV) -> Extreme Quadrant (-90 to 180 degrees)",
      "detailExplanation": "Defleksi dominan negatif pada Sadapan I dan aVF mengonfirmasi depolarisasi ventrikel menyebar mundur dari apeks ke basis.",
      "detailExplanationEn": "Northwest axis (-90 to -180 degrees) strongly favors ventricular tachycardia, as supraventricular pathways rarely produce this trajectory.",
      "voltageMv": -1.4
    },
    "step8_or_9_core_pathology": {
      "type": "INTERVAL_CALIPER",
      "targetLead": "V1",
      "leadRow": 0,
      "leadCol": 2,
      "label": "Kriteria Brugada Positif: Takikardia Kompleks Lebar Ventrikel",
      "labelEn": "Wide Complex Tachycardia (Monomorphic VT): Brugada Criteria Concordance and Fusion/Capture Beats",
      "calculationFormula": "Ketiadaan kompleks RS di V1-V6 atau interval awal R ke puncak S > 100 ms",
      "calculationFormulaEn": "Ventricular rate 175 bpm + QRS 170 ms + Positive precordial concordance (V1 - V6 all upright) + AV dissociation",
      "detailExplanation": "Morfologi QRS bizarre monomorfik dengan gelombang T berlawanan arah (diskordan). Pasien memerlukan evaluasi stabilitas hemodinamik segera untuk kardioversi atau amiodaron.",
      "detailExplanationEn": "Monomorphic Ventricular Tachycardia meeting Brugada criteria: QRS > 140 ms, extreme axis, positive precordial concordance, and AV dissociation. Life-threatening emergency requiring prompt cardioversion.",
      "durationSec": 0.165,
      "smallBoxesCount": 4.1
    }
  },
  "case_posterior_stemi": {
    "caseId": "case_posterior_stemi",
    "caseCode": "THALER-17-POST-STEMI",
    "title": "Acute True Posterior STEMI (Mirror Image Reciprocal Pattern in V1-V3)",
    "step1_calibration": {
      "type": "CALIBRATION_PULSE",
      "targetLead": "CALIBRATION_PULSE",
      "leadRow": 0,
      "leadCol": 0,
      "label": "Pulsa Kalibrasi: 10 mm (1.0 mV) x 5 mm (0.20 s)",
      "labelEn": "Calibration Pulse: 10 mm (1.0 mV) x 5 mm (0.20 s)",
      "calculationFormula": "10 mm = 1.0 mV",
      "calculationFormulaEn": "10 mm = 1.0 mV | 25 mm/s (1 mm = 0.04 s)",
      "detailExplanation": "Kalibrasi standar normal.",
      "detailExplanationEn": "Standard calibration pulse verified at 10 mm height and 5 mm width.",
      "voltageMv": 1.0,
      "durationSec": 0.2,
      "smallBoxesCount": 10,
      "largeBoxesCount": 2
    },
    "step2_heart_rate": {
      "type": "RATE_CALIPER",
      "targetLead": "RHYTHM_II",
      "leadRow": 3,
      "leadCol": 0,
      "label": "Laju Jantung Normal: 78 bpm",
      "labelEn": "Sinus Tachycardia: 104 bpm",
      "calculationFormula": "300 / 3.84 kotak besar = 78 bpm",
      "calculationFormulaEn": "300 / 2.88 large boxes = 104 bpm (1500 / 14.4 small boxes)",
      "detailExplanation": "Irama reguler dengan laju denyut jantung dalam rentang normal.",
      "detailExplanationEn": "Sinus tachycardia driven by acute ischemic chest pain.",
      "smallBoxesCount": 19.2,
      "largeBoxesCount": 3.84
    },
    "step3_intervals": {
      "type": "INTERVAL_CALIPER",
      "targetLead": "II",
      "leadRow": 1,
      "leadCol": 0,
      "label": "Interval Konduksi: PR 160 ms, QRS 88 ms, QTc 418 ms",
      "labelEn": "Conduction: Normal PR 160 ms, Narrow QRS 85 ms, QTc 445 ms",
      "calculationFormula": "PR 4 kotak kecil | QRS 2.2 kotak kecil",
      "calculationFormulaEn": "PR = 4.0 small boxes (0.16 s) | QRS = 2.1 small boxes (0.085 s) | QTc = 445 ms",
      "detailExplanation": "Semua interval konduksi atrioventrikular dan intraventrikular dalam batas normal.",
      "detailExplanationEn": "Preserved AV and intraventricular conduction.",
      "smallBoxesCount": 4.0,
      "durationSec": 0.16
    },
    "step4_axis": {
      "type": "AXIS_VECTOR",
      "targetLead": "I",
      "leadRow": 0,
      "leadCol": 0,
      "label": "Aksis Frontal Normal (+45\u00b0): Lead I (+) & aVF (+)",
      "labelEn": "Normal Frontal Axis: +65 degrees",
      "calculationFormula": "Lead I dan aVF sama-sama positif tegak",
      "calculationFormulaEn": "Lead I positive (+0.7 mV), Lead aVF positive (+0.9 mV) -> Normal Axis Quadrant",
      "detailExplanation": "Aksis bidang frontal normal di kuadran inferolateral.",
      "detailExplanationEn": "Normal frontal depolarization axis.",
      "voltageMv": 0.8
    },
    "step8_or_9_core_pathology": {
      "type": "ST_ELEVATION",
      "targetLead": "V2",
      "leadRow": 1,
      "leadCol": 2,
      "label": "Cermin Infark Posterior di V2: R Tinggi (R/S > 1) & Depresi ST Horisontal (-2.2 mm)",
      "labelEn": "Mirror-Image STEMI: Horizontal ST Depression with Tall Upright R and T Waves in Leads V1 - V3",
      "calculationFormula": "Depresi ST Horisontal >= 0.5 mm di V1-V3 + R Lebar/Tinggi = Gambar Cermin Elevasi ST Posterior",
      "calculationFormulaEn": "ST depression in V2 = -3.0 mm (equivalent to +3.0 mm elevation in posterior V7 - V9) | R/S ratio in V2 > 1.0",
      "detailExplanation": "Dinding posterior jantung berada di seberang sadapan V1-V3. Gelombang Q patologis tampak sebagai R tinggi, elevasi ST tampak sebagai depresi ST horisontal, dan inversi T tampak sebagai T tegak simetris tinggi. Pasang sadapan posterior V7-V9 untuk konfirmasi.",
      "detailExplanationEn": "True Posterior STEMI: leads V1 - V3 view posterior electrical forces through a mirror. Prominent R wave (mirror of Q wave), horizontal ST depression (mirror of ST elevation), and tall upright T wave (mirror of T inversion) demand emergent catheterization.",
      "voltageMv": -0.22,
      "smallBoxesCount": 2.2
    }
  },
  "case_pulmonary_embolism": {
    "caseId": "case_pulmonary_embolism",
    "caseCode": "THALER-18-PULM-EMB",
    "title": "Acute Massive Pulmonary Embolism (McGinn-White S1Q3T3 Pattern & RV Strain)",
    "step1_calibration": {
      "type": "CALIBRATION_PULSE",
      "targetLead": "CALIBRATION_PULSE",
      "leadRow": 0,
      "leadCol": 0,
      "label": "Pulsa Kalibrasi: 10 mm (1.0 mV) x 5 mm (0.20 s)",
      "labelEn": "Calibration Pulse: 10 mm (1.0 mV) x 5 mm (0.20 s)",
      "calculationFormula": "10 mm = 1.0 mV",
      "calculationFormulaEn": "10 mm = 1.0 mV | 25 mm/s (1 mm = 0.04 s)",
      "detailExplanation": "Kalibrasi standar normal.",
      "detailExplanationEn": "Standard calibration pulse verified at 10 mm height and 5 mm width.",
      "voltageMv": 1.0,
      "durationSec": 0.2,
      "smallBoxesCount": 10,
      "largeBoxesCount": 2
    },
    "step2_heart_rate": {
      "type": "RATE_CALIPER",
      "targetLead": "RHYTHM_II",
      "leadRow": 3,
      "leadCol": 0,
      "label": "Sinus Takikardia Respons Emboli Paru: 115 bpm",
      "labelEn": "Sinus Tachycardia: 115 bpm (Most Common PE Finding)",
      "calculationFormula": "300 / 2.61 kotak besar = 115 bpm (Sinus Takikardia)",
      "calculationFormulaEn": "300 / 2.61 large boxes = 115 bpm (1500 / 13.0 small boxes)",
      "detailExplanation": "Peningkatan denyut kompensatorik terhadap penurunan curah jantung dan hipoksemia akut.",
      "detailExplanationEn": "Sinus tachycardia is the most frequent and sensitive ECG finding in acute pulmonary embolism, resulting from hypoxemia and elevated sympathetic tone.",
      "smallBoxesCount": 13.0,
      "largeBoxesCount": 2.61
    },
    "step3_intervals": {
      "type": "INTERVAL_CALIPER",
      "targetLead": "II",
      "leadRow": 1,
      "leadCol": 0,
      "label": "Interval Normal: PR 140 ms, QRS 86 ms, QTc 425 ms",
      "labelEn": "Conduction: Normal PR 150 ms, Borderline QRS 95 ms, QTc 440 ms",
      "calculationFormula": "PR 3.5 kotak kecil | QRS 2.1 kotak kecil",
      "calculationFormulaEn": "PR = 3.75 small boxes (0.15 s) | QRS = 2.4 small boxes (0.095 s) | QTc = 440 ms",
      "detailExplanation": "Konduksi normal dengan takikardia sinus.",
      "detailExplanationEn": "Incomplete right bundle conduction delay reflecting acute right ventricular pressure overload.",
      "smallBoxesCount": 3.5,
      "durationSec": 0.14
    },
    "step4_axis": {
      "type": "AXIS_VECTOR",
      "targetLead": "I",
      "leadRow": 0,
      "leadCol": 0,
      "label": "Deviasi Aksis Kanan Akut (+110\u00b0): Lead I (-) & aVF (+)",
      "labelEn": "Right Axis Deviation (RAD): +105 degrees",
      "calculationFormula": "Gelombang S dalam di Lead I dan R dominan di aVF/III",
      "calculationFormulaEn": "Lead I negative (-0.4 mV), Lead aVF strongly positive (+1.2 mV) -> Axis +105 degrees",
      "detailExplanation": "Beban tekanan ventrikel kanan mendadak akibat obstruksi arteri pulmonalis menggeser vektor aksis ke kanan.",
      "detailExplanationEn": "Acute right ventricular strain and dilation displace the mean electrical axis sharply rightward.",
      "voltageMv": -0.3
    },
    "step8_or_9_core_pathology": {
      "type": "INTERVAL_CALIPER",
      "targetLead": "III",
      "leadRow": 2,
      "leadCol": 0,
      "label": "Trias Klasik McGinn-White S1Q3T3 & Regangan Ventrikel Kanan",
      "labelEn": "McGinn-White S1Q3T3 Pattern with T-Wave Inversion in Right Precordial Leads (V1 - V3)",
      "calculationFormula": "S dalam di Lead I (0.75 mV) + Q di Lead III (0.35 mV) + T Inversi di Lead III & V1-V4",
      "calculationFormulaEn": "Deep S wave in Lead I + Pathological Q in Lead III + Inverted T in Lead III (S1Q3T3) + T inversion V1 - V3",
      "detailExplanation": "Pola klasik cor pulmonale akut akibat emboli paru masif yang menyebabkan distensi dan regangan akut ventrikel kanan.",
      "detailExplanationEn": "Classic McGinn-White S1Q3T3 sign of acute cor pulmonale: deep S in I, Q in III, and T inversion in III, combined with precordial T inversions (V1 - V3) indicating severe acute right ventricular strain.",
      "voltageMv": 0.35,
      "durationSec": 0.08
    }
  },
  "case_brugada_type1": {
    "caseId": "case_brugada_type1",
    "caseCode": "THALER-19-BRUGADA",
    "title": "Brugada Syndrome Type 1 (Coved-Type ST Elevation & Risk of Sudden Death)",
    "step1_calibration": {
      "type": "CALIBRATION_PULSE",
      "targetLead": "CALIBRATION_PULSE",
      "leadRow": 0,
      "leadCol": 0,
      "label": "Pulsa Kalibrasi: 10 mm (1.0 mV) x 5 mm (0.20 s)",
      "labelEn": "Calibration Pulse: 10 mm (1.0 mV) x 5 mm (0.20 s)",
      "calculationFormula": "10 mm = 1.0 mV",
      "calculationFormulaEn": "10 mm = 1.0 mV | 25 mm/s (1 mm = 0.04 s)",
      "detailExplanation": "Kalibrasi standar normal.",
      "detailExplanationEn": "Standard calibration pulse verified at 10 mm height and 5 mm width.",
      "voltageMv": 1.0,
      "durationSec": 0.2,
      "smallBoxesCount": 10,
      "largeBoxesCount": 2
    },
    "step2_heart_rate": {
      "type": "RATE_CALIPER",
      "targetLead": "RHYTHM_II",
      "leadRow": 3,
      "leadCol": 0,
      "label": "Laju Jantung Normal: 74 bpm",
      "labelEn": "Normal Sinus Rhythm: 65 bpm",
      "calculationFormula": "300 / 4.05 kotak besar = 74 bpm",
      "calculationFormulaEn": "300 / 4.62 large boxes = 65 bpm (1500 / 23.1 small boxes)",
      "detailExplanation": "Irama reguler dengan laju denyut jantung dalam rentang normal.",
      "detailExplanationEn": "Normal resting sinus rate at 65 bpm.",
      "smallBoxesCount": 20.3,
      "largeBoxesCount": 4.05
    },
    "step3_intervals": {
      "type": "INTERVAL_CALIPER",
      "targetLead": "II",
      "leadRow": 1,
      "leadCol": 0,
      "label": "Interval Konduksi: PR 168 ms, QRS 104 ms, QTc 410 ms",
      "labelEn": "Conduction: PR 170 ms, Mild Conduction Delay QRS 110 ms, QTc 420 ms",
      "calculationFormula": "PR 4.2 kotak kecil | QRS 2.6 kotak kecil (Pseudo-RBBB)",
      "calculationFormulaEn": "PR = 4.25 small boxes (0.17 s) | QRS = 2.75 small boxes (0.11 s) | QTc = 420 ms",
      "detailExplanation": "Konduksi AV normal dengan sedikit perlambatan terminal di sadapan dada kanan.",
      "detailExplanationEn": "Mild intraventricular conduction delay in the right ventricular outflow tract (RVOT).",
      "smallBoxesCount": 4.2,
      "durationSec": 0.168
    },
    "step4_axis": {
      "type": "AXIS_VECTOR",
      "targetLead": "I",
      "leadRow": 0,
      "leadCol": 0,
      "label": "Aksis Frontal Normal (+35\u00b0): Lead I (+) & aVF (+)",
      "labelEn": "Normal Frontal Axis: +60 degrees",
      "calculationFormula": "Lead I dan aVF positif tegak",
      "calculationFormulaEn": "Lead I positive (+0.9 mV), Lead aVF positive (+0.8 mV) -> Normal Axis Quadrant",
      "detailExplanation": "Aksis frontal dalam batas normal.",
      "detailExplanationEn": "Normal frontal depolarization axis.",
      "voltageMv": 0.7
    },
    "step8_or_9_core_pathology": {
      "type": "ST_ELEVATION",
      "targetLead": "V1",
      "leadRow": 0,
      "leadCol": 2,
      "label": "Elevasi Segmen ST Coved-Type (Sirip Hiu / Ski-Slope: +2.8 mm) di V1-V2",
      "labelEn": "Diagnostic Type 1 Brugada Pattern: Coved ST Elevation >= 2 mm followed by Inverted T in Leads V1 - V2",
      "calculationFormula": "Elevasi Titik J >= 2.0 mm melengkung cembung turun ke gelombang T negatif simetris",
      "calculationFormulaEn": "Coved ST elevation = +3.2 mm (>= 2 mm) with high take-off J-point + Negative T wave in V1, V2",
      "detailExplanation": "Kanalopati natrium jantung (mutasi gen SCN5A) pada traktus aliran keluar ventrikel kanan (RVOT). Risiko tinggi aritmia ventrikel polimorfik dan kematian jantung mendadak (sudden cardiac death). Indikasi konsultasi elektrofisiologi untuk pemasangan ICD.",
      "detailExplanationEn": "Type 1 Brugada pattern (coved-type): J-point elevation >= 2 mm with downsloping concave/coved ST segment terminating in symmetric inverted T wave in right precordial leads (V1 - V2). High risk for polymorphic VT/VF and sudden cardiac death.",
      "voltageMv": 0.28,
      "smallBoxesCount": 2.8
    }
  },
  "case_severe_hypokalemia": {
    "caseId": "case_severe_hypokalemia",
    "caseCode": "THALER-20-HYPOKALEMIA",
    "title": "Severe Hypokalemia (Giant U Waves, Flattened T Waves & Pseudo-Long QT)",
    "step1_calibration": {
      "type": "CALIBRATION_PULSE",
      "targetLead": "CALIBRATION_PULSE",
      "leadRow": 0,
      "leadCol": 0,
      "label": "Pulsa Kalibrasi: 10 mm (1.0 mV) x 5 mm (0.20 s)",
      "labelEn": "Calibration Pulse: 10 mm (1.0 mV) x 5 mm (0.20 s)",
      "calculationFormula": "10 mm = 1.0 mV",
      "calculationFormulaEn": "10 mm = 1.0 mV | 25 mm/s (1 mm = 0.04 s)",
      "detailExplanation": "Kalibrasi standar normal.",
      "detailExplanationEn": "Standard calibration pulse verified at 10 mm height and 5 mm width.",
      "voltageMv": 1.0,
      "durationSec": 0.2,
      "smallBoxesCount": 10,
      "largeBoxesCount": 2
    },
    "step2_heart_rate": {
      "type": "RATE_CALIPER",
      "targetLead": "RHYTHM_II",
      "leadRow": 3,
      "leadCol": 0,
      "label": "Laju Jantung Normal: 82 bpm",
      "labelEn": "Borderline Sinus Tachycardia: 96 bpm",
      "calculationFormula": "300 / 3.65 kotak besar = 82 bpm",
      "calculationFormulaEn": "300 / 3.12 large boxes = 96 bpm (1500 / 15.6 small boxes)",
      "detailExplanation": "Irama reguler dengan laju denyut jantung dalam rentang normal.",
      "detailExplanationEn": "Resting sinus rate elevated to 96 bpm in a patient experiencing severe electrolyte depletion.",
      "smallBoxesCount": 18.3,
      "largeBoxesCount": 3.65
    },
    "step3_intervals": {
      "type": "INTERVAL_CALIPER",
      "targetLead": "II",
      "leadRow": 1,
      "leadCol": 0,
      "label": "Interval QU Semu Panjang: 540 ms (PR 160 ms, QRS 84 ms)",
      "labelEn": "Conduction: Apparent QT Prolongation (QU Fusion Interval = 580 ms)",
      "calculationFormula": "QT Terukur Nyata adalah Interval QU karena Gelombang T Melebur ke Gelombang U",
      "calculationFormulaEn": "PR = 4.0 small boxes (0.16 s) | QRS = 2.0 small boxes (0.08 s) | Measured QU interval = 580 ms",
      "detailExplanation": "Kekurangan kalium menunda repolarisasi seluler sehingga memperpanjang interval QU dan meningkatkan kerentanan terhadap Torsades de Pointes.",
      "detailExplanationEn": "Severe hypokalemia delays ventricular repolarization and creates huge U waves that fuse with T waves, falsely mimicking extreme QT prolongation (true Q-U interval).",
      "smallBoxesCount": 13.5,
      "durationSec": 0.54
    },
    "step4_axis": {
      "type": "AXIS_VECTOR",
      "targetLead": "I",
      "leadRow": 0,
      "leadCol": 0,
      "label": "Aksis Frontal Normal (+55\u00b0): Lead I (+) & aVF (+)",
      "labelEn": "Normal Frontal Axis: +50 degrees",
      "calculationFormula": "Lead I dan aVF positif tegak",
      "calculationFormulaEn": "Lead I positive (+0.9 mV), Lead aVF positive (+0.8 mV) -> Normal Axis Quadrant",
      "detailExplanation": "Aksis frontal dalam batas normal.",
      "detailExplanationEn": "Normal frontal axis.",
      "voltageMv": 0.8
    },
    "step8_or_9_core_pathology": {
      "type": "INTERVAL_CALIPER",
      "targetLead": "V2",
      "leadRow": 1,
      "leadCol": 2,
      "label": "Gelombang U Menonjol Raksasa (+2.8 mm) & Perataan Gelombang T",
      "labelEn": "Severe Hypokalemia Triad: ST Depression, Flattened T Wave, and Giant Prominent U Wave (K+ < 2.5 mEq/L)",
      "calculationFormula": "Amplitudo Gelombang U > Amplitudo Gelombang T + Depresi Ringan Segmen ST",
      "calculationFormulaEn": "ST depression = -1.2 mm | T wave amplitude < 1 mm | U wave amplitude = 2.8 mm (> T wave height in V2 - V4)",
      "detailExplanation": "Kadar kalium serum yang sangat rendah (< 2.0 mEq/L) menghasilkan perataan gelombang T dan pemunculan gelombang U raksasa yang menonjol terutama di V2 dan V3. Merupakan kegawatdaruratan koreksi elektrolit intravena.",
      "detailExplanationEn": "Characteristic Severe Hypokalemia Triad: generalized ST depression, flattened T wave, and giant prominent U wave exceeding T wave amplitude in leads V2 - V4. Extreme risk of Torsades de Pointes and ventricular fibrillation.",
      "voltageMv": 0.28,
      "durationSec": 0.18
    }
  }
};
