/**
 * Thaler Diagnostic Flowchart Data & Clinical Decision Hierarchy
 * Grounded in Dr. Malcolm S. Thaler's clinical curriculum.
 * Strictly zero em-dashes (Unicode U+2014 banned).
 */

export interface FlowchartBranch {
  label: string;
  labelEn?: string;
  condition: string;
  conditionEn?: string;
  finding: string;
  findingEn?: string;
  diagnosticOutcome: string;
  diagnosticOutcomeEn?: string;
  status: 'NORMAL' | 'PATHOLOGIC' | 'WARNING';
  targetCaseId?: string;
  targetStepNumber?: number;
  tutorialCaseId?: string;
  suggestedStep?: number;
  formula?: string;
}

export interface FlowchartNode {
  id: string;
  stageId: number;
  stepBadge: string;
  stepBadgeEn?: string;
  questionTitle: string;
  questionTitleEn?: string;
  clinicalDirective: string;
  clinicalDirectiveEn?: string;
  keyLeads: string[];
  branches: FlowchartBranch[];
  formula?: string;
}

export interface FlowchartStage {
  stageId: number;
  stageName: string;
  stageNameEn?: string;
  subtitle: string;
  subtitleEn?: string;
  clinicalObjective: string;
  clinicalObjectiveEn?: string;
  themeColor: 'blue' | 'indigo' | 'emerald' | 'amber' | 'rose' | 'slate';
  nodes: FlowchartNode[];
}

export const THALER_FLOWCHART_STAGES: FlowchartStage[] = [
  {
    stageId: 0,
    stageName: 'Tahap 0: Standarisasi & Kalibrasi Kertas',
    stageNameEn: 'Stage 0: Standardization & Paper Calibration',
    subtitle: 'Preflight Calibration Gate',
    subtitleEn: 'Preflight Calibration Gate',
    clinicalObjective: 'Memastikan kecepatan dan voltase kertas standar sebelum melakukan pengukuran interval dan voltase.',
    clinicalObjectiveEn: 'Confirm standard paper speed and voltage calibration before calculating intervals and voltages.',
    themeColor: 'slate',
    nodes: [
      {
        id: 'node-0-1',
        stageId: 0,
        stepBadge: 'Pra-Langkah',
        stepBadgeEn: 'Pre-Step',
        questionTitle: 'Apakah kalibrasi kertas EKG sudah standar (25 mm/s dan 10 mm/mV)?',
        questionTitleEn: 'Is ECG paper calibration standard (25 mm/s and 10 mm/mV)?',
        clinicalDirective: 'Periksa pulsa kalibrasi kotak pada tepi kertas atau teks header mesin EKG.',
        clinicalDirectiveEn: 'Inspect the calibration pulse box at the paper margin or the ECG machine header.',
        keyLeads: ['Kotak Kalibrasi', 'Lead II'],
        branches: [
          {
            label: 'Standar Rumah Sakit (25 mm/s, 10 mm/mV)',
            labelEn: 'Hospital Standard (25 mm/s, 10 mm/mV)',
            condition: 'Tinggi pulsa 10 mm (2 kotak besar) = 1.0 mV, lebar 1 kotak kecil = 40 ms.',
            conditionEn: 'Pulse height 10 mm (2 large boxes) = 1.0 mV, 1 small box width = 40 ms.',
            finding: 'Gunakan kaidah baku: 1 kotak kecil = 0.04s, 1 kotak besar = 0.20s.',
            findingEn: 'Apply standard rules: 1 small box = 0.04s, 1 large box = 0.20s.',
            diagnosticOutcome: 'Kalibrasi Valid: Siap untuk interpretasi diagnostik.',
            diagnosticOutcomeEn: 'Valid Calibration: Ready for diagnostic interpretation.',
            status: 'NORMAL',
            targetCaseId: 'case_foundations_anatomy',
            targetStepNumber: 1,
            formula: '1\\text{ mm} = 0.04\\text{ s}, 10\\text{ mm} = 1.0\\text{ mV}',
          },
          {
            label: 'Non-Standar (50 mm/s atau Sensitivitas Ganda)',
            labelEn: 'Non-Standard (50 mm/s or Double Sensitivity)',
            condition: 'Kecepatan 50 mm/s atau sensitivitas 5 mm/mV (sering pada QRS voltase tinggi).',
            conditionEn: 'Speed 50 mm/s or sensitivity 5 mm/mV (often used for high-voltage QRS).',
            finding: 'Koreksi perhitungan: Bagi dua durasi interval jika 50 mm/s, kalikan dua voltase jika 5 mm/mV.',
            findingEn: 'Calculation correction: Halve interval durations if 50 mm/s, double voltages if 5 mm/mV.',
            diagnosticOutcome: 'Waspada Artefak Kecepatan: Sesuaikan seluruh batas normal.',
            diagnosticOutcomeEn: 'Speed Artifact Alert: Adjust all normal diagnostic limits.',
            status: 'WARNING',
            targetCaseId: 'case_foundations_anatomy',
            targetStepNumber: 1,
          },
        ],
      },
    ],
  },
  {
    stageId: 1,
    stageName: 'Tahap 1: Laju & Irama Jantung',
    stageNameEn: 'Stage 1: Heart Rate & Rhythm',
    subtitle: 'Rate & Rhythm: Sinus vs Aritmia',
    subtitleEn: 'Rate & Rhythm: Sinus vs Arrhythmia',
    clinicalObjective: 'Menentukan apakah irama berasal dari nodus SA dan menghitung frekuensi denyut ventrikel.',
    clinicalObjectiveEn: 'Determine whether rhythm originates from the SA node and calculate ventricular rate.',
    themeColor: 'blue',
    nodes: [
      {
        id: 'node-1-1',
        stageId: 1,
        stepBadge: 'Langkah 1.1',
        stepBadgeEn: 'Step 1.1',
        questionTitle: 'Apakah irama teratur (regular) atau tidak teratur (irregular)?',
        questionTitleEn: 'Is the rhythm regular or irregular?',
        clinicalDirective: 'Bandingkan interval R-R menggunakan jangka ukur atau kertas pada Sadapan II ritme panjang.',
        clinicalDirectiveEn: 'Compare R-R intervals using calipers or paper strip along rhythm lead II.',
        keyLeads: ['II', 'V1'],
        branches: [
          {
            label: 'Irama Teratur (Regular)',
            labelEn: 'Regular Rhythm',
            condition: 'Interval R-R konstan sepanjang rekaman.',
            conditionEn: 'Constant R-R intervals throughout the tracing.',
            finding: 'Gunakan Rumus 300 / kotak besar atau 1500 / kotak kecil.',
            findingEn: 'Use the 300 large-box rule or 1500 small-box rule.',
            diagnosticOutcome: 'Laju dihitung presisi. Normal: 60 - 100 bpm; Bradikardia: <60; Takikardia: >100.',
            diagnosticOutcomeEn: 'Rate precisely determined. Normal: 60 - 100 bpm; Bradycardia: <60; Tachycardia: >100.',
            status: 'NORMAL',
            targetCaseId: 'case_normal_sinus',
            targetStepNumber: 2,
            formula: '\\text{HR} = \\frac{300}{n_{\\text{kotak besar}}} = \\frac{1500}{n_{\\text{kotak kecil}}}',
          },
          {
            label: 'Ireguler Total (Irregularly Irregular)',
            labelEn: 'Irregularly Irregular',
            condition: 'Interval R-R tidak beraturan tanpa pola berulang, tidak ada gelombang P teratur.',
            conditionEn: 'Erratic R-R intervals without repeating pattern; absence of discrete P waves.',
            finding: 'Hitung jumlah kompleks QRS dalam strip 6 detik (30 kotak besar), lalu kalikan 10.',
            findingEn: 'Count QRS complexes in a 6-second strip (30 large boxes) and multiply by 10.',
            diagnosticOutcome: 'Fibrilasi Atrium (Atrial Fibrillation / AFib).',
            diagnosticOutcomeEn: 'Atrial Fibrillation (AFib).',
            status: 'PATHOLOGIC',
            targetCaseId: 'case_atrial_fibrillation',
            targetStepNumber: 5,
            formula: '\\text{HR} = n_{\\text{QRS dalam 30 kotak besar}} \\times 10',
          },
          {
            label: 'Irama Cepat Teratur dengan Gelombang Gigi Gergaji',
            labelEn: 'Regular Rapid Rhythm with Sawtooth Waves',
            condition: 'Gelombang P digantikan gelombang flutter (sawtooth) kontinu frekuensi 300 bpm.',
            conditionEn: 'P waves replaced by continuous flutter waves at 300 bpm.',
            finding: 'Konduksi AV 2:1 menghasilkan laju ventrikel klasik tepat 150 bpm.',
            findingEn: '2:1 AV conduction produces classic ventricular rate of exactly 150 bpm.',
            diagnosticOutcome: 'Atrial Flutter dengan Blok AV 2:1.',
            diagnosticOutcomeEn: 'Atrial Flutter with 2:1 AV Block.',
            status: 'PATHOLOGIC',
            targetCaseId: 'case_atrial_flutter',
            targetStepNumber: 5,
          },
        ],
      },
      {
        id: 'node-1-2',
        stageId: 1,
        stepBadge: 'Langkah 1.2',
        stepBadgeEn: 'Step 1.2',
        questionTitle: 'Apakah terdapat gelombang P normal mendahului setiap kompleks QRS?',
        questionTitleEn: 'Are normal P waves preceding every QRS complex?',
        clinicalDirective: 'Periksa polaritas P pada sadapan inferior (II, III, aVF) dan sadapan aVR.',
        clinicalDirectiveEn: 'Check P wave polarity in inferior leads (II, III, aVF) and lead aVR.',
        keyLeads: ['II', 'aVR'],
        branches: [
          {
            label: 'Gelombang P Sinus Normal',
            labelEn: 'Normal Sinus P Waves',
            condition: 'P defleksi positif di II, terbalik di aVR, rasio P terhadap QRS tepat 1:1.',
            conditionEn: 'P upright in lead II, inverted in aVR, exact 1:1 P:QRS ratio.',
            finding: 'Depolarisasi atrium bermula normal dari Nodus Sinoatrial (SA Node).',
            findingEn: 'Atrial depolarization originates normally from the Sinoatrial (SA) node.',
            diagnosticOutcome: 'Irama Sinus Fisiologis.',
            diagnosticOutcomeEn: 'Physiological Sinus Rhythm.',
            status: 'NORMAL',
            targetCaseId: 'case_normal_sinus',
            targetStepNumber: 5,
          },
          {
            label: 'Gelombang P Hilang / Terbalik / Disosiasi',
            labelEn: 'Absent, Inverted, or Dissociated P Waves',
            condition: 'P tidak tampak, mendahului QRS dengan PR sangat pendek, atau timbul setelah QRS.',
            conditionEn: 'P waves absent, preceding QRS with very short PR, or appearing after QRS.',
            finding: 'Fokus pemicu berasal dari Nodus AV (Junctional) atau ventrikel.',
            findingEn: 'Pacemaker focus originates from AV junction or ventricles.',
            diagnosticOutcome: 'Irama Junctional Escape atau Disosiasi AV.',
            diagnosticOutcomeEn: 'Junctional Escape Rhythm or AV Dissociation.',
            status: 'WARNING',
            targetCaseId: 'case_complete_heart_block',
            targetStepNumber: 5,
          },
        ],
      },
    ],
  },
  {
    stageId: 2,
    stageName: 'Tahap 2: Interval & Konduksi',
    stageNameEn: 'Stage 2: Intervals & Conduction',
    subtitle: 'PR Interval, QRS Duration, QT/QTc',
    subtitleEn: 'PR Interval, QRS Duration, QT/QTc',
    clinicalObjective: 'Mengevaluasi kecepatan transmisi listrik melalui Nodus AV, sistem berkas cabang, dan repolarisasi ventrikel.',
    clinicalObjectiveEn: 'Evaluate electrical transmission velocity through the AV node, bundle branch system, and ventricular repolarization.',
    themeColor: 'indigo',
    nodes: [
      {
        id: 'node-2-1',
        stageId: 2,
        stepBadge: 'Langkah 2.1',
        stepBadgeEn: 'Step 2.1',
        questionTitle: 'Berapakah durasi Interval PR (Batas Normal: 120 - 200 ms / 3 - 5 kotak kecil)?',
        questionTitleEn: 'What is the PR interval duration (Normal: 120 - 200 ms / 3 - 5 small boxes)?',
        clinicalDirective: 'Ukur dari awal gelombang P hingga awal defleksi kompleks QRS pada Sadapan II.',
        clinicalDirectiveEn: 'Measure from the start of the P wave to the beginning of the QRS deflection in Lead II.',
        keyLeads: ['II', 'V1'],
        branches: [
          {
            label: 'PR Normal (120 - 200 ms)',
            labelEn: 'Normal PR (120 - 200 ms)',
            condition: 'Durasi berada dalam rentang 3 hingga 5 kotak kecil konsisten.',
            conditionEn: 'Duration consistently within 3 to 5 small boxes.',
            finding: 'Transmisi impuls dari atrium ke ventrikel berlangsung normal.',
            findingEn: 'Normal transmission from atria to ventricles.',
            diagnosticOutcome: 'Konduksi Nodus AV Normal.',
            diagnosticOutcomeEn: 'Normal AV Nodal Conduction.',
            status: 'NORMAL',
            targetCaseId: 'case_normal_sinus',
            targetStepNumber: 3,
          },
          {
            label: 'PR Memanjang Konstan (> 200 ms)',
            labelEn: 'Constant Prolonged PR (> 200 ms)',
            condition: 'PR interval konsisten melebihi 5 kotak kecil pada setiap denyut tanpa ada QRS yang hilang.',
            conditionEn: 'PR interval consistently exceeds 5 small boxes on every beat without dropped QRS.',
            finding: 'Perlambatan transmisi fisiologis atau efek farmakologis pada Nodus AV.',
            findingEn: 'Physiological delay or pharmacological effect on AV node.',
            diagnosticOutcome: 'Blok AV Derajat 1 (First-Degree AV Block).',
            diagnosticOutcomeEn: 'First-Degree AV Block.',
            status: 'WARNING',
            targetCaseId: 'case_inferior_stemi',
            targetStepNumber: 6,
          },
          {
            label: 'Disosiasi AV Lengkap (P dan QRS Berjalan Mandiri)',
            labelEn: 'Complete AV Dissociation (Independent P and QRS)',
            condition: 'Gelombang P berirama teratur sendiri, kompleks QRS lambat teratur sendiri tanpa hubungan.',
            conditionEn: 'P waves regular and independent; QRS slow and regular with no relationship to P.',
            finding: 'Tidak ada impuls atrium yang dapat menembus Nodus AV ke ventrikel.',
            findingEn: 'No atrial impulses penetrate the AV node to ventricles.',
            diagnosticOutcome: 'Blok AV Derajat 3 / Total (Third-Degree AV Block). Indikasi Pacu Jantung Cito.',
            diagnosticOutcomeEn: 'Third-Degree (Complete) AV Block. Emergent Pacemaker Indicated.',
            status: 'PATHOLOGIC',
            targetCaseId: 'case_complete_heart_block',
            targetStepNumber: 6,
          },
          {
            label: 'PR Pendek (< 120 ms) Disertai Gelombang Delta',
            labelEn: 'Short PR (< 120 ms) with Delta Wave',
            condition: 'Interval PR kurang dari 3 kotak kecil dengan kelandaian awal pada gelombang R.',
            conditionEn: 'PR interval less than 3 small boxes with slurred initial QRS upstroke.',
            finding: 'Depolarisasi prematur melalui jalur aksesori atrioventrikular (Berkas Kent).',
            findingEn: 'Pre-excitation through an accessory pathway (Bundle of Kent).',
            diagnosticOutcome: 'Sindrom Wolff-Parkinson-White (WPW Pre-excitation).',
            diagnosticOutcomeEn: 'Wolff-Parkinson-White (WPW) Syndrome.',
            status: 'PATHOLOGIC',
            targetCaseId: 'case_wpw_syndrome',
            targetStepNumber: 7,
          },
        ],
      },
      {
        id: 'node-2-2',
        stageId: 2,
        stepBadge: 'Langkah 2.2',
        stepBadgeEn: 'Step 2.2',
        questionTitle: 'Berapakah durasi kompleks QRS (Batas Normal: < 120 ms / < 3 kotak kecil)?',
        questionTitleEn: 'What is the QRS duration (Normal: < 120 ms / < 3 small boxes)?',
        clinicalDirective: 'Periksa morfologi QRS pada sadapan prekordial anterior V1 dan lateral I, V5, V6.',
        clinicalDirectiveEn: 'Inspect QRS morphology in right precordial V1 and lateral leads I, V5, V6.',
        keyLeads: ['V1', 'V6', 'I'],
        branches: [
          {
            label: 'QRS Sempit Normal (< 120 ms)',
            labelEn: 'Normal Narrow QRS (< 120 ms)',
            condition: 'Durasi QRS kurang dari 3 kotak kecil.',
            conditionEn: 'QRS duration less than 3 small boxes.',
            finding: 'Depolarisasi ventrikel terkoordinasi cepat melalui cabang berkas kiri dan kanan.',
            findingEn: 'Rapid synchronized ventricular depolarization via right and left bundle branches.',
            diagnosticOutcome: 'Konduksi Intraventrikular Normal.',
            diagnosticOutcomeEn: 'Normal Intraventricular Conduction.',
            status: 'NORMAL',
            targetCaseId: 'case_normal_sinus',
            targetStepNumber: 3,
          },
          {
            label: "QRS Lebar (>= 120 ms) dengan Morfologi RSR' di V1",
            labelEn: "Wide QRS (>= 120 ms) with RSR' in V1",
            condition: 'Gelombang telinga kelinci (rabbit ears) di V1, gelombang S lebar tumpul di V6.',
            conditionEn: 'Rabbit ears in V1, broad slurred S wave in V6.',
            finding: 'Hambatan konduksi total pada Cabang Berkas Kanan.',
            findingEn: 'Complete conduction block in the Right Bundle Branch.',
            diagnosticOutcome: 'Complete Right Bundle Branch Block (RBBB).',
            diagnosticOutcomeEn: 'Complete Right Bundle Branch Block (RBBB).',
            status: 'PATHOLOGIC',
            targetCaseId: 'case_rbbb',
            targetStepNumber: 6,
          },
          {
            label: 'QRS Lebar (>= 120 ms) dengan R Bertakik di I, aVL, V5-V6',
            labelEn: 'Wide QRS (>= 120 ms) with Notched R in I, aVL, V5-V6',
            condition: 'Gelombang R lebar terpancung tanpa gelombang Q di lateral, kompleks QS dalam di V1.',
            conditionEn: 'Broad notched R wave without Q waves in lateral leads; deep QS complex in V1.',
            finding: 'Hambatan konduksi total pada Cabang Berkas Kiri.',
            findingEn: 'Complete conduction block in the Left Bundle Branch.',
            diagnosticOutcome: 'Complete Left Bundle Branch Block (LBBB). Mengaburkan evaluasi iskemia.',
            diagnosticOutcomeEn: 'Complete Left Bundle Branch Block (LBBB). Obscures ischemia evaluation.',
            status: 'PATHOLOGIC',
            targetCaseId: 'case_lbbb',
            targetStepNumber: 6,
          },
        ],
      },
      {
        id: 'node-2-3',
        stageId: 2,
        stepBadge: 'Langkah 2.3',
        stepBadgeEn: 'Step 2.3',
        questionTitle: 'Berapakah Interval QT dan QTc (Normal: <= 440 ms pria, <= 460 ms wanita)?',
        questionTitleEn: 'What are the QT and QTc intervals (Normal: <= 440 ms men, <= 460 ms women)?',
        clinicalDirective: 'Ukur dari awal QRS hingga akhir gelombang T. Bandingkan dengan setengah interval R-R.',
        clinicalDirectiveEn: 'Measure from QRS onset to T wave termination. Compare with half the R-R interval.',
        keyLeads: ['II', 'V5'],
        branches: [
          {
            label: 'QT Normal (QT < 1/2 Interval R-R)',
            labelEn: 'Normal QT (QT < 1/2 R-R Interval)',
            condition: 'Akhir gelombang T jatuh sebelum titik tengah interval R-R sebelumnya.',
            conditionEn: 'T wave terminates before the midpoint of the preceding R-R interval.',
            finding: 'Repolarisasi ventrikel berlangsung tepat waktu.',
            findingEn: 'Ventricular repolarization completes on time.',
            diagnosticOutcome: 'Interval QT Fisiologis Normal.',
            diagnosticOutcomeEn: 'Normal Physiological QT Interval.',
            status: 'NORMAL',
            targetCaseId: 'case_normal_sinus',
            targetStepNumber: 3,
            formula: '\\text{QTc} = \\frac{\\text{QT}}{\\sqrt{\\text{RR}}} \\le 0.44\\text{ s}',
          },
          {
            label: 'QTc Memanjang (> 460 - 500 ms)',
            labelEn: 'Prolonged QTc (> 460 - 500 ms)',
            condition: 'Gelombang T berakhir melewati separuh jarak R-R.',
            conditionEn: 'T wave extends past the halfway point of the R-R interval.',
            finding: 'Dispersi repolarisasi abnormal akibat gangguan elektrolit atau obat antiaritmia.',
            findingEn: 'Abnormal repolarization dispersion from electrolytes or antiarrhythmic drugs.',
            diagnosticOutcome: 'Long QTc Syndrome. Waspada Aritmia Maligna Torsades de Pointes.',
            diagnosticOutcomeEn: 'Long QTc Syndrome. High risk for polymorphic VT / Torsades de Pointes.',
            status: 'PATHOLOGIC',
            targetCaseId: 'case_hyperkalemia',
            targetStepNumber: 3,
          },
          {
            label: 'QTc Memendek dengan ST Berparuh (Sagging ST)',
            labelEn: 'Shortened QTc with Scooped ST Depression',
            condition: 'Depresi ST landai cekung ke bawah seperti kurva kumis Salvador Dali.',
            conditionEn: 'Downsloping concave ST depression resembling Salvador Dali mustache curve.',
            finding: 'Efek farmakodinamik digitalis pada pompa Na+/K+ ATPase miosit ventrikel.',
            findingEn: 'Digitalis pharmacodynamic effect on ventricular myocyte Na+/K+ ATPase.',
            diagnosticOutcome: 'Efek Terapeutik Digoksin.',
            diagnosticOutcomeEn: 'Therapeutic Digoxin Effect.',
            status: 'WARNING',
            targetCaseId: 'case_digoxin_effect',
            targetStepNumber: 3,
          },
        ],
      },
    ],
  },
  {
    stageId: 3,
    stageName: 'Tahap 3: Sumbu Jantung (Frontal Plane Axis)',
    stageNameEn: 'Stage 3: Electrical Axis (Frontal Plane Axis)',
    subtitle: 'Axis: Normal vs LAD vs RAD vs Extreme',
    subtitleEn: 'Axis: Normal vs LAD vs RAD vs Extreme',
    clinicalObjective: 'Menentukan orientasi vektor listrik rata-rata depolarisasi ventrikel pada bidang frontal.',
    clinicalObjectiveEn: 'Determine the mean electrical vector of ventricular depolarization in the frontal plane.',
    themeColor: 'emerald',
    nodes: [
      {
        id: 'node-3-1',
        stageId: 3,
        stepBadge: 'Langkah 3.1',
        stepBadgeEn: 'Step 3.1',
        questionTitle: 'Metode Kuadran Cepat: Berapakah defleksi netto QRS pada Sadapan I dan aVF?',
        questionTitleEn: 'Fast Quadrant Method: What is the net QRS deflection in Leads I and aVF?',
        clinicalDirective: 'Hitung tinggi gelombang R dikurangi kedalaman gelombang S pada Sadapan I dan aVF.',
        clinicalDirectiveEn: 'Calculate R wave height minus S wave depth in Lead I and Lead aVF.',
        keyLeads: ['I', 'aVF', 'II'],
        branches: [
          {
            label: 'Sadapan I (+) dan aVF (+) -> Aksis Normal',
            labelEn: 'Lead I (+) and aVF (+) -> Normal Axis',
            condition: 'Kompleks QRS didominasi defleksi positif pada kedua sadapan tegak lurus.',
            conditionEn: 'QRS complex predominantly positive in both orthogonal leads.',
            finding: 'Vektor listrik berada di antara 0 derajat hingga +90 derajat.',
            findingEn: 'Electrical vector lies between 0 degrees and +90 degrees.',
            diagnosticOutcome: 'Aksis Bidang Frontal Normal.',
            diagnosticOutcomeEn: 'Normal Frontal Plane Axis.',
            status: 'NORMAL',
            targetCaseId: 'case_normal_sinus',
            targetStepNumber: 4,
          },
          {
            label: 'Sadapan I (+) dan aVF (-) -> Cek Sadapan II',
            labelEn: 'Lead I (+) and aVF (-) -> Check Lead II',
            condition: 'Sadapan I positif, aVF negatif. Periksa polaritas Sadapan II: jika II (+), aksis normal (-30 hingga 0); jika II (-), deviasi aksis kiri.',
            conditionEn: 'Lead I positive, aVF negative. Check Lead II polarity: if II (+), normal axis (-30 to 0); if II (-), left axis deviation.',
            finding: 'Vektor bergeser ke kuadran superior kiri (-30 derajat hingga -90 derajat).',
            findingEn: 'Vector shifts to the left superior quadrant (-30 degrees to -90 degrees).',
            diagnosticOutcome: 'Left Axis Deviation (LAD). Etiologi: LAFB, LVH, Infark Inferior.',
            diagnosticOutcomeEn: 'Left Axis Deviation (LAD). Etiology: LAFB, LVH, Inferior Infarction.',
            status: 'WARNING',
            targetCaseId: 'case_lahb',
            targetStepNumber: 4,
          },
          {
            label: 'Sadapan I (-) dan aVF (+) -> Right Axis Deviation',
            labelEn: 'Lead I (-) and aVF (+) -> Right Axis Deviation',
            condition: 'Sadapan I didominasi defleksi negatif, aVF didominasi defleksi positif.',
            conditionEn: 'Lead I predominantly negative, aVF predominantly positive.',
            finding: 'Vektor bergeser ke kuadran kanan (+90 derajat hingga +180 derajat).',
            findingEn: 'Vector shifts to the right quadrant (+90 degrees to +180 degrees).',
            diagnosticOutcome: 'Right Axis Deviation (RAD). Etiologi: RVH, Emboli Paru, LPFB.',
            diagnosticOutcomeEn: 'Right Axis Deviation (RAD). Etiology: RVH, Pulmonary Embolism, LPFB.',
            status: 'WARNING',
            targetCaseId: 'case_rbbb',
            targetStepNumber: 4,
          },
          {
            label: 'Sadapan I (-) dan aVF (-) -> Extreme Axis',
            labelEn: 'Lead I (-) and aVF (-) -> Extreme Axis',
            condition: 'Defleksi negatif mendominasi kedua sadapan I dan aVF.',
            conditionEn: 'Negative deflections dominate both Leads I and aVF.',
            finding: 'Vektor mengarah ke kuadran barat laut (-90 derajat hingga 180 derajat).',
            findingEn: 'Vector points toward northwest quadrant (-90 degrees to 180 degrees).',
            diagnosticOutcome: 'Extreme Right Axis / "No Man\'s Land". Waspada VT atau lead terbalik.',
            diagnosticOutcomeEn: 'Extreme Right Axis / "No Man\'s Land". Consider VT or reversed arm leads.',
            status: 'PATHOLOGIC',
            targetCaseId: 'case_normal_sinus',
            targetStepNumber: 4,
          },
        ],
      },
    ],
  },
  {
    stageId: 4,
    stageName: 'Tahap 4: Hipertrofi & Pembesaran Ruang Jantung',
    stageNameEn: 'Stage 4: Chamber Enlargement & Hypertrophy',
    subtitle: 'Chamber Enlargement: LVH, RVH, RAA, LAA',
    subtitleEn: 'Chamber Enlargement: LVH, RVH, RAA, LAA',
    clinicalObjective: 'Mendeteksi peningkatan tegangan voltase atau durasi akibat hipertrofi otot dan dilatasi atrium.',
    clinicalObjectiveEn: 'Detect increased voltage or duration resulting from myocardial hypertrophy and atrial dilation.',
    themeColor: 'amber',
    nodes: [
      {
        id: 'node-4-1',
        stageId: 4,
        stepBadge: 'Langkah 4.1',
        stepBadgeEn: 'Step 4.1',
        questionTitle: 'Apakah terdapat pembesaran atrium pada Sadapan II dan V1?',
        questionTitleEn: 'Is there atrial enlargement in Leads II and V1?',
        clinicalDirective: 'Periksa tinggi puncak P di Sadapan II dan kedalaman defleksi negatif di V1.',
        clinicalDirectiveEn: 'Inspect P wave peak height in Lead II and negative terminal deflection depth in V1.',
        keyLeads: ['II', 'V1'],
        branches: [
          {
            label: 'Morfologi Atrium Normal',
            labelEn: 'Normal Atrial Morphology',
            condition: 'P tinggi < 2.5 mm di II, lebar < 120 ms, komponen bifasik V1 minimal.',
            conditionEn: 'P height < 2.5 mm in II, duration < 120 ms, minimal biphasic component in V1.',
            finding: 'Tidak ada tanda dilatasi atrium kanan maupun kiri.',
            findingEn: 'No evidence of right or left atrial dilation.',
            diagnosticOutcome: 'Ruang Atrium Normal.',
            diagnosticOutcomeEn: 'Normal Atrial Chambers.',
            status: 'NORMAL',
            targetCaseId: 'case_normal_sinus',
            targetStepNumber: 8,
          },
          {
            label: 'P Pulmonale / RAA (Right Atrial Abnormality)',
            labelEn: 'P Pulmonale / RAA (Right Atrial Abnormality)',
            condition: 'Gelombang P tinggi lancip melebihi 2.5 mm di sadapan inferior (II, III, aVF).',
            conditionEn: 'Peaked tall P wave exceeding 2.5 mm in inferior leads (II, III, aVF).',
            finding: 'Beban tekanan atrium kanan akibat hipertensi pulmonal atau PPOK.',
            findingEn: 'Right atrial pressure overload from pulmonary hypertension or COPD.',
            diagnosticOutcome: 'Pembesaran Atrium Kanan (P Pulmonale).',
            diagnosticOutcomeEn: 'Right Atrial Enlargement (P Pulmonale).',
            status: 'WARNING',
            targetCaseId: 'case_lvh_strain',
            targetStepNumber: 8,
          },
          {
            label: 'P Mitrale / LAA (Left Atrial Abnormality)',
            labelEn: 'P Mitrale / LAA (Left Atrial Abnormality)',
            condition: 'Gelombang P berlekuk lebar >= 120 ms di II, atau defleksi terminal negatif di V1 >= 1 mm dalam dan >= 40 ms lebar.',
            conditionEn: 'Broad notched P wave >= 120 ms in II, or negative terminal deflection in V1 >= 1 mm deep and >= 40 ms wide.',
            finding: 'Dilatasi atrium kiri akibat penyakit katup mitral atau hipertensi sistemik kronis.',
            findingEn: 'Left atrial dilation from mitral valve disease or chronic systemic hypertension.',
            diagnosticOutcome: 'Pembesaran Atrium Kiri (P Mitrale / Indeks Morris Positif).',
            diagnosticOutcomeEn: 'Left Atrial Enlargement (P Mitrale / Positive Morris Index).',
            status: 'WARNING',
            targetCaseId: 'case_lvh_strain',
            targetStepNumber: 8,
          },
        ],
      },
      {
        id: 'node-4-2',
        stageId: 4,
        stepBadge: 'Langkah 4.2',
        stepBadgeEn: 'Step 4.2',
        questionTitle: 'Apakah kriteria voltase hipertrofi ventrikel terpenuhi (LVH / RVH)?',
        questionTitleEn: 'Are ventricular hypertrophy voltage criteria met (LVH / RVH)?',
        clinicalDirective: 'Hitung kriteria Sokolow-Lyon dan periksa pola regangan (strain pattern).',
        clinicalDirectiveEn: 'Calculate Sokolow-Lyon criteria and evaluate repolarization strain pattern.',
        keyLeads: ['V1', 'V5', 'V6', 'aVL', 'I'],
        branches: [
          {
            label: 'Left Ventricular Hypertrophy (LVH Kriteria Sokolow-Lyon)',
            labelEn: 'Left Ventricular Hypertrophy (LVH Sokolow-Lyon Criteria)',
            condition: 'Kedalaman S di V1 ditambah tinggi R di V5 atau V6 >= 35 mm (3.5 mV).',
            conditionEn: 'S depth in V1 plus R height in V5 or V6 >= 35 mm (3.5 mV).',
            finding: 'Penebalan dinding ventrikel kiri disertai depresi ST asimetris dan T inversi (Strain Pattern) di sadapan lateral.',
            findingEn: 'Left ventricular wall thickening with asymmetric ST depression and T inversion (Strain Pattern) in lateral leads.',
            diagnosticOutcome: 'LVH dengan Repolarization Strain Pattern.',
            diagnosticOutcomeEn: 'LVH with Repolarization Strain Pattern.',
            status: 'PATHOLOGIC',
            targetCaseId: 'case_lvh_strain',
            targetStepNumber: 8,
            formula: 'S_{\\text{V1}} + R_{\\text{V5/V6}} \\ge 35\\text{ mm} \\quad (3.5\\text{ mV})',
          },
          {
            label: 'Right Ventricular Hypertrophy (RVH)',
            labelEn: 'Right Ventricular Hypertrophy (RVH)',
            condition: 'Gelombang R tinggi di V1 (R/S rasio > 1 atau R >= 7 mm) disertai Right Axis Deviation.',
            conditionEn: 'Tall R wave in V1 (R/S ratio > 1 or R >= 7 mm) accompanied by Right Axis Deviation.',
            finding: 'Vektor ventrikel didominasi oleh massa ventrikel kanan.',
            findingEn: 'Ventricular electrical forces dominated by right ventricular mass.',
            diagnosticOutcome: 'Hipertrofi Ventrikel Kanan (RVH).',
            diagnosticOutcomeEn: 'Right Ventricular Hypertrophy (RVH).',
            status: 'PATHOLOGIC',
            targetCaseId: 'case_rbbb',
            targetStepNumber: 8,
          },
        ],
      },
    ],
  },
  {
    stageId: 5,
    stageName: 'Tahap 5: Iskemia & Infark Miokard',
    stageNameEn: 'Stage 5: Myocardial Ischemia & Infarction',
    subtitle: 'Ischemia, Infarction & Systemic Conditions',
    subtitleEn: 'Ischemia, Infarction & Systemic Conditions',
    clinicalObjective: 'Mendeteksi oklusi arteri koroner akut (STEMI), lokalisasi infark, serta membedakan elevasi ST non-iskemik.',
    clinicalObjectiveEn: 'Detect acute coronary artery occlusion (STEMI), localize infarction, and differentiate non-ischemic ST elevation.',
    themeColor: 'rose',
    nodes: [
      {
        id: 'node-5-1',
        stageId: 5,
        stepBadge: 'Langkah 5.1',
        stepBadgeEn: 'Step 5.1',
        questionTitle: 'Apakah terdapat Elevasi Segmen ST Baru (Acute STEMI)?',
        questionTitleEn: 'Is there new ST-Segment Elevation (Acute STEMI)?',
        clinicalDirective: 'Periksa elevasi titik J pada sadapan kontigu dan cari depresi ST resiprokal penegas.',
        clinicalDirectiveEn: 'Inspect J-point elevation in contiguous leads and identify reciprocal ST depression.',
        keyLeads: ['V1', 'V2', 'V3', 'V4', 'II', 'III', 'aVF', 'I', 'aVL'],
        branches: [
          {
            label: 'STEMI Dinding Inferior dengan Depresi Resiprokal',
            labelEn: 'Inferior Wall STEMI with Reciprocal Depression',
            condition: 'Elevasi ST >= 1 mm di sadapan inferior (II, III, aVF) disertai depresi ST resiprokal di I dan aVL.',
            conditionEn: 'ST elevation >= 1 mm in inferior leads (II, III, aVF) with reciprocal ST depression in I and aVL.',
            finding: 'Oklusi akut Arteri Koroner Kanan (RCA). Waspada keterlibatan ventrikel kanan dan bradiaritmia.',
            findingEn: 'Acute occlusion of Right Coronary Artery (RCA). Watch for RV involvement and bradyarrhythmias.',
            diagnosticOutcome: 'Acute Inferior STEMI (Cito Reperfusi).',
            diagnosticOutcomeEn: 'Acute Inferior STEMI (Emergent Reperfusion).',
            status: 'PATHOLOGIC',
            targetCaseId: 'case_inferior_stemi',
            targetStepNumber: 9,
          },
          {
            label: 'STEMI Dinding Anterior Ekstensif (Tombstone Pattern)',
            labelEn: 'Extensive Anterior Wall STEMI (Tombstone Pattern)',
            condition: 'Elevasi ST cembung masif di sadapan prekordial V1-V4 (>= 2 mm) tanpa perlambatan konduksi.',
            conditionEn: 'Massive convex ST elevation in precordial leads V1-V4 (>= 2 mm) without conduction delay.',
            finding: 'Oklusi proksimal Arteri LAD (Left Anterior Descending). Risiko tinggi gagal jantung dan syok kardiogenik.',
            findingEn: 'Proximal LAD (Left Anterior Descending) occlusion. High risk of heart failure and cardiogenic shock.',
            diagnosticOutcome: 'Acute Extensive Anterior STEMI (Cito Reperfusi).',
            diagnosticOutcomeEn: 'Acute Extensive Anterior STEMI (Emergent Reperfusion).',
            status: 'PATHOLOGIC',
            targetCaseId: 'case_anterior_stemi',
            targetStepNumber: 9,
          },
        ],
      },
      {
        id: 'node-5-2',
        stageId: 5,
        stepBadge: 'Langkah 5.2',
        stepBadgeEn: 'Step 5.2',
        questionTitle: 'Diagnosa Banding Elevasi Segmen ST Non-Iskemik',
        questionTitleEn: 'Differential Diagnosis for Non-Ischemic ST Elevation',
        clinicalDirective: 'Evaluasi bentuk kelengkungan ST (cekung vs cembung) dan ada/tidaknya depresi segmen PR.',
        clinicalDirectiveEn: 'Evaluate ST curvature (concave vs convex) and the presence or absence of PR segment depression.',
        keyLeads: ['Semua Sadapan', 'II', 'aVR'],
        branches: [
          {
            label: 'Perikarditis Akut (Elevasi ST Cekung Difus)',
            labelEn: 'Acute Pericarditis (Diffuse Concave ST Elevation)',
            condition: 'Elevasi ST berbentuk cekung ke atas hampir di seluruh sadapan, disertai depresi PR pada sadapan II dan elevasi PR di aVR.',
            conditionEn: 'Upward concave ST elevation across nearly all leads, accompanied by PR depression in Lead II and PR elevation in aVR.',
            finding: 'Inflamasi difus epikardium tanpa oklusi koroner lokal.',
            findingEn: 'Diffuse epicardial inflammation without focal coronary occlusion.',
            diagnosticOutcome: 'Acute Viral Pericarditis. Terapi NSAID/Colchicine.',
            diagnosticOutcomeEn: 'Acute Viral Pericarditis. NSAID / Colchicine therapy.',
            status: 'WARNING',
            targetCaseId: 'case_acute_pericarditis',
            targetStepNumber: 9,
          },
          {
            label: 'Benign Early Repolarization (Varian Normal Atlet)',
            labelEn: 'Benign Early Repolarization (Normal Athletic Variant)',
            condition: 'Elevasi ST konkaf ringan dengan takik (notch) pada titik J di sadapan prekordial pada individu muda tanpa keluhan.',
            conditionEn: 'Mild concave ST elevation with J-point notching in precordial leads in young asymptomatic individuals.',
            finding: 'Repolarisasi ventrikel dini tanpa jejas miosit.',
            findingEn: 'Early ventricular repolarization without myocyte injury.',
            diagnosticOutcome: 'Benign Early Repolarization (Varian Jinak Non-Signifikan).',
            diagnosticOutcomeEn: 'Benign Early Repolarization (Non-Significant Variant).',
            status: 'NORMAL',
            targetCaseId: 'case_early_repol',
            targetStepNumber: 9,
          },
          {
            label: 'Hiperkalemia Berat (Gelombang T Tented)',
            labelEn: 'Severe Hyperkalemia (Tented T Waves)',
            condition: 'Gelombang T tinggi sempit simetris seperti tenda, mendatar/hilangnya gelombang P, pelebaran QRS.',
            conditionEn: 'Tall, narrow, symmetrical tented T waves, flattening/loss of P waves, and QRS widening.',
            finding: 'Kadar kalium serum tinggi (> 7.0 mEq/L) melumpuhkan eksitabilitas membran jantung.',
            findingEn: 'Serum potassium levels (> 7.0 mEq/L) paralyzing cardiac membrane excitability.',
            diagnosticOutcome: 'Severe Hyperkalemia. Cito Kalsium Glukonat & Insulin-Dextrose.',
            diagnosticOutcomeEn: 'Severe Hyperkalemia. Urgent Calcium Gluconate & Insulin-Dextrose.',
            status: 'PATHOLOGIC',
            targetCaseId: 'case_hyperkalemia',
            targetStepNumber: 9,
          },
        ],
      },
    ],
  },
];
