import { ClinicalFactors } from '../biophysics/types';

export interface ClinicalPreset {
  id: string;
  title: string;
  category: 'Normal' | 'Ischemia & Infarction' | 'Electrolytes' | 'Electrode Technique' | 'Arrhythmias & Conduction';
  description: string;
  patientInfo: {
    name: string;
    id: string;
    age: number;
    gender: 'Male' | 'Female';
    history: string;
  };
  factors: ClinicalFactors;
  electrodeMisplacement?: boolean;
}

export const CLINICAL_PRESETS: ClinicalPreset[] = [
  {
    id: 'normal_sinus',
    title: 'Normal Sinus Rhythm',
    category: 'Normal',
    description: 'Healthy adult resting baseline. Normal P-QRS-T concordance and physiological intervals.',
    patientInfo: {
      name: 'Rian Pratama',
      id: 'MRN-102941',
      age: 28,
      gender: 'Male',
      history: 'Pre-employment executive medical check-up. Asymptomatic, athletic.',
    },
    factors: {
      heartRate: 72,
      hsTroponinT: 6,
      ladStenosisPercent: 0,
      lcxStenosisPercent: 0,
      rcaStenosisPercent: 0,
      serumPotassium: 4.2,
      serumCalcium: 9.6,
      spo2Percent: 99,
      rhythmType: 'sinus',
    },
  },
  {
    id: 'anteroseptal_stemi',
    title: 'Acute Anteroseptal STEMI (Proximal LAD)',
    category: 'Ischemia & Infarction',
    description: '100% acute thrombus in LAD. Massive ST elevation in leads V1-V4 with reciprocal inferior depression.',
    patientInfo: {
      name: 'Bambang Sutrisno',
      id: 'MRN-840192',
      age: 58,
      gender: 'Male',
      history: 'Sudden crushing retrosternal chest pain radiating to left jaw for 90 minutes. Diaphoretic, pale.',
    },
    factors: {
      heartRate: 98,
      hsTroponinT: 4850,
      ladStenosisPercent: 100,
      lcxStenosisPercent: 20,
      rcaStenosisPercent: 15,
      serumPotassium: 4.1,
      serumCalcium: 9.4,
      spo2Percent: 95,
      rhythmType: 'sinus',
    },
  },
  {
    id: 'inferior_stemi',
    title: 'Acute Inferior STEMI (RCA Occlusion)',
    category: 'Ischemia & Infarction',
    description: '100% acute occlusion of Right Coronary Artery. ST elevation in II, III, aVF with reciprocal depression in I, aVL.',
    patientInfo: {
      name: 'Hendra Gunawan',
      id: 'MRN-723145',
      age: 64,
      gender: 'Male',
      history: 'Epigastric burning and nausea for 2 hours, mistaken for indigestion. Sinus bradycardia from nodal ischemia.',
    },
    factors: {
      heartRate: 52,
      hsTroponinT: 3200,
      ladStenosisPercent: 30,
      lcxStenosisPercent: 25,
      rcaStenosisPercent: 100,
      serumPotassium: 4.3,
      serumCalcium: 9.2,
      spo2Percent: 96,
      rhythmType: 'sinus',
    },
  },
  {
    id: 'severe_hyperkalemia',
    title: 'Severe Hyperkalemia (K+ 7.8 mmol/L)',
    category: 'Electrolytes',
    description: 'End-stage renal disease missing dialysis. Tall tented T waves, flattened P waves, marked QRS widening.',
    patientInfo: {
      name: 'Siti Aminah',
      id: 'MRN-991203',
      age: 62,
      gender: 'Female',
      history: 'Missed 2 hemodialysis sessions. Generalized weakness, profound fatigue.',
    },
    factors: {
      heartRate: 58,
      hsTroponinT: 12,
      ladStenosisPercent: 15,
      lcxStenosisPercent: 10,
      rcaStenosisPercent: 15,
      serumPotassium: 7.8,
      serumCalcium: 8.4,
      spo2Percent: 97,
      rhythmType: 'sinus',
    },
  },
  {
    id: 'hypokalemia_severe',
    title: 'Severe Hypokalemia with U Waves (K+ 2.7 mmol/L)',
    category: 'Electrolytes',
    description: 'Diuretic overuse. Flattened T waves, ST depression, prominent U waves in V2-V3, risk of Torsades.',
    patientInfo: {
      name: 'Dewi Kartika',
      id: 'MRN-449102',
      age: 45,
      gender: 'Female',
      history: 'Severe gastrointestinal fluid loss and loop diuretic overuse. Muscle cramps, palpitations.',
    },
    factors: {
      heartRate: 88,
      hsTroponinT: 8,
      ladStenosisPercent: 0,
      lcxStenosisPercent: 0,
      rcaStenosisPercent: 0,
      serumPotassium: 2.7,
      serumCalcium: 9.1,
      spo2Percent: 98,
      rhythmType: 'sinus',
    },
  },
  {
    id: 'high_v1_v2_error',
    title: 'Electrode Malposition: High V1/V2 (2nd ICS)',
    category: 'Electrode Technique',
    description: 'Electrodes placed 2 intercostal spaces too high. Produces negative P wave and terminal r prime (pseudo-Brugada).',
    patientInfo: {
      name: 'Agus Setiawan',
      id: 'MRN-551029',
      age: 36,
      gender: 'Male',
      history: 'Routine health screening. V1 and V2 incorrectly placed at 2nd intercostal space.',
    },
    factors: {
      heartRate: 74,
      hsTroponinT: 7,
      ladStenosisPercent: 0,
      lcxStenosisPercent: 0,
      rcaStenosisPercent: 0,
      serumPotassium: 4.1,
      serumCalcium: 9.5,
      spo2Percent: 99,
      rhythmType: 'sinus',
    },
    electrodeMisplacement: true,
  },
  {
    id: 'afib_rvr',
    title: 'Atrial Fibrillation with RVR',
    category: 'Arrhythmias & Conduction',
    description: 'Rapid chaotic f-waves (350-600 bpm) with irregularly irregular ventricular response at 135 bpm.',
    patientInfo: {
      name: 'Ratna Sari',
      id: 'MRN-338192',
      age: 68,
      gender: 'Female',
      history: 'Hypertension and sudden palpitations for 4 hours. Pulse deficit noted on examination.',
    },
    factors: {
      heartRate: 135,
      hsTroponinT: 18,
      ladStenosisPercent: 10,
      lcxStenosisPercent: 10,
      rcaStenosisPercent: 10,
      serumPotassium: 4.1,
      serumCalcium: 9.3,
      spo2Percent: 96,
      rhythmType: 'afib',
    },
  },
  {
    id: 'vfib_cardiac_arrest',
    title: 'Ventricular Fibrillation (Cardiac Arrest)',
    category: 'Arrhythmias & Conduction',
    description: 'Lethal chaotic 3D wandering rotor without organized ventricular contraction. Immediate defibrillation required.',
    patientInfo: {
      name: 'Dedi Kurniawan',
      id: 'MRN-609124',
      age: 54,
      gender: 'Male',
      history: 'Sudden collapse in triage room. Unresponsive, pulseless, gasping agonal respirations.',
    },
    factors: {
      heartRate: 230,
      hsTroponinT: 8500,
      ladStenosisPercent: 100,
      lcxStenosisPercent: 40,
      rcaStenosisPercent: 30,
      serumPotassium: 5.1,
      serumCalcium: 8.8,
      spo2Percent: 70,
      rhythmType: 'vfib_coarse',
    },
  },
  {
    id: 'asystole_flatline',
    title: 'Asystole (Ventricular Flatline)',
    category: 'Arrhythmias & Conduction',
    description: 'Total cessation of myocardial electrical activity. Isoelectric flatline with thermal noise. High-quality CPR.',
    patientInfo: {
      name: 'Wahyu Hidayat',
      id: 'MRN-881204',
      age: 71,
      gender: 'Male',
      history: 'Prolonged cardiac arrest following extensive anterior wall MI. Non-shockable rhythm.',
    },
    factors: {
      heartRate: 30,
      hsTroponinT: 12000,
      ladStenosisPercent: 100,
      lcxStenosisPercent: 80,
      rcaStenosisPercent: 90,
      serumPotassium: 6.2,
      serumCalcium: 7.9,
      spo2Percent: 60,
      rhythmType: 'asystole',
    },
  },
  {
    id: 'complete_heart_block',
    title: 'Complete Heart Block (3rd-Degree AV Block)',
    category: 'Arrhythmias & Conduction',
    description: 'Complete AV dissociation: atria fire at 75 bpm while wide idioventricular escape rhythm beats at 35 bpm.',
    patientInfo: {
      name: 'Sulaeman',
      id: 'MRN-441029',
      age: 76,
      gender: 'Male',
      history: 'Recurrent syncope, dizziness, and extreme fatigue. Regular slow pulse of 35 bpm.',
    },
    factors: {
      heartRate: 35,
      hsTroponinT: 22,
      ladStenosisPercent: 40,
      lcxStenosisPercent: 30,
      rcaStenosisPercent: 90,
      serumPotassium: 4.4,
      serumCalcium: 9.2,
      spo2Percent: 93,
      rhythmType: 'av_block_3rd',
    },
  },
  {
    id: 'ventricular_tachycardia',
    title: 'Monomorphic Ventricular Tachycardia (VT)',
    category: 'Arrhythmias & Conduction',
    description: 'Rapid wide QRS tachycardia (175 bpm) originating from an ectopic ventricular circuit. Northwest electrical axis.',
    patientInfo: {
      name: 'Ronald Siregar',
      id: 'MRN-552109',
      age: 60,
      gender: 'Male',
      history: 'Previous myocardial infarction 3 years ago. Sudden presyncope and rapid palpitations. BP 85/50 mmHg.',
    },
    factors: {
      heartRate: 175,
      hsTroponinT: 340,
      ladStenosisPercent: 75,
      lcxStenosisPercent: 20,
      rcaStenosisPercent: 30,
      serumPotassium: 3.8,
      serumCalcium: 9.0,
      spo2Percent: 90,
      rhythmType: 'vtach',
    },
  },
  {
    id: 'torsades_de_pointes',
    title: 'Torsades de Pointes (Long QT Syndrome)',
    category: 'Arrhythmias & Conduction',
    description: 'Polymorphic VT with continuous 3D axis precession ("twisting of the points") in severe hypokalemia/long QT.',
    patientInfo: {
      name: 'Linda Wijaya',
      id: 'MRN-771920',
      age: 42,
      gender: 'Female',
      history: 'Psychotropic medication combined with diuretic-induced hypokalemia. Recurrent syncope.',
    },
    factors: {
      heartRate: 215,
      hsTroponinT: 45,
      ladStenosisPercent: 0,
      lcxStenosisPercent: 0,
      rcaStenosisPercent: 0,
      serumPotassium: 2.6,
      serumCalcium: 7.8,
      spo2Percent: 88,
      rhythmType: 'torsades',
    },
  },
];
